obj-$(CONFIG_FILE_SYSTEM) += fs/
obj-$(CONFIG_USB) += usb/
obj-$(CONFIG_BLUETOOTH) += bluetooth/
obj-$(CONFIG_NET_BUF) += net/
obj-$(CONFIG_CONSOLE_SHELL) += shell/
obj-$(CONFIG_DISK_ACCESS) += disk/
obj-y += logging/
obj-y += debug/
