/*
 * Copyright (c) 2024 Realtek Semiconductor Corp.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_AMEBAG2_PINCTRL_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_AMEBAG2_PINCTRL_H_

/* PINMUX Function definitions */
#define AMEBA_GPIO           0
#define AMEBA_LOG_UART       1
#define AMEBA_SPIC0_FLASH    2
#define AMEBA_SPIC1_FLASH    3
#define AMEBA_SPIC1_PSRAM    4
#define AMEBA_ADC            5
#define AMEBA_CAP_TOUCH      5
#define AMEBA_TSSI           6
#define AMEBA_USB            7
#define AMEBA_RMII           8
#define AMEBA_SPI0           9
#define AMEBA_SPI1           10
#define AMEBA_SWD            11
#define AMEBA_SDIO_MST       12
#define AMEBA_SDIO_SLV       13
#define AMEBA_SIC            14
#define AMEBA_BT_IO          15
#define AMEBA_BT             16
#define AMEBA_DEBUG          17
#define AMEBA_I2S0_BCLK      32
#define AMEBA_I2S0_MCLK      33
#define AMEBA_I2S0_WS        34
#define AMEBA_I2S0_DIO0      35
#define AMEBA_I2S0_DIO1      36
#define AMEBA_I2S0_DIO2      37
#define AMEBA_I2S0_DIO3      38
#define AMEBA_LCD_RGB_DCLK   39
#define AMEBA_LCD_MCU_WR     39
#define AMEBA_LCD_RGB_DE     40
#define AMEBA_LCD_MCU_CSX    40
#define AMEBA_LCD_RGB_HSYNC  41
#define AMEBA_LCD_MCU_RD     41
#define AMEBA_LCD_RGB_TE     42
#define AMEBA_LCD_MCU_TE     42
#define AMEBA_LCD_RGB_VSYNC  43
#define AMEBA_LCD_MCU_VSYNC  43
#define AMEBA_LCD_MCU_DCX    44
#define AMEBA_LCD_D0         45
#define AMEBA_LCD_D1         46
#define AMEBA_LCD_D2         47
#define AMEBA_LCD_D3         48
#define AMEBA_LCD_D4         49
#define AMEBA_LCD_D5         50
#define AMEBA_LCD_D6         51
#define AMEBA_LCD_D7         52
#define AMEBA_LCD_D8         53
#define AMEBA_LCD_D9         54
#define AMEBA_LCD_D10        55
#define AMEBA_LCD_D11        56
#define AMEBA_LCD_D12        57
#define AMEBA_LCD_D13        58
#define AMEBA_LCD_D14        59
#define AMEBA_LCD_D15        60
#define AMEBA_LCD_D16        61
#define AMEBA_LCD_D17        62
#define AMEBA_LCD_D18        63
#define AMEBA_LCD_D19        64
#define AMEBA_LCD_D20        65
#define AMEBA_LCD_D21        66
#define AMEBA_LCD_D22        67
#define AMEBA_LCD_D23        68
#define AMEBA_SD_M_CLK       69
#define AMEBA_SD_M_CMD       70
#define AMEBA_SD_M_D0        71
#define AMEBA_SD_M_D1        72
#define AMEBA_SD_M_D2        73
#define AMEBA_SD_M_D3        74
#define AMEBA_SPI0_CLK       75
#define AMEBA_SPI0_MISO      76
#define AMEBA_SPI0_MOSI      77
#define AMEBA_SPI0_CS        78
#define AMEBA_SPI1_CLK       79
#define AMEBA_SPI1_MISO      80
#define AMEBA_SPI1_MOSI      81
#define AMEBA_SPI1_CS        82
#define AMEBA_SWD_CLK        83
#define AMEBA_SWD_DAT        84
#define AMEBA_DMIC_CLK       85
#define AMEBA_DMIC_DATA      86
#define AMEBA_LED_SCL        87
#define AMEBA_LED_SDA        88
#define AMEBA_I2C0_SCL       89
#define AMEBA_I2C0_SDA       90
#define AMEBA_I2C1_SCL       91
#define AMEBA_I2C1_SDA       92
#define AMEBA_RMII_MDIO      93
#define AMEBA_RMII_MDC       94
#define AMEBA_UART0_TXD      95
#define AMEBA_UART0_RXD      96
#define AMEBA_UART0_CTS      97
#define AMEBA_UART0_RTS      98
#define AMEBA_UART1_TXD      99
#define AMEBA_UART1_RXD      100
#define AMEBA_UART2_TXD      101
#define AMEBA_UART2_RXD      102
#define AMEBA_UART3_TXD      103
#define AMEBA_UART3_RXD      104
#define AMEBA_UART3_CTS      105
#define AMEBA_UART3_RTS      106
#define AMEBA_A2C0_TX        107
#define AMEBA_A2C0_RX        108
#define AMEBA_A2C1_TX        109
#define AMEBA_A2C1_RX        110
#define AMEBA_TIM4_PWM0      111
#define AMEBA_TIM4_PWM1      112
#define AMEBA_TIM4_PWM2      113
#define AMEBA_TIM4_PWM3      114
#define AMEBA_TIM5_PWM0      115
#define AMEBA_TIM5_PWM1      116
#define AMEBA_TIM5_PWM2      117
#define AMEBA_TIM5_PWM3      118
#define AMEBA_TIM6_PWM0      119
#define AMEBA_TIM6_PWM1      120
#define AMEBA_TIM6_PWM2      121
#define AMEBA_TIM6_PWM3      122
#define AMEBA_TIM7_PWM0      123
#define AMEBA_TIM7_PWM1      124
#define AMEBA_TIM7_PWM2      125
#define AMEBA_TIM7_PWM3      126
#define AMEBA_PWM_TIM4_TRIG  127
#define AMEBA_PWM_TIM5_TRIG  128
#define AMEBA_PWM_TIM6_TRIG  129
#define AMEBA_PWM_TIM7_TRIG  130
#define AMEBA_CAPT_TIM8_TRIG 131
#define AMEBA_IR_TX          132
#define AMEBA_IR_RX          133
#define AMEBA_ANT_SEL_P      134
#define AMEBA_ANT_SEL_N      135
#define AMEBA_TRSW_P         136
#define AMEBA_TRSW_N         137
#define AMEBA_PA_EN0         138
#define AMEBA_LNA_EN0        139
#define AMEBA_PA_EN1         140
#define AMEBA_LNA_EN1        141
#define AMEBA_BT_CLK_REQ     142
#define AMEBA_WLAN_ACT       143
#define AMEBA_BT_ACT         144
#define AMEBA_BT_STE         145
#define AMEBA_BT_CK          146
#define AMEBA_ZB_REQ         147
#define AMEBA_ZB_GRANT       148
#define AMEBA_ZB_PRI         149
#define AMEBA_BT_ANT_SW0     150
#define AMEBA_BT_ANT_SW1     151
#define AMEBA_BT_ANT_SW2     152
#define AMEBA_BT_ANT_SW3     153
#define AMEBA_EXT_CLK50M_IN  154
#define AMEBA_EXT_CLK_OUT    155
#define AMEBA_UART_LOG_RXD   156
#define AMEBA_UART_LOG_TXD   157
#define AMEBA_SIC_CLK        158
#define AMEBA_SIC_DAT        159
#define AMEBA_BT_FWLOG       160
#define AMEBA_BT_I2C_SDA     161
#define AMEBA_BT_I2C_SCL     162

/* Define pins number: bit[14:13] port, bit[12:8] pin, bit[7:0] function ID */
#define AMEBA_PORT_PIN(port, line)       ((((port) - 'A') << 5) + (line))
#define AMEBA_PINMUX(port, line, funcid) (((AMEBA_PORT_PIN(port, line)) << 8) | (funcid))

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_AMEBAG2_PINCTRL_H_ */
