obj-y =
obj-$(CONFIG_CPLUSPLUS) += cpp_virtual.o cpp_vtable.o               \
                           cpp_init_array.o cpp_ctors.o cpp_dtors.o
obj-$(CONFIG_PRINTK) += printk.o
obj-$(CONFIG_REBOOT) += reboot.o
obj-$(CONFIG_RING_BUFFER) += ring_buffer.o
obj-y += generated/
obj-y += debug/
