soc-cflags = $(call cc-option,-mcpu=quarkse_em) \
             $(call cc-option,-mno-sdata)

soc-aflags = $(soc-cflags)
soc-cxxflags = $(soc-cflags)
soc-cflags += -DQM_SENSOR=1

## FIXME
SOC_SERIES = quark_se
