EMU_PLATFORM ?= qemu

QEMU_CPU_TYPE_xtensa = sample_controller
QEMU_FLAGS_xtensa = -cpu $(QEMU_CPU_TYPE_xtensa) \
                    -machine sim -semihosting -nographic
QEMU_xtensa = qemu-system-xtensa

DEBUG_SCRIPT = qemu.sh

debugserver: QEMU_EXTRA_FLAGS += -s -S
debugserver: run

export QEMU_FLAGS_xtensa QEMU_xtensa
