# SPDX-FileCopyrightText: Copyright (c) 2026 Infineon Technologies AG,
# SPDX-FileCopyrightText: or an affiliate of Infineon Technologies AG. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

# The CSG slice DAC only supports direct-write mode.
CONFIG_DAC_BUFFER_NOT_SUPPORT=y
