obj-$(CONFIG_BLUETOOTH_CONTROLLER) += hci/

obj-$(CONFIG_BLUETOOTH_LL_SW) += util/
obj-$(CONFIG_BLUETOOTH_LL_SW) += hal/
obj-$(CONFIG_BLUETOOTH_LL_SW) += ticker/
obj-$(CONFIG_BLUETOOTH_LL_SW) += ll_sw/
