.. SPDX-License-Identifier: Apache-2.0
..
.. Copyright (c) 2026 Ezurio LLC

.. _Lyra 24 product brief:
   https://www.ezurio.com/documentation/product-brief-lyra-24-series

.. _Lyra 24 website:
   https://www.ezurio.com/wireless-modules/bluetooth-modules/bluetooth-5-modules/lyra-24-series-bluetooth-5-modules

.. _EFR32BG24 datasheet:
   https://www.silabs.com/documents/public/data-sheets/efr32bg24-datasheet.pdf

.. _EFR32BG24 reference manual:
   https://www.silabs.com/documents/public/reference-manuals/efr32xg24-rm.pdf

.. _mikroBUS:
   https://www.mikroe.com/mikrobus

.. _Qwiic:
   https://www.sparkfun.com/qwiic

.. _Simplicity Studio:
   https://www.silabs.com/software-and-tools/simplicity-studio
