ccflags-y +=-I$(srctree)/drivers

obj-$(CONFIG_GPIO_DW) += gpio_dw.o
obj-$(CONFIG_GPIO_PCAL9535A) += gpio_pcal9535a.o
obj-$(CONFIG_GPIO_SCH) += gpio_sch.o
obj-$(CONFIG_GPIO_QMSI) += gpio_qmsi.o
obj-$(CONFIG_GPIO_QMSI_SS) += gpio_qmsi_ss.o
obj-$(CONFIG_GPIO_ATMEL_SAM3) += gpio_atmel_sam3.o
obj-$(CONFIG_GPIO_MCUX) += gpio_mcux.o
obj-$(CONFIG_GPIO_MMIO32) += gpio_mmio32.o
obj-$(CONFIG_GPIO_STM32) += gpio_stm32.o
obj-$(CONFIG_GPIO_NRF5) += gpio_nrf5.o
obj-$(CONFIG_GPIO_CMSDK_AHB) += gpio_cmsdk_ahb.o
obj-$(CONFIG_GPIO_CC32XX) += gpio_cc32xx.o
obj-$(CONFIG_GPIO_PULPINO) += gpio_pulpino.o
obj-$(CONFIG_GPIO_FE310) += gpio_fe310.o
obj-$(CONFIG_GPIO_CC2650) += gpio_cc2650.o
