# Makefile - Hexiwear K64 board
#
# Copyright (c) 2016, Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

ccflags-y +=-I$(srctree)/drivers

obj-$(CONFIG_PINMUX_MCUX) += pinmux.o
