OPENSDA_FW ?= daplink

ifeq ($(OPENSDA_FW),jlink)
DEBUG_SCRIPT ?= jlink.sh
endif

ifeq ($(OPENSDA_FW),daplink)
DEBUG_SCRIPT ?= pyocd.sh
FLASH_SCRIPT ?= pyocd.sh
endif

JLINK_DEVICE = MK64FN1M0xxx12

PYOCD_TARGET = k64f

export JLINK_DEVICE PYOCD_TARGET
