/*
 * Copyright (c) 2020 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#define BT_MESH_DFD_OP_RECEIVERS_ADD_RAW         BT_MESH_MODEL_OP_SIG(0x83, 0x11)
#define BT_MESH_DFD_OP_RECEIVERS_ADD             \
	BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_RECEIVERS_ADD_RAW)
#define BT_MESH_DFD_OP_RECEIVERS_DELETE_ALL_RAW  BT_MESH_MODEL_OP_SIG(0x83, 0x12)
#define BT_MESH_DFD_OP_RECEIVERS_DELETE_ALL      \
	BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_RECEIVERS_DELETE_ALL_RAW)
#define BT_MESH_DFD_OP_RECEIVERS_STATUS_RAW      BT_MESH_MODEL_OP_SIG(0x83, 0x13)
#define BT_MESH_DFD_OP_RECEIVERS_STATUS          \
	BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_RECEIVERS_STATUS_RAW)
#define BT_MESH_DFD_OP_RECEIVERS_GET_RAW         BT_MESH_MODEL_OP_SIG(0x83, 0x14)
#define BT_MESH_DFD_OP_RECEIVERS_GET             \
	BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_RECEIVERS_GET_RAW)
#define BT_MESH_DFD_OP_RECEIVERS_LIST_RAW        BT_MESH_MODEL_OP_SIG(0x83, 0x15)
#define BT_MESH_DFD_OP_RECEIVERS_LIST            \
	BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_RECEIVERS_LIST_RAW)
#define BT_MESH_DFD_OP_CAPABILITIES_GET_RAW      BT_MESH_MODEL_OP_SIG(0x83, 0x16)
#define BT_MESH_DFD_OP_CAPABILITIES_GET          \
	BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_CAPABILITIES_GET_RAW)
#define BT_MESH_DFD_OP_CAPABILITIES_STATUS_RAW   BT_MESH_MODEL_OP_SIG(0x83, 0x17)
#define BT_MESH_DFD_OP_CAPABILITIES_STATUS       \
	BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_CAPABILITIES_STATUS_RAW)
#define BT_MESH_DFD_OP_GET_RAW                   BT_MESH_MODEL_OP_SIG(0x83, 0x18)
#define BT_MESH_DFD_OP_GET                       BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_GET_RAW)
#define BT_MESH_DFD_OP_START_RAW                 BT_MESH_MODEL_OP_SIG(0x83, 0x19)
#define BT_MESH_DFD_OP_START                     BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_START_RAW)
#define BT_MESH_DFD_OP_SUSPEND_RAW               BT_MESH_MODEL_OP_SIG(0x83, 0x1a)
#define BT_MESH_DFD_OP_SUSPEND                   BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_SUSPEND_RAW)
#define BT_MESH_DFD_OP_CANCEL_RAW                BT_MESH_MODEL_OP_SIG(0x83, 0x1b)
#define BT_MESH_DFD_OP_CANCEL                    BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_CANCEL_RAW)
#define BT_MESH_DFD_OP_APPLY_RAW                 BT_MESH_MODEL_OP_SIG(0x83, 0x1c)
#define BT_MESH_DFD_OP_APPLY                     BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_APPLY_RAW)
#define BT_MESH_DFD_OP_STATUS_RAW                BT_MESH_MODEL_OP_SIG(0x83, 0x1d)
#define BT_MESH_DFD_OP_STATUS                    BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_STATUS_RAW)
#define BT_MESH_DFD_OP_UPLOAD_GET_RAW            BT_MESH_MODEL_OP_SIG(0x83, 0x1e)
#define BT_MESH_DFD_OP_UPLOAD_GET                \
	BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_UPLOAD_GET_RAW)
#define BT_MESH_DFD_OP_UPLOAD_START_RAW          BT_MESH_MODEL_OP_SIG(0x83, 0x1f)
#define BT_MESH_DFD_OP_UPLOAD_START              \
	BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_UPLOAD_START_RAW)
#define BT_MESH_DFD_OP_UPLOAD_START_OOB_RAW      BT_MESH_MODEL_OP_SIG(0x83, 0x20)
#define BT_MESH_DFD_OP_UPLOAD_START_OOB          \
	BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_UPLOAD_START_OOB_RAW)
#define BT_MESH_DFD_OP_UPLOAD_CANCEL_RAW         BT_MESH_MODEL_OP_SIG(0x83, 0x21)
#define BT_MESH_DFD_OP_UPLOAD_CANCEL             \
	BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_UPLOAD_CANCEL_RAW)
#define BT_MESH_DFD_OP_UPLOAD_STATUS_RAW         BT_MESH_MODEL_OP_SIG(0x83, 0x22)
#define BT_MESH_DFD_OP_UPLOAD_STATUS             \
	BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_UPLOAD_STATUS_RAW)
#define BT_MESH_DFD_OP_FW_GET_RAW                BT_MESH_MODEL_OP_SIG(0x83, 0x23)
#define BT_MESH_DFD_OP_FW_GET                    BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_FW_GET_RAW)
#define BT_MESH_DFD_OP_FW_GET_BY_INDEX_RAW       BT_MESH_MODEL_OP_SIG(0x83, 0x24)
#define BT_MESH_DFD_OP_FW_GET_BY_INDEX           \
	BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_FW_GET_BY_INDEX_RAW)
#define BT_MESH_DFD_OP_FW_DELETE_RAW             BT_MESH_MODEL_OP_SIG(0x83, 0x25)
#define BT_MESH_DFD_OP_FW_DELETE                 BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_FW_DELETE_RAW)
#define BT_MESH_DFD_OP_FW_DELETE_ALL_RAW         BT_MESH_MODEL_OP_SIG(0x83, 0x26)
#define BT_MESH_DFD_OP_FW_DELETE_ALL             \
	BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_FW_DELETE_ALL_RAW)
#define BT_MESH_DFD_OP_FW_STATUS_RAW             BT_MESH_MODEL_OP_SIG(0x83, 0x27)
#define BT_MESH_DFD_OP_FW_STATUS                 \
	BT_MESH_MODEL_OPCODE(BT_MESH_DFD_OP_FW_STATUS_RAW)
