ccflags-y +=-I$(srctree)/arch/nios2/include/
ccflags-y +=-I$(srctree)/include
ccflags-y +=-I$(srctree)/include/drivers
ccflags-y +=-I$(srctree)/drivers

asflags-y := ${ccflags-y}

# Force kbuild to make empty built-in.o if necessary
obj- := dummy.o
