# Makefile - IRC client sample

#
# Copyright (c) 2017 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

BOARD ?= qemu_x86
CONF_FILE ?= prj.conf

include $(ZEPHYR_BASE)/Makefile.inc

include $(ZEPHYR_BASE)/samples/net/common/Makefile.ipstack
