/*
 * Copyright (c) 2026 Dimitri Varpusvuori
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_ARCH_M68K_INCLUDE_VECTOR_H_
#define ZEPHYR_ARCH_M68K_INCLUDE_VECTOR_H_

#define M68K_VECTOR_RESET_SP          0
#define M68K_VECTOR_RESET_PC          1
#define M68K_VECTOR_BUS_ERROR         2
#define M68K_VECTOR_ADDRESS_ERROR     3
#define M68K_VECTOR_ILLEGAL_INSTR     4
#define M68K_VECTOR_ZERO_DIVIDE       5
#define M68K_VECTOR_CHK               6
#define M68K_VECTOR_TRAPV             7
#define M68K_VECTOR_PRIVILEGE         8
#define M68K_VECTOR_TRACE             9
#define M68K_VECTOR_LINE_A            10
#define M68K_VECTOR_LINE_F            11
#define M68K_VECTOR_RESERVED_12       12
#define M68K_VECTOR_RESERVED_13       13
#define M68K_VECTOR_FORMAT_ERROR      14
#define M68K_VECTOR_UNINITIALIZED_INTERRUPT 15
#define M68K_VECTOR_RESERVED_LOW_FIRST 16
#define M68K_VECTOR_RESERVED_LOW_COUNT 8

#define M68K_VECTOR_SPURIOUS          24
#define M68K_VECTOR_AUTOVEC_BASE      25
#define M68K_VECTOR_AUTOVEC_LEVEL1    25
#define M68K_VECTOR_AUTOVEC_LEVEL2    26
#define M68K_VECTOR_AUTOVEC_LEVEL3    27
#define M68K_VECTOR_AUTOVEC_LEVEL4    28
#define M68K_VECTOR_AUTOVEC_LEVEL5    29
#define M68K_VECTOR_AUTOVEC_LEVEL6    30
#define M68K_VECTOR_AUTOVEC_LEVEL7    31

#define M68K_VECTOR_TRAP_BASE         32
#define M68K_VECTOR_TRAP_COUNT        16
#define M68K_VECTOR_USER_BASE         64

#define M68K_CPU_VECTOR_COUNT         256
#define M68K_NUM_VECTORS              M68K_CPU_VECTOR_COUNT

#define M68K_VECTOR_RESET_FIRST       M68K_VECTOR_RESET_SP
#define M68K_VECTOR_RESET_LAST        M68K_VECTOR_RESET_PC
#define M68K_VECTOR_EXCEPTION_FIRST   M68K_VECTOR_BUS_ERROR
#define M68K_VECTOR_EXCEPTION_LAST    M68K_VECTOR_LINE_F
#define M68K_VECTOR_AUTOVEC_FIRST     M68K_VECTOR_AUTOVEC_LEVEL1
#define M68K_VECTOR_AUTOVEC_LAST      M68K_VECTOR_AUTOVEC_LEVEL7
#define M68K_VECTOR_MASKABLE_AUTOVEC_LAST M68K_VECTOR_AUTOVEC_LEVEL6
#define M68K_VECTOR_NMI               M68K_VECTOR_AUTOVEC_LEVEL7
#define M68K_VECTOR_TRAP_LAST         (M68K_VECTOR_TRAP_BASE + M68K_VECTOR_TRAP_COUNT - 1)
#define M68K_VECTOR_RESERVED_HIGH_FIRST (M68K_VECTOR_TRAP_LAST + 1)
#define M68K_VECTOR_RESERVED_HIGH_LAST (M68K_VECTOR_USER_BASE - 1)
#define M68K_VECTOR_RESERVED_HIGH_COUNT 16
#define M68K_VECTOR_USER_LAST         (M68K_CPU_VECTOR_COUNT - 1)

#define M68K_VECTOR_SIZE              4
#define M68K_VECTOR_OFFSET(n)         ((n) * M68K_VECTOR_SIZE)
#define M68K_AUTOVEC_LEVEL(vector)    ((vector) - M68K_VECTOR_AUTOVEC_BASE + 1)
#define M68K_AUTOVEC_VECTOR(level)    (M68K_VECTOR_AUTOVEC_BASE + (level) - 1)

#define M68K_TRAP_RUNTIME_EXCEPT      14
#define M68K_VECTOR_RUNTIME_EXCEPT \
	(M68K_VECTOR_TRAP_BASE + M68K_TRAP_RUNTIME_EXCEPT)

#endif /* ZEPHYR_ARCH_M68K_INCLUDE_VECTOR_H_ */
