KERNEL_TYPE = nano
KBUILD_DEFCONFIG ?= $(KERNEL_TYPE)_generic_pc_atom_n28xx_defconfig
CONF_FILE = prj_$(ARCH).conf
SOURCE_DIR = $(ZEPHYR_BASE)/samples/microkernel/test/test_fp_sharing/src/

include $(ZEPHYR_BASE)/Makefile.inc
