# ESP32-S3-BOX-3 specific config for lvgl sample
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_REGULATOR=y

CONFIG_LV_Z_MEM_POOL_SIZE=65536
CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_COLOR_16_SWAP=y

CONFIG_HEAP_MEM_POOL_SIZE=131072
CONFIG_MAIN_STACK_SIZE=8192
