# Makefile - RPL node test application

#
# Copyright (c) 2017 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

BOARD ?= quark_se_c1000_devboard
CONF_FILE ?= prj.conf

include $(ZEPHYR_BASE)/Makefile.inc
include $(ZEPHYR_BASE)/samples/net/common/Makefile.ipstack

# QEMU_EXTRA_FLAGS = -serial unix:/tmp/bt-server-bredr
