obj-$(CONFIG_HPET_TIMER) += hpet.o
obj-$(CONFIG_LOAPIC_TIMER) += loapic_timer.o
obj-$(CONFIG_ARCV2_TIMER) += arcv2_timer0.o
obj-$(CONFIG_ALTERA_AVALON_TIMER) += altera_avalon_timer.o
obj-$(CONFIG_NRF_RTC_TIMER) += nrf_rtc_timer.o
obj-$(CONFIG_PULPINO_TIMER) += pulpino_timer.o
obj-$(CONFIG_RISCV_MACHINE_TIMER) += riscv_machine_timer.o
obj-$(CONFIG_RISCV_QEMU_TIMER) += riscv_qemu_timer.o
obj-$(CONFIG_XTENSA_TIMER) += xtensa_sys_timer.o

obj-$(CONFIG_CORTEX_M_SYSTICK) += cortex_m_systick.o

obj-y += sys_clock_init.o
