subdir-ccflags-y +=-I$(srctree)/lib/iot/zoap
ccflags-y += -I${srctree}/net/ip/contiki
ccflags-y += -I${srctree}/net/ip/contiki/os/lib
ccflags-y += -I${srctree}/net/ip/contiki/os
ccflags-y += -I${srctree}/net/ip

obj-y := zoap.o
