ccflags-y +=-I$(srctree)/arch/nios2/include/
ccflags-y +=-I$(srctree)/include
ccflags-y +=-I$(srctree)/include/drivers
ccflags-y +=-I$(srctree)/drivers

asflags-y := ${ccflags-y}

# Trick the build system into generating built-in.o even though there
# are no C files (yet) to compile
obj- = dummy.o
