ccflags-y +=-I$(srctree)/arch/nios2/include/
ccflags-y +=-I$(srctree)/include
ccflags-y +=-I$(srctree)/include/drivers
ccflags-y +=-I$(srctree)/drivers

asflags-y := ${ccflags-y}

# Force build system to create built-in.o even though we don't (yet)
# have any C files to compile
obj- = dummy.o
