# SPDX-FileCopyrightText: Copyright 2026 NXP
# SPDX-License-Identifier: Apache-2.0

CONFIG_EBPF=y
CONFIG_EBPF_TRACING=y
CONFIG_EBPF_SHELL=y
CONFIG_EBPF_STACK_SIZE=128
CONFIG_EBPF_STATS=y
CONFIG_EBPF_RUNTIME_BOUNDS_CHECK=y
CONFIG_EBPF_MAP_RINGBUF=y
CONFIG_TRACING=y
CONFIG_TRACING_CUSTOM=y
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_IDLE_STACK_SIZE=1024
