/*
 * Copyright (c) 2019 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#define LOG_MULDOMAIN_DOMAIN_NAME_GET 0
#define LOG_MULDOMAIN_SOURCE_COUNT_GET 1
#define LOG_MULDOMAIN_SOURCE_NAME_GET 2
#define LOG_MULDOMAIN_COMPILED_LEVEL_GET 3
#define LOG_MULDOMAIN_RUNTIME_LEVEL_GET 4
#define LOG_MULDOMAIN_RUNTIME_LEVEL_SET 5
#define LOG_MULDOMAIN_TIMESTAMP_GET 6
#define LOG_MULDOMAIN_MSG_HEAD 0xff
#define LOG_MULDOMAIN_MSG_CONT 0xfe
