/*
 * Copyright (c) 2015 Intel Corporation.
 * Copyright (c) 2024 Tenstorrent AI ULC
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_MISC_LOREM_IPSUM_H_
#define ZEPHYR_MISC_LOREM_IPSUM_H_

#include <zephyr/toolchain.h>

/** @cond INTERNAL_HIDDEN */

/*
 * N.B. These strings are generally only used for tests and samples. They are not part of any
 * official Zephyr API, but were moved to reduce duplication.
 */

/* Generated by http://www.lipsum.com/
 * 1 paragraph, 69 words, 445 bytes of Lorem Ipsum
 */
#define LOREM_IPSUM_SHORT                                                                          \
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, "                                \
	"sed do eiusmod tempor incididunt ut labore et dolore magna "                              \
	"aliqua. Ut enim ad minim veniam, quis nostrud exercitation "                              \
	"ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis "                           \
	"aute irure dolor in reprehenderit in voluptate velit esse "                               \
	"cillum dolore eu fugiat nulla pariatur. Excepteur sint "                                  \
	"occaecat cupidatat non proident, sunt in culpa qui officia "                              \
	"deserunt mollit anim id est laborum."

#define LOREM_IPSUM_SHORT_STRLEN 445
BUILD_ASSERT(sizeof(LOREM_IPSUM_SHORT) == LOREM_IPSUM_SHORT_STRLEN + 1);

/* Generated by http://www.lipsum.com/
 * 2 paragraphs, 173 words, 1160 bytes of Lorem Ipsum
 */
#define LOREM_IPSUM                                                                                \
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus a varius sapien. "       \
	"Suspendisse interdum nulla et enim elementum faucibus. Vestibulum nec est libero. Duis "  \
	"leo orci, tincidunt a interdum ut, porttitor ac arcu. Etiam porttitor pretium nibh, non " \
	"laoreet nisl vulputate vitae. Vestibulum sit amet odio sit amet nibh faucibus mattis "    \
	"eget at ex. Nam non arcu vitae nisi congue eleifend. Suspendisse sagittis, leo at "       \
	"blandit semper, arcu neque tristique dolor, eu consequat urna quam non tortor. "          \
	"Suspendisse ut ullamcorper lectus. Nullam ut accumsan lacus, sed iaculis leo. "           \
	"Suspendisse potenti. Duis ullamcorper velit tellus, ac dictum tellus ultricies quis."     \
	"\n"                                                                                       \
	"Curabitur tellus eros, congue a sem et, mattis fermentum velit. Donec sollicitudin "      \
	"faucibus enim eu vehicula. Aliquam pulvinar lectus et finibus laoreet. Praesent at "      \
	"tempor ex. Aenean blandit nunc viverra enim vulputate, et dictum turpis elementum. "      \
	"Donec porttitor in dolor a ultricies. Cras neque ipsum, blandit sed varius at, semper "   \
	"quis justo. Meanness ac metus ex. Pellentesque eu tortor eget nisl tempor pretium. "      \
	"Donec elit enim, ultrices sit amet est vitae, sollicitudin bibendum egestas."

#define LOREM_IPSUM_STRLEN 1160
BUILD_ASSERT(sizeof(LOREM_IPSUM) == LOREM_IPSUM_STRLEN + 1);

/* Generated by http://www.lipsum.com/
 * 14 paragraphs, 1215 words, 8192 bytes of Lorem Ipsum
 */
#define LOREM_IPSUM_LONG \
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque viverra " \
	"suscipit turpis sit amet vehicula. Duis dapibus non sem at semper. Sed ut pulvinar" \
	"mi. Vivamus odio sapien, lacinia id sagittis et, ultrices vel quam. Donec " \
	"convallis ligula dui, et tempus leo varius vel. Cras tincidunt eros non magna " \
	"accumsan, id viverra diam convallis. Nulla facilisi. Phasellus posuere nunc ac sem " \
	"dictum, ac vehicula metus pretium. Etiam et nunc sed sapien commodo " \
	"dignissim. Nunc placerat a augue imperdiet vehicula. In pellentesque sed est quis " \
	"imperdiet. Aliquam sit amet laoreet leo. Maecenas mi tortor, hendrerit et" \
	"sollicitudin non, egestas et nunc. Etiam blandit nunc turpis, sit amet sodales " \
	"nisl aliquet non. Curabitur quis luctus nulla, luctus eleifend erat. Etiam nec " \
	"magna eleifend, auctor ligula dignissim, dapius sapien.\n Maecenas neque " \
	"lacus, venenatis at mauris eget, condimentum accumsan arcu. Nullam consectetur " \
	"sapien vitae interdum. Nam rhoncus felis eu libero pharetra, vitae feugiat lorem " \
	"volutpat. Praesent malesuada metus a nisi semper, quis hendrerit lorem " \
	"volutpat. Nullam in mi sem. Donec auctor vehicula arcu vel dignissim. Sed porta ac " \
	"eros eget vulputate. Ut quis viverra ante. Proin get nisl scelerisque, varius " \
	"magna id, suscipit libero.\n Aliquam erat volutpat. Pellentesque sed vulputate " \
	"nulla. In ac facilisis velit. Curabitur laoreet leo id interdum rhoncus. Nam augue " \
	"eros, gravida eget eleifend id, blandit nec ex. Maecenas accumsan neque ac neque " \
	"pharetra, mattis condimentum augue placerat. Nunc fringilla felis pretium egestas " \
	"gravida. Duis tellus odio, tristique ac massa ac, scelerisque vulputate nisi. Duis " \
	"sit amet urna iaculis, venenatis lorem in, blandit velit. Morbi venenatis justo " \
	"orci, in maximus nisl rhoncus vel. Donec placerat euismod convalis.\n Nam ac risus " \
	"vel lectus cursus blandit. Aliquam tempus eros nec tellus accumsan bibendum. In " \
	"hac habitasse platea dictumst. Nam elementum a quam id dignissim. Nunc imperdiet " \
	"augue vel est maximus vestibulum. Integer vitae risus sed tortor bibendum cursus a " \
	"eu velit. Fusce est orci, sollicitudin ut risus pretium, consequat commodo " \
	"odio. Suspendisse potenti. Fusce at venenati turpis, eget gravida nulla. Sed " \
	"vestibulum placerat nulla a pellentesque. Proin laoreet sollicitudin leo. Nulla " \
	"quis dolor ligula. Orci varius natoque penatibus et magnis dis parturient montes, " \
	"nascetur ridiculus mus. Quisque hendrerit scelerisque turpis, ac laoreet arcu " \
	"feugiat id.\n Aliquam sed placerat erat. Cras quis neque sed metus pretium " \
	"convallis ut et nulla. Fusce diam ligula, efficitur tincidunt sagittis nec, " \
	"rhoncus at enim. Nullam sit amet maximus est. Quisque semper orci tellus, et " \
	"euismod eros faucibus et. Etiam nec quam id libero porta aliquam sit amet eu " \
	"justo. Vivamus congue convallis diam, vitae facilisis leo varius vel. Vivamus " \
	"ultrices purus et ante iaculis, vitae vehicula neque pulvinar. Cras interdum nisl " \
	"mi, eleifend rhoncus justo blandit vitae. Nulla sagittis ex in vestibulum " \
	"gravida. Fusce ac qua vel nunc pulvinar dictum nec eu magna. Maecenas massa elit, " \
	"vestibulum et semper at, ullamcorper in lacus. Pellentesque tincidunt facilisis " \
	"feugiat.\n Vivamus lobortis sapien et turpis rhoncus, eu pretium elit " \
	"pharetra. Nunc elementum varius congue. Suspendisse ac odio vitae nisi " \
	"pellentesque blandit sed vitae eros. Etiam convallis sem non arcu pretium, " \
	"tristique vehicula nunc pellentesque. Maecenas nibh dui, imperdiet sed bibendum " \
	"eget, fringilla id enim. In dignissim viverra rhoncus. Mauris id maximus " \
	"ligula. Vivamus lectus lorem, porta molestie malesuada nec, efficitur ut " \
	"ipsum. Fusce neque massa, finibus sed massa sed, cursus dapibus magna. Quisque " \
	"sodales ac tortor ac comodo. Nam ac sodales justo. Pellentesque convallis, felis " \
	"vitae ullamcorper sodales, quam odio malesuada augue, eu faucibus magna est non " \
	"enim. Sed feugiat nunc ut turpis placerat, eget iaculis orci lobortis. Nulla eget " \
	"nulla id quam blandit tristique. Aliquam consectetur at lacus sit amet bibendum.\n" \
	"In sollicitudin eros nec dui aliquam ullamcorper. Nullam vestibulum fringilla " \
	"malesuada. Ut ultrices a nisi sit amet eleifend. Donec mattis molestie lorem eu " \
	"finibus. Aenean mattis ultrices gravida. Phasellus porta laoreet vivera. Ut " \
	"malesuada, enim porta bibendum commodo, magna nunc vehicula metus, quis " \
	"sollicitudin massa nunc et ipsum. Duis at purus id eros cursus ultrices.\n Sed " \
	"convallis dapibus maximus. Aliquam imperdiet diam sed dignissim " \
	"congue. Pellentesque varius mattis augue, vestibulum hendrerit ante dapibus " \
	"et. Quisque non eros odio. Vestibulum ravida dolor vitae iaculis " \
	"venenatis. Quisque eu dui a velit suscipit vehicula sed at dui. Vestibulum est " \
	"magna, tempor quis quam ac, accumsan dictum ex. Aliquam condimentum vulputate " \
	"metus, id fermentum dui semper eu. Ut nec vestibulum velit. Curabitur eget " \
	"volutpat eros, ac malesuada nisl. Ut sed ullamcorper lectus, nec pharetra metus.\n" \
	"Maecenas ultrices odio augue, ut finibus ante euismod id. Maecenas porttitor " \
	"tellus sit amet lacinia feugiat. Nulla facilisi. Nulla tempus finibus mi " \
	"efficitur. Quisque at iaculis mauris. Nam at volutpat tellus. Praesent quis risus " \
	"ac risus faucibus interdum in a nibh.\n Quisque finibus nisi quis tincidunt " \
	"tristique. Etiam posuere, quam et volutpat tincidunt, ipsum ante scelerisque ante, " \
	"sit amet ultrices neque arcu sed nisi. Vestibulum ultricies sed ligula quis " \
	"volutpat. Phasellus ac vestibulum velit. Morbi dignissim felis ante, eget ultrices " \
	"ipsum elementum eu. Sed dapibus velit justo, fermentum pulvinar sem gravida " \
	"at. Nam imperdiet at massa vitae eleifend. In hac habitase platea " \
	"dictumst. Quisque egestas bibendum nisl ac fermentum. Ut eget turpis nec velit " \
	"efficitur posuere non ut nunc. Ut ultricies dapibus posuere.\n Quisque augue elit, " \
	"lobortis a fringilla non, malesuada elementum nisi. Interdum et malesuada fames ac " \
	"ante ipsum primis in faucibus. Suspendisse vehicula justo nibh, eget varius diam " \
	"iaculis ac. Curabitur nisl ligula, sodales in placerat non, porta non eros. Morbi " \
	"non magna turpis. Sed efficitur consequat nisi, eu tempus lacus. Donec nisi nisl, " \
	"lobortis ut tortor non, pretium interdum sapien. Vestibulum maximus iaculis dui a " \
	"porttitor. Sed euismod mollis eros, eget gravida lorem pretium vel. Nulla suscipit " \
	"nec sem quis rutrum. Curabitur tristique enim in mi pulvinar varius. Pellentesque " \
	"habitant morbi tristique senectus et netus et malesuada fames ac turpis " \
	"egestas. Aliquam bibendum leo purus, nec lobortis eros sodales id. Aliquam vitae " \
	"tellus iaculis, pulvinar erat sed, rhoncus nisi. Aenean cursus accumsan " \
	"volutpat. Nunc tellus neque, ultricies eget scelerisque sit met, lobortis at " \
	"sapien.\n Maecenas ut leo ullamcorper, rhoncus sapien nec, tempus " \
	"tortor. Phasellus eget arcu ac massa sollicitudin ultricies. Nunc in iaculis " \
	"sapien. Nam venenatis dolor euismod arcu iaculis, non placerat enim bibendum. Sed " \
	"venenatis et arcu non finibus. Mauris eget metus auctor libero cursus " \
	"vehicula. Proin id sem erat. Donec iaculis mi at molestie sollicitudin. Etiam vel " \
	"dignissim erat. Etiam dictum lacus fermentum gravida vulputate. Morbi gravida, " \
	"ligula id placerat pellentesque, metus urna faucibus mauris, a sagittis tortor " \
	"metus sit amet enim. Morbi dignissim, justo commodo suscipit sagittis, sem massa " \
	"efficitur nulla, in porta ipsum massa nec ante. Aliquam nulla quam, mollis nec " \
	"nisl eget, pretium placerat massa. Donec facilisis sapien sit amet tincidunt " \
	"iaculis. Maecenas dictum placerat lacus id pretium. Morbi sagittis at libero ege " \
	"condimentum.\n Ut euismod condimentum porttitor. Nam ornare lacus a nibh fermentum " \
	"rutrum. Nullam pretium libero ut augue aliquam ultrices. Donec sed dignissim " \
	"dui. Sed sit amet fringilla est. Morbi vitae mauris massa. Morbi feugiat suscipit " \
	"bibendum. Nunc mollis, lectus id rutrum tristique, metus metus iaculis enim, vel " \
	"scelerisque ligula odio et tortor. Nam lacus diam, condimentum in lectus vel, " \
	"congue euismod ligula. Maecenas laoreet orci orci, eget maximus erat tincidunt " \
	"in. Sed non finibus elit, in eleifend arcu. Proin posuere euismod vivera.\n Donec " \
	"a commodo du. Vestibulum faucibus quis ligula non volutpat. Nulla a elementum " \
	"nunc, quis malesuada nunc. Sed auctore in sapien at volutpat. In augue ipsum est.\n"

#define LOREM_IPSUM_LONG_STRLEN 8192
BUILD_ASSERT(sizeof(LOREM_IPSUM_LONG) == LOREM_IPSUM_LONG_STRLEN + 1);

/** @endcond */

#endif /* ZEPHYR_MISC_LOREM_IPSUM_H_ */
