#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: Apache-2.0
#

CONFIG_LOG=y
# CONFIG_LOG_MODE_MINIMAL=y
CONFIG_LOG_DBG_COLOR_BLUE=y

CONFIG_SERIAL=y
CONFIG_UART_ASYNC_API=y

CONFIG_UART_1_NRF_ASYNC_LOW_POWER=y
CONFIG_UART_2_NRF_ASYNC_LOW_POWER=y

CONFIG_ZBUS=y
CONFIG_ZBUS_CHANNEL_NAME=y
CONFIG_ZBUS_MSG_SUBSCRIBER=y

CONFIG_CRC=y

CONFIG_ZBUS_MULTIDOMAIN=y
CONFIG_ZBUS_MULTIDOMAIN_UART=y
CONFIG_ZBUS_MULTIDOMAIN_LOG_LEVEL_INF=y
