#
# Copyright (c) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ccflags-y += -I${ZEPHYR_BASE}/net/ip/contiki
ccflags-y += -I${ZEPHYR_BASE}/net/ip/contiki/os/lib
ccflags-y += -I${ZEPHYR_BASE}/net/ip/contiki/os
ccflags-y += -I${ZEPHYR_BASE}/net/ip

obj-y += nats_pack.o
obj-y += nats_client.o
obj-y += netz.o
obj-y += main.o
