CONFIG_WIFI_ESP32=y
CONFIG_ESP32_WIFI_STA_RECONNECT=y
CONFIG_WIFI_NM=y
CONFIG_WIFI_NM_MAX_MANAGED_INTERFACES=2

CONFIG_HEAP_MEM_POOL_SIZE=131072
CONFIG_IDLE_STACK_SIZE=1024
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SHELL_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

# apsta_mode configuration
CONFIG_WIFI_SAMPLE_AP_SSID="ESP32-AP"
CONFIG_WIFI_SAMPLE_AP_PSK=""
CONFIG_WIFI_SAMPLE_SSID="SSID"
CONFIG_WIFI_SAMPLE_PSK="PASSWORD"
CONFIG_WIFI_SAMPLE_DHCPV4_START=y
CONFIG_WIFI_SAMPLE_AP_IP_ADDRESS="192.168.4.1"
CONFIG_WIFI_SAMPLE_AP_NETMASK="255.255.255.0"
