ifeq ($(CONFIG_HAS_CC3220SDK),y)
ccflags-y += -D$(COMPILER)
# Need to build prcm, utils and pin, which are not in ROM
obj-$(CONFIG_HAS_CC3220SDK) += source/ti/devices/cc32xx/driverlib/utils.o
obj-$(CONFIG_HAS_CC3220SDK) += source/ti/devices/cc32xx/driverlib/prcm.o
obj-$(CONFIG_HAS_CC3220SDK) += source/ti/devices/cc32xx/driverlib/pin.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/SPI.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/spi/SPICC32XXDMA.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/dma/UDMACC32XX.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/power/PowerCC32XX.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/utils/List.o
CFLAGS_driver.o += -D__LINUX_ERRNO_EXTENSIONS__
# driver.c warns on strict-aliasing
CFLAGS_driver.o += -Wno-strict-aliasing
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/net/wifi/source/driver.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/net/wifi/source/device.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/net/wifi/source/flowcont.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/net/wifi/source/fs.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/net/wifi/source/netapp.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/net/wifi/source/netcfg.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/net/wifi/source/netutil.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/net/wifi/source/nonos.o
# sl_socket warns on missing braces:
CFLAGS_sl_socket.o += -Wno-missing-braces
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/net/wifi/source/sl_socket.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/net/wifi/source/spawn.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/net/wifi/source/wlan.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/net/wifi/porting/CC3220SF_LAUNCHXL.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/net/wifi/porting/cc_pal.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/net/wifi/eventreg.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/drivers/net/wifi/source/socket.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/devices/cc32xx/driverlib/timer.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += source/ti/devices/cc32xx/driverlib/udma.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += kernel/zephyr/dpl/dpl.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += kernel/zephyr/dpl/MutexP_zephyr.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += kernel/zephyr/dpl/SemaphoreP_zephyr.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += kernel/zephyr/dpl/ClockP_zephyr.o
obj-$(CONFIG_SIMPLELINK_HOST_DRIVER) += kernel/zephyr/dpl/HwiP_zephyr.o
endif

ifeq ($(CONFIG_HAS_MSP432P4XXSDK),y)
ccflags-y += -D$(COMPILER)
# Need system_msp432p401r for SystemInit which is not in ROM
obj-y += source/ti/devices/msp432p4xx/startup_system_files/system_msp432p401r.o
endif
