ifdef CONFIG_HAS_CC3220SDK
ZEPHYRINCLUDE +=-I$(srctree)/ext/hal/ti/simplelink/source/ti/devices/cc32xx
ZEPHYRINCLUDE +=-I$(srctree)/ext/hal/ti/simplelink/source/ti/devices/cc32xx/inc
ZEPHYRINCLUDE +=-I$(srctree)/ext/hal/ti/simplelink/source/ti/devices/cc32xx/driverlib
KBUILD_CFLAGS += -DUSE_CC3220_ROM_DRV_API
endif # CONFIG_HAS_CC3220SDK
