subdir-ccflags-$(CONFIG_BLUETOOTH_NRF51_PM) +=-I$(srctree)/drivers/bluetooth

obj-$(CONFIG_NBLE) += gap.o conn.o gatt.o uart.o rpc_serialize.o \
		      rpc_deserialize.o stubs.o \
		      ../../../net/bluetooth/uuid.o
