
EMU_PLATFORM = qemu

QEMU_CPU_TYPE_riscv32 = riscv32
QEMU_FLAGS_riscv32 = -machine sifive -nographic -m $(CONFIG_RISCV_RAM_SIZE_MB)
QEMU_riscv32 = qemu-system-riscv32

DEBUG_SCRIPT = qemu.sh

debugserver: QEMU_EXTRA_FLAGS += -s -S
debugserver: qemu
