# Makefile - ieee802154 example that is used in testing

#
# Copyright (c) 2016 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

BOARD ?= quark_se_c1000_devboard
CONF_FILE ?= prj.conf

include $(ZEPHYR_BASE)/Makefile.inc
