/*
 * Copyright (c) 2025 EXALT Technologies.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/types.h>
#include <stm32_ll_dma.h>

#if defined(CONFIG_STM32_HAL2)

/* STM32Cube2 GPDMA LL constants live under different names */
#define MSPI_DMA_PRIORITY_LOW_WEIGHT    LL_DMA_PRIORITY_LOW_WEIGHT_LOW
#define MSPI_DMA_PRIORITY_MID_WEIGHT    LL_DMA_PRIORITY_LOW_WEIGHT_MID
#define MSPI_DMA_PRIORITY_HIGH_WEIGHT   LL_DMA_PRIORITY_LOW_WEIGHT_HIGH
#define MSPI_DMA_PRIORITY_HIGH          LL_DMA_PRIORITY_HIGH

#define MSPI_DMA_SRC_DATAWIDTH_BYTE     LL_DMA_SRC_DATA_WIDTH_BYTE
#define MSPI_DMA_SRC_DATAWIDTH_HALFWORD LL_DMA_SRC_DATA_WIDTH_HALFWORD
#define MSPI_DMA_SRC_DATAWIDTH_WORD     LL_DMA_SRC_DATA_WIDTH_WORD

#define MSPI_DMA_DEST_DATAWIDTH_BYTE     LL_DMA_DEST_DATA_WIDTH_BYTE
#define MSPI_DMA_DEST_DATAWIDTH_HALFWORD LL_DMA_DEST_DATA_WIDTH_HALFWORD
#define MSPI_DMA_DEST_DATAWIDTH_WORD     LL_DMA_DEST_DATA_WIDTH_WORD

#define MSPI_DMA_MEMORY_TO_MEMORY       LL_DMA_DIRECTION_MEMORY_TO_MEMORY
#define MSPI_DMA_MEMORY_TO_PERIPH       LL_DMA_DIRECTION_MEMORY_TO_PERIPH
#define MSPI_DMA_PERIPH_TO_MEMORY       LL_DMA_DIRECTION_PERIPH_TO_MEMORY

#else /* CONFIG_STM32_HAL2 */

#if defined(DMA_LOW_PRIORITY_LOW_WEIGHT)
#define MSPI_DMA_PRIORITY_LOW_WEIGHT    DMA_LOW_PRIORITY_LOW_WEIGHT
#else
#define MSPI_DMA_PRIORITY_LOW_WEIGHT    DMA_PRIORITY_LOW
#endif

#if defined(DMA_LOW_PRIORITY_MID_WEIGHT)
#define MSPI_DMA_PRIORITY_MID_WEIGHT    DMA_LOW_PRIORITY_MID_WEIGHT
#else
#define MSPI_DMA_PRIORITY_MID_WEIGHT    DMA_PRIORITY_MEDIUM
#endif

#if defined(DMA_LOW_PRIORITY_HIGH_WEIGHT)
#define MSPI_DMA_PRIORITY_HIGH_WEIGHT   DMA_LOW_PRIORITY_HIGH_WEIGHT
#else
#define MSPI_DMA_PRIORITY_HIGH_WEIGHT   DMA_PRIORITY_HIGH
#endif

#if defined(DMA_HIGH_PRIORITY)
#define MSPI_DMA_PRIORITY_HIGH          DMA_HIGH_PRIORITY
#else
#define MSPI_DMA_PRIORITY_HIGH          DMA_PRIORITY_VERY_HIGH
#endif

#if defined(LL_DMA_SRC_DATAWIDTH_BYTE)
#define MSPI_DMA_SRC_DATAWIDTH_BYTE LL_DMA_SRC_DATAWIDTH_BYTE
#else
#define MSPI_DMA_SRC_DATAWIDTH_BYTE LL_DMA_MDATAALIGN_BYTE
#endif

#if defined(LL_DMA_SRC_DATAWIDTH_HALFWORD)
#define MSPI_DMA_SRC_DATAWIDTH_HALFWORD LL_DMA_SRC_DATAWIDTH_HALFWORD
#else
#define MSPI_DMA_SRC_DATAWIDTH_HALFWORD LL_DMA_MDATAALIGN_HALFWORD
#endif

#if defined(LL_DMA_SRC_DATAWIDTH_WORD)
#define MSPI_DMA_SRC_DATAWIDTH_WORD LL_DMA_SRC_DATAWIDTH_WORD
#else
#define MSPI_DMA_SRC_DATAWIDTH_WORD LL_DMA_MDATAALIGN_WORD
#endif

#if defined(LL_DMA_DEST_DATAWIDTH_BYTE)
#define MSPI_DMA_DEST_DATAWIDTH_BYTE LL_DMA_DEST_DATAWIDTH_BYTE
#else
#define MSPI_DMA_DEST_DATAWIDTH_BYTE LL_DMA_PDATAALIGN_BYTE
#endif

#if defined(LL_DMA_DEST_DATAWIDTH_HALFWORD)
#define MSPI_DMA_DEST_DATAWIDTH_HALFWORD LL_DMA_DEST_DATAWIDTH_HALFWORD
#else
#define MSPI_DMA_DEST_DATAWIDTH_HALFWORD LL_DMA_PDATAALIGN_HALFWORD
#endif

#if defined(LL_DMA_DEST_DATAWIDTH_WORD)
#define MSPI_DMA_DEST_DATAWIDTH_WORD LL_DMA_DEST_DATAWIDTH_WORD
#else
#define MSPI_DMA_DEST_DATAWIDTH_WORD LL_DMA_PDATAALIGN_WORD
#endif

#define MSPI_DMA_MEMORY_TO_MEMORY       DMA_MEMORY_TO_MEMORY
#define MSPI_DMA_MEMORY_TO_PERIPH       DMA_MEMORY_TO_PERIPH
#define MSPI_DMA_PERIPH_TO_MEMORY       DMA_PERIPH_TO_MEMORY

#endif /* CONFIG_STM32_HAL2 */

/* Lookup table to set dma priority from the DTS */
const uint32_t mspi_stm32_table_priority[] = {
	MSPI_DMA_PRIORITY_LOW_WEIGHT,
	MSPI_DMA_PRIORITY_MID_WEIGHT,
	MSPI_DMA_PRIORITY_HIGH_WEIGHT,
	MSPI_DMA_PRIORITY_HIGH,
};

/* Lookup table to set dma channel direction from the DTS */
const uint32_t mspi_stm32_table_direction[] = {
	MSPI_DMA_MEMORY_TO_MEMORY,
	MSPI_DMA_MEMORY_TO_PERIPH,
	MSPI_DMA_PERIPH_TO_MEMORY,
};

const uint32_t mspi_stm32_table_src_size[] = {
	MSPI_DMA_SRC_DATAWIDTH_BYTE,
	MSPI_DMA_SRC_DATAWIDTH_HALFWORD,
	MSPI_DMA_SRC_DATAWIDTH_WORD
};

const uint32_t mspi_stm32_table_dest_size[] = {
	MSPI_DMA_DEST_DATAWIDTH_BYTE,
	MSPI_DMA_DEST_DATAWIDTH_HALFWORD,
	MSPI_DMA_DEST_DATAWIDTH_WORD
};
