/*
 * Copyright (c) 2025 EXALT Technologies.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/types.h>
#include <stm32_ll_dma.h>

#if defined(DMA_LOW_PRIORITY_LOW_WEIGHT)
#define MSPI_DMA_PRIORITY_LOW_WEIGHT    DMA_LOW_PRIORITY_LOW_WEIGHT
#else
#define MSPI_DMA_PRIORITY_LOW_WEIGHT    DMA_PRIORITY_LOW
#endif

#if defined(DMA_LOW_PRIORITY_MID_WEIGHT)
#define MSPI_DMA_PRIORITY_MID_WEIGHT    DMA_LOW_PRIORITY_MID_WEIGHT
#else
#define MSPI_DMA_PRIORITY_MID_WEIGHT    DMA_PRIORITY_MEDIUM
#endif

#if defined(DMA_LOW_PRIORITY_HIGH_WEIGHT)
#define MSPI_DMA_PRIORITY_HIGH_WEIGHT   DMA_LOW_PRIORITY_HIGH_WEIGHT
#else
#define MSPI_DMA_PRIORITY_HIGH_WEIGHT   DMA_PRIORITY_HIGH
#endif

#if defined(DMA_HIGH_PRIORITY)
#define MSPI_DMA_PRIORITY_HIGH          DMA_HIGH_PRIORITY
#else
#define MSPI_DMA_PRIORITY_HIGH          DMA_PRIORITY_VERY_HIGH
#endif

#if defined(LL_DMA_SRC_DATAWIDTH_BYTE)
#define MSPI_DMA_SRC_DATAWIDTH_BYTE LL_DMA_SRC_DATAWIDTH_BYTE
#else
#define MSPI_DMA_SRC_DATAWIDTH_BYTE LL_DMA_MDATAALIGN_BYTE
#endif

#if defined(LL_DMA_SRC_DATAWIDTH_HALFWORD)
#define MSPI_DMA_SRC_DATAWIDTH_HALFWORD LL_DMA_SRC_DATAWIDTH_HALFWORD
#else
#define MSPI_DMA_SRC_DATAWIDTH_HALFWORD LL_DMA_MDATAALIGN_HALFWORD
#endif

#if defined(LL_DMA_SRC_DATAWIDTH_WORD)
#define MSPI_DMA_SRC_DATAWIDTH_WORD LL_DMA_SRC_DATAWIDTH_WORD
#else
#define MSPI_DMA_SRC_DATAWIDTH_WORD LL_DMA_MDATAALIGN_WORD
#endif

#if defined(LL_DMA_DEST_DATAWIDTH_BYTE)
#define MSPI_DMA_DEST_DATAWIDTH_BYTE LL_DMA_DEST_DATAWIDTH_BYTE
#else
#define MSPI_DMA_DEST_DATAWIDTH_BYTE LL_DMA_PDATAALIGN_BYTE
#endif

#if defined(LL_DMA_DEST_DATAWIDTH_HALFWORD)
#define MSPI_DMA_DEST_DATAWIDTH_HALFWORD LL_DMA_DEST_DATAWIDTH_HALFWORD
#else
#define MSPI_DMA_DEST_DATAWIDTH_HALFWORD LL_DMA_PDATAALIGN_HALFWORD
#endif

#if defined(LL_DMA_DEST_DATAWIDTH_WORD)
#define MSPI_DMA_DEST_DATAWIDTH_WORD LL_DMA_DEST_DATAWIDTH_WORD
#else
#define MSPI_DMA_DEST_DATAWIDTH_WORD LL_DMA_PDATAALIGN_WORD
#endif

/* Lookup table to set dma priority from the DTS */
const uint32_t mspi_stm32_table_priority[] = {
	MSPI_DMA_PRIORITY_LOW_WEIGHT,
	MSPI_DMA_PRIORITY_MID_WEIGHT,
	MSPI_DMA_PRIORITY_HIGH_WEIGHT,
	MSPI_DMA_PRIORITY_HIGH,
};

/* Lookup table to set dma channel direction from the DTS */
const uint32_t mspi_stm32_table_direction[] = {
	DMA_MEMORY_TO_MEMORY,
	DMA_MEMORY_TO_PERIPH,
	DMA_PERIPH_TO_MEMORY,
};

const uint32_t mspi_stm32_table_src_size[] = {
	MSPI_DMA_SRC_DATAWIDTH_BYTE,
	MSPI_DMA_SRC_DATAWIDTH_HALFWORD,
	MSPI_DMA_SRC_DATAWIDTH_WORD
};

const uint32_t mspi_stm32_table_dest_size[] = {
	MSPI_DMA_DEST_DATAWIDTH_BYTE,
	MSPI_DMA_DEST_DATAWIDTH_HALFWORD,
	MSPI_DMA_DEST_DATAWIDTH_WORD
};
