/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_SAEJ2716_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_SAEJ2716_H_

#define FAST_CRC_DISABLE 0
#define FAST_CRC_LEGACY_IMPLEMENTATION 1
#define FAST_CRC_RECOMMENDED_IMPLEMENTATION 2
#define FAST_CRC_STATUS_INCLUDE 4

#define SHORT_CRC_LEGACY_IMPLEMENTATION 0
#define SHORT_CRC_RECOMMENDED_IMPLEMENTATION 1

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_SAEJ2716_H_ */
