ccflags-y +=-I$(srctree)/arch/arc/platforms/$(strip $(CONFIG_PLATFORM))
asflags-y +=-I$(srctree)/arch/arc/platforms/$(strip $(CONFIG_PLATFORM))

obj-y = core/

obj-$(CONFIG_PLATFORM_GENERIC_ARC) += platforms/generic_arc/
