ccflags-y +=-I$(srctree)/arch/arc/$(strip $(CONFIG_PLATFORM))
asflags-y +=-I$(srctree)/arch/arc/$(strip $(CONFIG_PLATFORM))

obj-y = core/

obj-y += prep_c.o \
         reset.o \
         vector_table.o
