obj-${CONFIG_PIC_DISABLE} = i8259.o

obj-$(CONFIG_MVIC) += mvic.o
obj-$(CONFIG_LOAPIC) += loapic_intr.o system_apic.o
obj-$(CONFIG_IOAPIC) += ioapic_intr.o
obj-$(CONFIG_LOAPIC_SPURIOUS_VECTOR) += loapic_spurious.o

obj-$(CONFIG_ARCV2_INTERRUPT_UNIT) += arcv2_irq_unit.o

obj-$(CONFIG_SOC_FAMILY_STM32) += exti_stm32.o
