obj-${CONFIG_SHUTOFF_PIC} = i8259.o

obj-$(CONFIG_LOAPIC) += system_apic.o
obj-$(CONFIG_LOAPIC) += loapic_intr.o
obj-$(CONFIG_IOAPIC) += ioapic_intr.o

obj-$(CONFIG_ARCV2_INTERRUPT_UNIT) += arcv2_irq_unit.o
