# Copyright (c) 2025-2026 Analog Devices, Inc.
#
# SPDX-License-Identifier: Apache-2.0

# GPIO for Blinking LED
CONFIG_GPIO=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_SOC_LOG_LEVEL_DBG=y

# Prevent debugger lockout
CONFIG_MAX32_STANDBY_DELAY=1000

# Power management configuration
CONFIG_COUNTER=y
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_PM_POLICY_DEVICE_CONSTRAINTS=y
