obj-$(CONFIG_ADC_DW) += adc_dw.o
obj-$(CONFIG_ADC_MCUX_ADC16) += adc_mcux_adc16.o
obj-$(CONFIG_ADC_TI_ADC108S102) += adc_ti_adc108s102.o
obj-$(CONFIG_ADC_QMSI) += adc_qmsi.o
obj-$(CONFIG_ADC_QMSI_SS) += adc_qmsi_ss.o
