ccflags-y += -I${srctree}/net/ip/contiki
ccflags-y += -I${srctree}/net/ip/contiki/os/lib
ccflags-y += -I${srctree}/net/ip/contiki/os
ccflags-y += -I${srctree}/net/ip

obj-y += zperf_shell.o
obj-y += shell_utils.o
obj-y += zperf_uploader.o
obj-y += zperf_receiver.o
