EXTRA_CFLAGS += ${PROJECTINCLUDE}
EXTRA_CFLAGS +=-I${srctree}/net/ip/contiki
EXTRA_CFLAGS +=-I${srctree}/net/ip/contiki/os/lib
EXTRA_CFLAGS +=-I${srctree}/net/ip/contiki/os/sys
EXTRA_CFLAGS +=-I${srctree}/net/ip/contiki/os
EXTRA_CFLAGS +=-I${srctree}/net/ip/tinydtls
EXTRA_CFLAGS +=-I${srctree}/net/ip/er-coap
EXTRA_CFLAGS +=-I${srctree}/net/ip/rest-engine

obj-y = coap-observe-client.o
