/*
 * Copyright (c) 2026 Jonathan Elliot Peace <jep@alphabetiq.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * brcmfmac firmware, NVRAM and (optional) CLM blob payloads. The actual
 * bytes are generated by CMake from the corresponding files in
 * hal_broadcom (fetched via `west blobs fetch hal_broadcom`) and
 * #include'd here. An unset CONFIG_WIFI_BRCMFMAC_CLM_FILE links an
 * empty CLM array and the driver skips the upload at runtime.
 */

const unsigned char brcmfmac_fw[] = {
#include "brcmfmac_fw.inc"
};
const unsigned int brcmfmac_fw_len = sizeof(brcmfmac_fw);

const unsigned char brcmfmac_nvram[] = {
#include "brcmfmac_nvram.inc"
};
const unsigned int brcmfmac_nvram_len = sizeof(brcmfmac_nvram);

const unsigned char brcmfmac_clm_blob[] = {
#include "brcmfmac_clm_blob.inc"
};
const unsigned int brcmfmac_clm_blob_len = sizeof(brcmfmac_clm_blob);
