EXTRA_CFLAGS += ${PROJECTINCLUDE}
EXTRA_CFLAGS +=-I${srctree}/net/ip/contiki
EXTRA_CFLAGS +=-I${srctree}/net/ip/contiki/os/lib
EXTRA_CFLAGS +=-I${srctree}/net/ip/contiki/os
EXTRA_CFLAGS +=-I${srctree}/net/ip/contiki/os/sys
EXTRA_CFLAGS +=-I${srctree}/net/ip

obj-y = dtls-server.o
