ZEPHYRINCLUDE +=-I${srctree}/ext/drivers/atmel/winc1500/
ZEPHYRINCLUDE +=-I${srctree}/drivers/wifi/winc1500/

obj-$(CONFIG_WIFI_WINC1500) += \
				driver/source/m2m_ate_mode.o \
				driver/source/m2m_crypto.o \
				driver/source/m2m_hif.o \
				driver/source/m2m_ota.o \
				driver/source/m2m_periph.o \
				driver/source/m2m_wifi.o \
				driver/source/nmasic.o \
				driver/source/nmbus.o \
				driver/source/nmdrv.o \
				driver/source/nmspi.o \
				socket/source/socket.o \
				common/source/nm_common.o \
				spi_flash/source/spi_flash.o