EXTRA_CFLAGS +=-I$(srctree)/include/drivers
EXTRA_CFLAGS +=-I$(srctree)/arch/x86/generic_pc
EXTRA_CFLAGS +=-I$(srctree)/arch/x86

obj-$(CONFIG_LOAPIC) += loApicIntr.o
obj-$(CONFIG_IOAPIC) += ioApicIntr.o
