CONFIG_NETWORKING=y
CONFIG_LOG=y
CONFIG_NET_LOG=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=y

CONFIG_NET_UDP=y
CONFIG_NET_SOCKETS=y

CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_NEED_IPV4=y
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.1"

CONFIG_DNS_RESOLVER=n
CONFIG_TFTP_LIB=y
CONFIG_TFTPS=y
CONFIG_POSIX_API=y

CONFIG_MAIN_STACK_SIZE=4096

# File system support (RAM disk + in-memory ext2)
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVERS=y
CONFIG_FILE_SYSTEM_EXT2=y
