set(BOARD_REVISIONS "minima" "wifi")
if(NOT DEFINED BOARD_REVISION)
  set(BOARD_REVISION "minima")
else()
  if(NOT BOARD_REVISION IN_LIST BOARD_REVISIONS)
    message(FATAL_ERROR "${BOARD_REVISION} is not a valid revision for arduino_uno_r4. Accepted revisions: ${BOARD_REVISIONS}")
  endif()
endif()
