OPENSDA_FW ?= daplink

ifeq ($(OPENSDA_FW),jlink)
DEBUG_SCRIPT ?= jlink.sh
endif

ifeq ($(OPENSDA_FW),daplink)
DEBUG_SCRIPT ?= pyocd.sh
FLASH_SCRIPT ?= pyocd.sh
endif

JLINK_DEVICE = MKL25Z128xxx4

PYOCD_TARGET = kl25z

export JLINK_DEVICE PYOCD_TARGET
