/*
 * Copyright (c) 2024 Mustafa Abdullah Kus, Sparse Technology
 *
 * SPDX-License-Identifier: Apache-2.0
 */

ITERABLE_SECTION_RAM(prometheus_counter, Z_LINK_ITERABLE_SUBALIGN)
ITERABLE_SECTION_RAM(prometheus_gauge, Z_LINK_ITERABLE_SUBALIGN)
ITERABLE_SECTION_RAM(prometheus_histogram, Z_LINK_ITERABLE_SUBALIGN)
ITERABLE_SECTION_RAM(prometheus_summary, Z_LINK_ITERABLE_SUBALIGN)
ITERABLE_SECTION_RAM(prometheus_collector, Z_LINK_ITERABLE_SUBALIGN)
