OPENSDA_FW ?= jlink

ifeq ($(OPENSDA_FW),jlink)
DEBUG_SCRIPT ?= jlink.sh
endif

ifeq ($(OPENSDA_FW),daplink)
DEBUG_SCRIPT ?= pyocd.sh
FLASH_SCRIPT ?= pyocd.sh
endif

JLINK_DEVICE = MKW41Z512xxx4

PYOCD_TARGET = kw41z4

export JLINK_DEVICE PYOCD_TARGET
