subdir-ccflags-y +=-I$(srctree)/include/drivers
subdir-ccflags-y +=-I$(srctree)/drivers
subdir-ccflags-y +=-I$(srctree)/arch/arm/platforms/$(subst $(DQUOTE),,$(CONFIG_PLATFORM))
subdir-asflags-y := ${subdir-ccflags-y}

obj-y += core/
obj-y += platforms/$(subst $(DQUOTE),,$(CONFIG_PLATFORM))/
