subdir-ccflags-y +=-I$(srctree)/include/drivers
subdir-ccflags-y +=-I$(srctree)/drivers
subdir-ccflags-y +=-I$(srctree)/arch/arm/platforms/$(PLATFORM_NAME)
subdir-asflags-y := ${subdir-ccflags-y}

obj-y += core/
obj-y += platforms/$(PLATFORM_NAME)/
