ccflags-y +=-I${srctree}/net/ip
ccflags-y +=-I${srctree}/net/ip/contiki
ccflags-y +=-I${srctree}/net/ip/contiki/os/lib
ccflags-y +=-I${srctree}/net/ip/contiki/os/sys
ccflags-y +=-I${srctree}/net/ip/contiki/os
ccflags-y +=-I${srctree}/net/ip/tinydtls
ccflags-y +=-I${srctree}/net/ip/er-coap
ccflags-y +=-I${srctree}/net/ip/rest-engine

obj-y = coap-observe-client.o
