/*
 * Copyright (c) 2025 Silicon Laboratories Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DRIVERS_DMA_SILABS_LDMA_H_
#define ZEPHYR_INCLUDE_DRIVERS_DMA_SILABS_LDMA_H_

#include <zephyr/drivers/dma.h>

#define SILABS_LDMA_SOURCE_MASK  GENMASK(21, 16)
#define SILABS_LDMA_SIG_MASK     GENMASK(3, 0)

#define SILABS_DMA_SLOT_SOURCE_MASK  GENMASK(7, 3)
#define SILABS_DMA_SLOT_SIG_MASK     GENMASK(2, 0)

#define SILABS_LDMA_REQSEL_TO_SLOT(signal)             \
	FIELD_PREP(SILABS_DMA_SLOT_SOURCE_MASK, FIELD_GET(SILABS_LDMA_SOURCE_MASK, signal)) | \
	FIELD_PREP(SILABS_DMA_SLOT_SIG_MASK, FIELD_GET(SILABS_LDMA_SIG_MASK, signal))

#define SILABS_LDMA_SLOT_TO_REQSEL(slot)     \
	FIELD_PREP(SILABS_LDMA_SOURCE_MASK, FIELD_GET(SILABS_DMA_SLOT_SOURCE_MASK, slot)) | \
	FIELD_PREP(SILABS_LDMA_SIG_MASK, FIELD_GET(SILABS_DMA_SLOT_SIG_MASK, slot))

#endif /* ZEPHYR_INCLUDE_DRIVERS_DMA_SILABS_LDMA_H_*/
