
arch-cflags += $(call cc-option,-mthumb -mcpu=cortex-m3) \
		$(call cc-option,-mthumb -march=armv7-m)

KBUILD_AFLAGS += $(arch-cflags)
KBUILD_CXXFLAGS += $(arch-cflags)
KBUILD_CFLAGS += $(arch-cflags)
