# Makefile - fxos8700 sample
#
# Copyright (c) 2016, Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

BOARD ?= frdm_k64f
CONF_FILE ?= prj.conf

include $(ZEPHYR_BASE)/Makefile.inc
