"""
Copyright (c) 2021 Zephyr Project members and individual contributors
SPDX-License-Identifier: Apache-2.0

This module contains a variable with a list of tuples (old_url, new_url) for
pages to redirect. This list allows redirecting old URLs (caused by reorganizing
doc directories)

Notes:
    - Please keep this list sorted alphabetically.
    - URLs must be relative to document root (with NO leading slash), and
      without the html extension).
"""

REDIRECTS = (
    # zephyr-keep-sorted-start
    ('boards/arm/fvp_baser_aemv8r/doc/aarch32', 'boards/arm/fvp_baser_aemv8r/doc/index'),
    ('boards/arm/fvp_baser_aemv8r/doc/aarch64', 'boards/arm/fvp_baser_aemv8r/doc/index'),
    ('boards/arm/fvp_baser_aemv8r/doc/debug-with-arm-ds', 'boards/arm/fvp_baser_aemv8r/doc/index'),
    ('boards/nxp/hexiwear/doc/index', 'boards/mikroe/hexiwear/doc/index'),
    ('boards/phytec/mimx8mm_phyboard_polis/doc/index', 'boards/phytec/phyboard_polis/doc/index'),
    ('boards/phytec/mimx8mp_phyboard_pollux/doc/index', 'boards/phytec/phyboard_pollux/doc/index'),
    ('boards/rak/index', 'boards/rakwireless/index'),
    ('boards/rak/rak11720/doc/index', 'boards/rakwireless/rak11720/doc/index'),
    ('boards/rak/rak4631/doc/index', 'boards/rakwireless/rak4631/doc/index'),
    ('boards/rak/rak5010/doc/index', 'boards/rakwireless/rak5010/doc/index'),
    ('connectivity/bluetooth/api/audio/shell/bap', 'connectivity/bluetooth/shell/audio/bap'),
    ('connectivity/bluetooth/api/audio/shell/bap_broadcast_assistant', 'connectivity/bluetooth/shell/audio/bap_broadcast_assistant'),
    ('connectivity/bluetooth/api/audio/shell/bap_scan_delegator', 'connectivity/bluetooth/shell/audio/bap_scan_delegator'),
    ('connectivity/bluetooth/api/audio/shell/cap', 'connectivity/bluetooth/shell/audio/cap'),
    ('connectivity/bluetooth/api/audio/shell/ccp', 'connectivity/bluetooth/shell/audio/ccp'),
    ('connectivity/bluetooth/api/audio/shell/csip', 'connectivity/bluetooth/shell/audio/csip'),
    ('connectivity/bluetooth/api/audio/shell/gmap', 'connectivity/bluetooth/shell/audio/gmap'),
    ('connectivity/bluetooth/api/audio/shell/mcp', 'connectivity/bluetooth/shell/audio/mcp'),
    ('connectivity/bluetooth/api/audio/shell/pbp', 'connectivity/bluetooth/shell/audio/pbp'),
    ('connectivity/bluetooth/api/audio/shell/tmap', 'connectivity/bluetooth/shell/audio/tmap'),
    ('connectivity/bluetooth/api/hfp', 'connectivity/bluetooth/api/classic/hfp'),
    ('connectivity/bluetooth/api/rfcomm', 'connectivity/bluetooth/api/classic/rfcomm'),
    ('connectivity/bluetooth/api/sdp', 'connectivity/bluetooth/api/classic/sdp'),
    ('connectivity/bluetooth/api/shell/iso', 'connectivity/bluetooth/shell/host/iso'),
    ('hardware/peripherals/mipi_dbi', 'hardware/peripherals/display/index'),
    ('hardware/peripherals/mipi_dsi', 'hardware/peripherals/display/index'),
    ('samples/bluetooth/central_iso/README', 'samples/bluetooth/iso_central/README'),
    ('samples/bluetooth/handsfree/README', 'samples/bluetooth/classic/handsfree/README'),
    ('samples/bluetooth/handsfree_ag/README', 'samples/bluetooth/classic/handsfree_ag/README'),
    ('samples/bluetooth/peripheral_iso/README', 'samples/bluetooth/iso_peripheral/README'),
    ('samples/boards/96b_argonkey/microphone/README', 'samples/boards/96boards/argonkey/microphone/README'),
    ('samples/boards/96b_argonkey/sensors/README', 'samples/boards/96boards/argonkey/sensors/README'),
    ('samples/boards/esp32/deep_sleep/README', 'samples/boards/espressif/deep_sleep/README'),
    ('samples/boards/esp32/flash_encryption/README', 'samples/boards/espressif/flash_encryption/README'),
    ('samples/boards/esp32/flash_memory_mapped/README', 'samples/boards/espressif/flash_memory_mapped/README'),
    ('samples/boards/esp32/light_sleep/README', 'samples/boards/espressif/light_sleep/README'),
    ('samples/boards/esp32/spiram_test/README', 'samples/boards/espressif/spiram_test/README'),
    ('samples/boards/esp32/xt_wdt/README', 'samples/boards/espressif/xt_wdt/README'),
    ('samples/boards/google_twinkie_v2_pda/README', 'samples/boards/google/twinkie_v2/pda/README'),
    ('samples/boards/intel_adsp/code_relocation/README', 'samples/boards/intel/adsp/code_relocation/README'),
    ('samples/boards/litex/i2s/README', 'samples/boards/enjoydigital/litex/i2s/README'),
    ('samples/boards/mec15xxevb_assy6853/power_management/README', 'samples/boards/microchip/mec15xxevb_assy6853/power_management/README'),
    ('samples/boards/mimxrt1060_evk/system_off/README', 'samples/boards/nxp/mimxrt1060_evk/system_off/README'),
    ('samples/boards/mimxrt1170_evk_cm7/magic_addr/README', 'samples/boards/nxp/mimxrt1170_evk_cm7/magic_addr/README'),
    ('samples/boards/mimxrt595_evk/system_off/README', 'samples/boards/nxp/mimxrt595_evk/system_off/README'),
    ('samples/boards/nrf/battery/README', 'samples/boards/nordic/battery/README'),
    ('samples/boards/nrf/clock_skew/README', 'samples/boards/nordic/clock_skew/README'),
    ('samples/boards/nrf/dynamic_pinctrl/README', 'samples/boards/nordic/dynamic_pinctrl/README'),
    ('samples/boards/nrf/ieee802154/802154_rpmsg/README', 'samples/boards/nordic/ieee802154/802154_rpmsg/README'),
    ('samples/boards/nrf/mesh/onoff-app/README', 'samples/boards/nordic/mesh/onoff-app/README'),
    ('samples/boards/nrf/mesh/onoff_level_lighting_vnd_app/README', 'samples/boards/nordic/mesh/onoff_level_lighting_vnd_app/README'),
    ('samples/boards/nrf/nrf53_sync_rtc/README', 'samples/boards/nordic/nrf53_sync_rtc/README'),
    ('samples/boards/nrf/nrf_led_matrix/README', 'samples/boards/nordic/nrf_led_matrix/README'),
    ('samples/boards/nrf/nrfx/README', 'samples/boards/nordic/nrfx/README'),
    ('samples/boards/nrf/nrfx_prs/README', 'samples/boards/nordic/nrfx_prs/README'),
    ('samples/boards/nrf/system_off/README', 'samples/boards/nordic/system_off/README'),
    ('samples/boards/nxp_s32/netc/README', 'samples/boards/nxp/s32/netc/README'),
    ('samples/boards/qomu/README', 'samples/boards/quicklogic/qomu/README'),
    ('samples/boards/stm32/backup_sram/README', 'samples/boards/st/backup_sram/README'),
    ('samples/boards/stm32/bluetooth/interactive_gui/README', 'samples/boards/st/bluetooth/interactive_gui/README'),
    ('samples/boards/stm32/ccm/README', 'samples/boards/st/ccm/README'),
    ('samples/boards/stm32/h7_dual_core/README', 'samples/boards/st/h7_dual_core/README'),
    ('samples/boards/stm32/i2c_timing/README', 'samples/boards/st/i2c_timing/README'),
    ('samples/boards/stm32/power_mgmt/adc/README', 'samples/boards/st/power_mgmt/adc/README'),
    ('samples/boards/stm32/power_mgmt/blinky/README', 'samples/boards/st/power_mgmt/blinky/README'),
    ('samples/boards/stm32/power_mgmt/serial_wakeup/README', 'samples/boards/st/power_mgmt/serial_wakeup/README'),
    ('samples/boards/stm32/power_mgmt/standby_shutdown/README', 'samples/boards/st/power_mgmt/index'),
    ('samples/boards/stm32/power_mgmt/stm32wb_ble/README', 'samples/boards/st/power_mgmt/stm32wb_ble/README'),
    ('samples/boards/stm32/power_mgmt/stop3/README', 'samples/boards/st/power_mgmt/stop3/README'),
    ('samples/boards/stm32/power_mgmt/suspend_to_ram/README', 'samples/boards/st/power_mgmt/suspend_to_ram/README'),
    ('samples/boards/stm32/power_mgmt/wkup_pins/README', 'samples/boards/st/power_mgmt/wkup_pins/README'),
    ('samples/drivers/led_is31fl3216a/README', 'samples/drivers/led/is31fl3216a/README'),
    ('samples/drivers/led_is31fl3733/README', 'samples/drivers/led/is31fl3733/README'),
    ('samples/drivers/led_lp3943/README', 'samples/drivers/led/lp3943/README'),
    ('samples/drivers/led_lp50xx/README', 'samples/drivers/led/lp50xx/README'),
    ('samples/drivers/led_lp5562/README', 'samples/drivers/led/lp5562/README'),
    ('samples/drivers/led_lp5569/README', 'samples/drivers/led/lp5569/README'),
    ('samples/drivers/led_pca9633/README', 'samples/drivers/led/pca9633/README'),
    ('samples/drivers/led_pwm/README', 'samples/drivers/led/pwm/README'),
    ('samples/drivers/led_strip/README', 'samples/drivers/led/led_strip/README'),
    ('samples/drivers/led_sx1509b_intensity/README', 'samples/drivers/led/sx1509b_intensity/README'),
    ('samples/drivers/led_xec/README', 'samples/drivers/led/xec/README'),
    ('samples/posix/env/README', 'samples/subsys/portability/posix/env/README'),
    ('samples/posix/eventfd/README', 'samples/subsys/portability/posix/eventfd/README'),
    ('samples/posix/gettimeofday/README', 'samples/subsys/portability/posix/gettimeofday/README'),
    ('samples/posix/philosophers/README', 'samples/subsys/portability/posix/philosophers/README'),
    ('samples/posix/posix', 'samples/subsys/portability/posix/posix'),
    ('samples/posix/uname/README', 'samples/subsys/portability/posix/uname/README'),
    ('samples/sensor/max44009/README', 'samples/sensor/light_polling/README'),
    ('samples/sensor/mpr/README', 'samples/sensor/pressure_polling/README'),
    ('samples/shields/npm1300_ek/doc/index', 'samples/shields/npm13xx_ek/index'),
    ('samples/shields/npm6001_ek/doc/index', 'samples/shields/npm6001_ek/index'),
    ('samples/subsys/video/capture/README', 'samples/drivers/video/capture/README'),
    ('samples/subsys/video/tcpserversink/README', 'samples/drivers/video/tcpserversink/README'),
    ('samples/subsys/video/video', 'samples/drivers/video/video'),
    ('services/file_system/index', 'services/storage/file_system/index'),
    ('services/misc', 'services/index'),
    ('services/modbus/index', 'connectivity/modbus/index'),
    ('services/retention/blinfo', 'services/storage/retention/blinfo'),
    ('services/retention/index', 'services/storage/retention/index'),
    ('services/settings/index', 'services/storage/settings/index'),
    # zephyr-keep-sorted-stop
)
