CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n
CONFIG_USBD_XBOX360_CONTROLLER_CLASS=y

CONFIG_LOG=y
CONFIG_USBD_LOG_LEVEL_WRN=y
CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=y
CONFIG_USBD_XBOX360_CONTROLLER_LOG_LEVEL_DBG=y

# Better to keep these values in a final product
CONFIG_SAMPLE_USBD_VID=0x045E
CONFIG_SAMPLE_USBD_PID=0x028E
CONFIG_SAMPLE_USBD_MANUFACTURER="Microsoft Corporation"
CONFIG_SAMPLE_USBD_PRODUCT="Controller"
CONFIG_SAMPLE_USBD_SELF_POWERED=n
