/* version_header.c */

/*
 * Copyright (c) 2018 Intel Corporation.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/types.h>
#include "version.h" /* generated by MAKE, at compile time */
#include <version_header.h>

/* The content of this struct is overwritten in a post-build script */
struct version_header version_header __attribute__((section(".version_header")))
__attribute__((used)) = {
	.magic = {'$', 'B', '!', 'N'},
	.version = 1,
};

