TIMO_BASE = $(strip $(subst /samples/nanokernel/apps/hello_world,,$(shell pwd) ))
BSP ?= generic_pc
KERNEL_TYPE = nano
SOURCE_DIR = $(TIMO_BASE)/samples/microkernel/apps/hello_world/src/


include ${TIMO_BASE}/Makefile.inc
