#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_DISPLAY_GC9A01A_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_DISPLAY_GC9A01A_H_

/* Pixel formats */
#define GC9A01A_PIXEL_FORMAT_RGB565 0U
#define GC9A01A_PIXEL_FORMAT_RGB888 1U

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_DISPLAY_GC9A01A_H_ */
