ifeq ($(CONFIG_HAS_DTS),y)
dtb-$(CONFIG_SOC_QUARK_SE_C1000)	=	arduino_101.dts_compiled
dtb-$(CONFIG_BOARD_QUARK_D2000_CRB)	=	quark_d2000_crb.dts_compiled
dtb-$(CONFIG_BOARD_TINYTILE)		=	tinytile.dts_compiled
always	:= $(dtb-y)
endif
