ifeq ($(CONFIG_HAS_DTS),y)
dtb-$(CONFIG_BOARD_ARDUINO_101)			=	arduino_101.dts_compiled
dtb-$(CONFIG_BOARD_QUARK_D2000_CRB)		=	quark_d2000_crb.dts_compiled
dtb-$(CONFIG_BOARD_TINYTILE)			=	tinytile.dts_compiled
dtb-$(CONFIG_BOARD_QUARK_SE_C1000_DEVBOARD)	=	quark_se_c1000_devboard.dts_compiled
always	:= $(dtb-y)
endif
