EXTRA_CFLAGS += ${PROJECTINCLUDE}
EXTRA_CFLAGS +=-I${srctree}/net/ip/contiki
EXTRA_CFLAGS +=-I${srctree}/net/ip/contiki/os/lib
EXTRA_CFLAGS +=-I${srctree}/net/ip/contiki/os/sys
EXTRA_CFLAGS +=-I${srctree}/net/ip/contiki/os
EXTRA_CFLAGS +=-I${srctree}/net/ip/tinydtls
EXTRA_CFLAGS +=-I${srctree}/net/ip/er-coap
EXTRA_CFLAGS +=-I${srctree}/net/ip/rest-engine
EXTRA_CFLAGS +=-I${srctree}/net/ip

obj-y = coap-server.o

obj-y += \
	resources/res-plugtest-create1.o \
	resources/res-plugtest-create2.o \
	resources/res-plugtest-create3.o \
	resources/res-plugtest-large.o \
	resources/res-plugtest-large-create.o \
	resources/res-plugtest-large-update.o \
	resources/res-plugtest-links.o \
	resources/res-plugtest-locquery.o \
	resources/res-plugtest-longpath.o \
	resources/res-plugtest-multi.o \
	resources/res-plugtest-obs.o \
	resources/res-plugtest-path.o \
	resources/res-plugtest-query.o \
	resources/res-plugtest-separate.o \
	resources/res-plugtest-test.o \
	resources/res-plugtest-validate.o
