# Kconfig - SOC_FAMILY_RISCV_PRIVILEGE common functionalities
#
# Copyright (c) 2017 Jean-Paul Etienne <fractalclone@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0
#

obj-y += soc_common_irq.o soc_irq.o
