ccflags-y += -I${srctree}/subsys/net/ip

obj-$(CONFIG_NET_L2_IEEE802154) += ieee802154.o \
					ieee802154_frame.o

obj-$(CONFIG_NET_L2_IEEE802154_MGMT) += ieee802154_mgmt.o
obj-$(CONFIG_NET_L2_IEEE802154_SHELL) += ieee802154_shell.o
obj-$(CONFIG_NET_L2_IEEE802154_RADIO_ALOHA) += ieee802154_radio_aloha.o
obj-$(CONFIG_NET_L2_IEEE802154_RADIO_CSMA_CA) += ieee802154_radio_csma_ca.o

obj-$(CONFIG_NET_L2_IEEE802154_FRAGMENT) += ieee802154_fragment.o
