
EMU_PLATFORM = qemu

QEMU_CPU_TYPE_nios2 = nios2
QEMU_FLAGS_nios2 = -machine altera_10m50_zephyr -nographic
QEMU_nios2 = qemu-system-nios2

DEBUG_SCRIPT = qemu.sh

debugserver: QEMU_EXTRA_FLAGS += -s -S
debugserver: qemu
