CONFIG_GPIO=y
CONFIG_HAPTICS=y
CONFIG_HAPTICS_LOG_LEVEL_DBG=y
CONFIG_I2C=y
CONFIG_LOG=y

# Demonstrate PM runtime features
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y

# Enable custom shell sample for demonstration
CONFIG_SHELL=y

# All CS40L26 Kconfig options and their defaults
CONFIG_HAPTICS_CS40L26_CALIBRATION=y
CONFIG_HAPTICS_CS40L26_CLICK_COMPENSATION=y
CONFIG_HAPTICS_CS40L26_DYNAMIC_F0=y
CONFIG_HAPTICS_CS40L26_PM_ACTIVE_TIMEOUT=8000
CONFIG_HAPTICS_CS40L26_PM_STDBY_TIMEOUT=160000
