CONFIG_UWB=y
CONFIG_NUM_PREEMPT_PRIORITIES=15
CONFIG_NUM_COOP_PRIORITIES=16
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_SERIAL=y
CONFIG_CLOCK_CONTROL=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_INIT_STACKS=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_MULTITHREADING=y
CONFIG_SCHED_DEADLINE=y
CONFIG_ASSERT=y
# CONFIG_USB_CDC_ACM=y
CONFIG_UART_LINE_CTRL=y
# Below Configs should be enable for the MCTT/PnP
# Optionally disable logging subsystem if you don't use it elsewhere
CONFIG_LOG=y
CONFIG_HEAP_MEM_POOL_SIZE=20000
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_MAIN_STACK_SIZE=2048

CONFIG_KERNEL_BIN_NAME="demo_ranging_controller"
