.. SPDX-License-Identifier: Apache-2.0
..
.. Copyright (c) 2026 Ezurio LLC

.. _RM126x product brief:
   https://www.ezurio.com/documentation/product-brief-rm126x-series

.. _RM126x website:
   https://www.ezurio.com/wireless-modules/lorawan-modules-solutions/rm126x-ultra-low-power-lorawan-a-b-c-module

.. _RM126x datasheet:
   https://www.ezurio.com/documentation/datasheet-rm126x-lorawan-module

.. _EFR32BG22 datasheet:
   https://www.silabs.com/documents/public/data-sheets/efr32bg22-datasheet.pdf

.. _EFR32BG22 reference manual:
   https://www.silabs.com/documents/public/reference-manuals/efr32xg22-rm.pdf

.. _SX126x datasheet:
   https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/RQ000008n3pp/qXjWn19TZmb.1MgqPZ8Vrc5V7U.M_lOAIoTZHcEAeTI

.. _mikroBUS:
   https://www.mikroe.com/mikrobus

.. _Qwiic:
   https://www.sparkfun.com/qwiic

.. _RM126x DVK user guide:
   https://www.ezurio.com/documentation/user-guide-rm126x-development-kit

.. _Simplicity Studio:
   https://www.silabs.com/software-and-tools/simplicity-studio
