# Makefile - Kinetis KWx MCU series
#
# Copyright (c) 2017, NXP
#
# SPDX-License-Identifier: Apache-2.0
#

obj-$(CONFIG_SOC_MKW24D5) += wdog.o soc_kw2xd.o
obj-$(CONFIG_SOC_MKW22D5) += wdog.o soc_kw2xd.o
obj-$(CONFIG_SOC_MKW41Z4) += soc_kw4xz.o
obj-$(CONFIG_SOC_MKW40Z4) += soc_kw4xz.o
