ccflags-y +=-I$(srctree)/arch/arc/soc/
ccflags-y +=-I$(srctree)/include
ccflags-y +=-I$(srctree)/include/drivers
ccflags-y +=-I$(srctree)/drivers

asflags-y := ${ccflags-y}

obj-y += soc.o soc_config.o

obj-$(CONFIG_ARC_MPU_ENABLE) += arc_mpu_regions.o
