#
# Copyright (c) 2026 Espressif Systems (Shanghai) Co., Ltd.
#

CONFIG_ESP_SPIRAM=y
CONFIG_SHARED_MULTI_HEAP=y

# lib & os
CONFIG_EVENTS=y

# CPP library
CONFIG_CPP=y

# Enable Openthread RCP host interface
CONFIG_IEEE802154=n
CONFIG_HDLC_RCP_IF=y
CONFIG_OPENTHREAD_MANUAL_START=y
CONFIG_OPENTHREAD_RCP_RESTORATION_MAX_COUNT=10
CONFIG_OPENTHREAD_EXTERNAL_HEAP_SHARED_MULTI_HEAP=y
CONFIG_OPENTHREAD_MESSAGE_POOL_CUSTOM_SECTION=y
