# Persistent TLS session cache
# Usage: west build -b <board> samples/net/sockets/http_get -- \
#   -DEXTRA_CONF_FILE="overlay-tls.conf;overlay-tls-session-cache.conf"

CONFIG_NET_SAMPLE_TLS_SESSION_CACHE=y

CONFIG_SETTINGS=y
CONFIG_NET_SOCKETS_TLS_SESSION_CACHE_PERSISTENT=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_NVS=y
CONFIG_SETTINGS_NVS=y
