OPENSDA_FW ?= jlink

ifeq ($(OPENSDA_FW),jlink)
DEBUG_SCRIPT ?= jlink.sh
endif

ifeq ($(OPENSDA_FW),daplink)
DEBUG_SCRIPT ?= pyocd.sh
FLASH_SCRIPT ?= pyocd.sh
endif

JLINK_DEVICE = MKW40Z160xxx4

PYOCD_TARGET = kw40z4

export JLINK_DEVICE PYOCD_TARGET
