lwm2m_senml = [1* record]

record = {
	? bn => tstr,            ; Base Name
	? n => tstr,             ; Name
	? ( vi => int .size 8 // ; Integer Value
	    vf => float       // ; Float Value
	    vs => tstr        // ; String Value
	    vb => bool        // ; Boolean Value
	    vd => bstr ),        ; Data Value
	0*3 key-value-pair       ; To handle unordered maps; length-first ordered map keys
}

; now define the generic versions
key-value-pair = ( int => value )

value = tstr / bstr / int .size 8 / float / bool

n  = 0
bn = -2
vi = 2
vf = 2
vs = 3
vd = 8
vb = 4
