

include $(srctree)/ext/hal/cmsis/Makefile

include $(srctree)/ext/hal/ksdk/Makefile

include $(srctree)/ext/hal/nordic/mdk/Makefile

include $(srctree)/ext/hal/qmsi/Makefile

include $(srctree)/ext/hal/st/stm32cube/Makefile

include $(srctree)/ext/hal/ti/cc3200sdk/Makefile
