
ifdef CONFIG_ASF
include $(srctree)/ext/hal/atmel/asf/Makefile
endif

-include $(srctree)/ext/hal/cmsis/Makefile

-include $(srctree)/ext/hal/nordic/Makefile

-include $(srctree)/ext/hal/nxp/mcux/Makefile

-include $(srctree)/ext/hal/qmsi/Makefile

-include $(srctree)/ext/hal/st/stm32cube/Makefile

-include $(srctree)/ext/hal/ti/simplelink/Makefile

-include $(srctree)/ext/hal/rda/rda5981a/Makefile
