obj-$(CONFIG_RANDOM_MCUX_RNGA) += random_mcux_rnga.o
obj-$(CONFIG_RANDOM_MCUX_TRNG) += random_mcux_trng.o
obj-$(CONFIG_RANDOM_STM32_RNG) += random_stm32_rng.o
obj-$(CONFIG_RANDOM_ESP32_RNG) += random_esp32.o

obj-$(CONFIG_USERSPACE) += random_handlers.o
