subdir-ccflags-y +=-I${srctree}/net/ip/contiki
subdir-ccflags-y +=-I${srctree}/net/ip/contiki/os/lib
subdir-ccflags-y +=-I${srctree}/net/ip/contiki/os
subdir-ccflags-y +=-I${srctree}/net/ip

obj-$(CONFIG_TI_CC2520_LEGACY) += ieee802154_cc2520_legacy.o
obj-$(CONFIG_TI_CC2520) += ieee802154_cc2520.o
