obj-$(CONFIG_TI_CC2520) += ieee802154_cc2520.o
obj-$(CONFIG_TI_CC2520_RAW) += ieee802154_cc2520.o
obj-$(CONFIG_UPIPE_15_4) += ieee802154_uart_pipe.o
obj-$(CONFIG_NXP_MCR20A) += ieee802154_mcr20a.o
obj-$(CONFIG_NXP_MCR20A_RAW) += ieee802154_mcr20a.o
