ccflags-y += -I${ZEPHYR_BASE}/net/ip/contiki
ccflags-y += -I${ZEPHYR_BASE}/net/ip/contiki/os/lib
ccflags-y += -I${ZEPHYR_BASE}/net/ip/contiki/os
ccflags-y += -I${ZEPHYR_BASE}/net/ip
ccflags-$(CONFIG_NET_SANITY_TEST) += -I${ZEPHYR_BASE}/samples/include

obj-y = network.o
