/*
 * Copyright (c) 2024 Infineon Technologies AG
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_SOC_INFINEON_AURIX_TC4X_SOC_TAGID_H_
#define ZEPHYR_SOC_INFINEON_AURIX_TC4X_SOC_TAGID_H_

#define AURIX_TAGID_CPU0    0x00
#define AURIX_TAGID_CPU0_S  0x01
#define AURIX_TAGID_CPU1    0x02
#define AURIX_TAGID_CPU1_S  0x03
#define AURIX_TAGID_CPU2    0x04
#define AURIX_TAGID_CPU2_S  0x05
#define AURIX_TAGID_CPU3    0x06
#define AURIX_TAGID_CPU3_S  0x07
#define AURIX_TAGID_CPU4    0x08
#define AURIX_TAGID_CPU4_S  0x09
#define AURIX_TAGID_CPU5    0x0A
#define AURIX_TAGID_CPU5_S  0x0B
#define AURIX_TAGID_CPUCS   0x0C
#define AURIX_TAGID_CPUCS_S 0x0D

#define AURIX_TAGID_CPU0_P  0x28
#define AURIX_TAGID_CPU1_P  0x29
#define AURIX_TAGID_CPU2_P  0x2A
#define AURIX_TAGID_CPU3_P  0x2B
#define AURIX_TAGID_CPU4_P  0x2C
#define AURIX_TAGID_CPU5_P  0x2D
#define AURIX_TAGID_CPUCS_P 0x2E

#define AURIX_TAGID_GETH_C0 0x30
#define AURIX_TAGID_GETH_C1 0x31
#define AURIX_TAGID_GETH_C2 0x32
#define AURIX_TAGID_GETH_C3 0x33
#define AURIX_TAGID_GETH_C4 0x34
#define AURIX_TAGID_GETH_C5 0x35
#define AURIX_TAGID_GETH_C6 0x36
#define AURIX_TAGID_GETH_C7 0x37

#define AURIX_TAGID_PPUSTU 0x38
#define AURIX_TAGID_SDMMC  0x39
#define AURIX_TAGID_XSPI   0x3A
#define AURIX_TAGID_CANXL  0x3B

#define AURIX_TAGID_LETH_P0 0x3C
#define AURIX_TAGID_LETH_P1 0x3D

#define AURIX_TAGID_OCMTS 0x3E

#endif /* ZEPHYR_SOC_INFINEON_AURIX_TC4X_SOC_TAGID_H_ */
