
#define CONFIG_BT_CONN
#define CONFIG_BT_MAX_CONN 4

#ifndef CONFIG_BT_CTLR_PHY
#define CONFIG_BT_CTLR_PHY
#endif

/* Kconfig Cheats */
#define CONFIG_BT_LOG_LEVEL 1
#define CONFIG_BT_CTLR_COMPANY_ID 0x1234
#define CONFIG_BT_CTLR_SUBVERSION_NUMBER 0x5678
#define CONFIG_NET_BUF_USER_DATA_SIZE 4096
#define PROC_CTX_BUF_NUM 2
#define TX_CTRL_BUF_NUM 2
#define NTF_BUF_NUM 2
