ZEPHYRINCLUDE +=-I${srctree}/ext/drivers/atmel/winc1500
ZEPHYRINCLUDE +=-I${srctree}/drivers/wifi/winc1500

obj-$(CONFIG_WIFI_WINC1500) += \
				bsp/source/nm_bsp.o \
				bus_wrapper/source/nm_bus_wrapper.o \
				winc1500.o
