/*
 * Copyright (c) 2019 Manivannan Sadhasivam <mani@kernel.org>
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_ACTS_CMU_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_ACTS_CMU_H_

#define ACTS_CLOCK_DMA			0
#define ACTS_CLOCK_SPICACHE		1
#define ACTS_CLOCK_SPI0			2
#define ACTS_CLOCK_SPI1			3
#define ACTS_CLOCK_SPI2			4
#define ACTS_CLOCK_UART0		5
#define ACTS_CLOCK_UART1		6
#define ACTS_CLOCK_UART2		7
#define ACTS_CLOCK_I2C0			8
#define ACTS_CLOCK_I2C1			9
#define ACTS_CLOCK_PWM0			10
#define ACTS_CLOCK_PWM1			11
#define ACTS_CLOCK_PWM2			12
#define ACTS_CLOCK_PWM3			13
#define ACTS_CLOCK_PWM4			14
#define ACTS_CLOCK_KEY			15
#define ACTS_CLOCK_ADC			16
#define ACTS_CLOCK_I2STX		17
#define ACTS_CLOCK_I2SRX		18
#define ACTS_CLOCK_LRADC		19
#define ACTS_CLOCK_TIMER0		20
#define ACTS_CLOCK_TIMER1		21
#define ACTS_CLOCK_TIMER2		22
#define ACTS_CLOCK_TIMER3		23
#define ACTS_CLOCK_BLE_HCLK_EN		24
#define ACTS_CLOCK_BLE_HCLK_GATING	25
#define ACTS_CLOCK_BLE_LLCC_CLK_REQ_O	26
#define ACTS_CLOCK_HCL4HZ		27
#define ACTS_CLOCK_HCL32K		28
#define ACTS_CLOCK_EFUSE		29
#define ACTS_CLOCK_IRC_RXCLK		30
#define ACTS_CLOCK_IRC_CLK		31
#define ACTS_CLOCK_MAX			32

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_ACTS_CMU_H_ */
