EXTRA_CFLAGS +=-I$(srctree)/kernel/microkernel/include

obj-y = ch_addit.o InitChan.o ch_buff.o ch_buffm.o \
	K_Ch_RO.o K_Ch_WO.o K_Ch_WR.o K_Ch_Mvd.o  \
	KS_Chan.o KS_ChPut.o KS_ChPtA.o KS_ChGet.o \
	K_ChProc.o K_ChPAck.o K_ChPRpl.o K_ChPReq.o \
	K_ChPTmo.o K_ChGAck.o K_ChGRpl.o K_ChGReq.o K_ChGTmo.o
