# Makefile - ARM LTD Beetle SoC build options

#
# Copyright (c) 2016 Linaro Limited
#
# SPDX-License-Identifier: Apache-2.0
#

obj-y += soc.o power.o
obj-$(CONFIG_ARM_MPU_ENABLE) += arm_mpu_regions.o
