# Makefile - Atmel SAM E70 MCU series
#
# Copyright (c) 2016 Piotr Mienkowski
# SPDX-License-Identifier: Apache-2.0
#

ZEPHYRINCLUDE += -I$(srctree)/arch/arm/soc/atmel_sam/common

obj-y += soc.o
obj-y += soc_config.o
