ccflags-$(CONFIG_HAS_CC3220SDK) += -D$(COMPILER)
# Need to build prcm and utils for PRCMCC3220MCUInit, which is not in ROM
obj-$(CONFIG_HAS_CC3220SDK) += driverlib/utils.o
obj-$(CONFIG_HAS_CC3220SDK) += driverlib/prcm.o
