ifdef CONFIG_HAS_CC3220SDK
ZEPHYRINCLUDE +=-I$(srctree)/ext/hal/ti/cc3220sdk
ZEPHYRINCLUDE +=-I$(srctree)/ext/hal/ti/cc3220sdk/inc
ZEPHYRINCLUDE +=-I$(srctree)/ext/hal/ti/cc3220sdk/driverlib
KBUILD_CFLAGS += -DUSE_CC3200_ROM_DRV_API
endif # CONFIG_HAS_CC3220SDK
