include $(srctree)/ext/lib/Makefile
include $(srctree)/ext/hal/Makefile
include $(srctree)/ext/fs/Makefile
include $(srctree)/ext/debug/Makefile
include $(srctree)/ext/drivers/atmel/winc1500/Makefile
