generate_inc_file += \
	response_small.html.bin \
	response_big.html.bin

include $(ZEPHYR_BASE)/scripts/Makefile.gen

include $(ZEPHYR_BASE)/samples/net/common/Makefile.common

obj-y += socket_dumb_http.o
