CONFIG_LOG=y
CONFIG_SHELL=y

# Needed for boards that enable RTT backends for logging
CONFIG_LOG_BACKEND_RTT=n

# Enable SMF and ESMF
CONFIG_SMF=y
CONFIG_SMF_ANCESTOR_SUPPORT=y
CONFIG_SMF_INITIAL_TRANSITION=n
CONFIG_SMF_ESMF=y
