obj-$(CONFIG_AON_COUNTER_QMSI) += counter_qmsi_aon.o
obj-$(CONFIG_AON_TIMER_QMSI) += counter_qmsi_aonpt.o
obj-$(CONFIG_COUNTER_TMR_CMSDK_APB) += counter_tmr_cmsdk_apb.o
obj-$(CONFIG_TIMER_TMR_CMSDK_APB) += timer_tmr_cmsdk_apb.o
obj-$(CONFIG_COUNTER_DTMR_CMSDK_APB) += counter_dtmr_cmsdk_apb.o
obj-$(CONFIG_TIMER_DTMR_CMSDK_APB) += timer_dtmr_cmsdk_apb.o
