obj-$(CONFIG_UART_CONSOLE) = uart_console.o
obj-$(CONFIG_RAM_CONSOLE) += ram_console.o
obj-$(CONFIG_IPI_CONSOLE_RECEIVER) += ipi_console_receiver.o
obj-$(CONFIG_IPI_CONSOLE_SENDER) += ipi_console_sender.o
obj-$(CONFIG_UART_PIPE) += uart_pipe.o
