KERNEL_TYPE = nano
KBUILD_DEFCONFIG ?= $(KERNEL_TYPE)_generic_pc_defconfig
CONF_FILE = prj_$(ARCH).conf
SOURCE_DIR = $(ZEPHYR_BASE)/samples/microkernel/test/test_static_idt/src/

include $(ZEPHYR_BASE)/Makefile.inc
