KERNEL_TYPE = nano
PLATFORM_CONFIG ?= generic_pc_atom_n28xx
CONF_FILE = prj_$(ARCH).conf
SOURCE_DIR = $(ZEPHYR_BASE)/samples/microkernel/test/test_static_idt/src/

include $(ZEPHYR_BASE)/Makefile.inc
