# Makefile - ARM V2M Beetle Board build options

#
# Copyright (c) 2016 Linaro Limited
#
# SPDX-License-Identifier: Apache-2.0
#

# Trick the build system into generating built-in.o even though there
# are no C files (yet) to compile
obj- += dummy.o
