KERNEL_TYPE = nano
PLATFORM_CONFIG ?= basic_atom
SOURCE_DIR = $(ZEPHYR_BASE)/samples/microkernel/apps/kernel_event_logger_sample/src/
MDEF_FILE = prj.mdef
CONF_FILE = prj_$(ARCH).conf

include ${ZEPHYR_BASE}/Makefile.inc
