ccflags-y +=-I$(srctree)/drivers

obj-$(CONFIG_SENSOR_DELAYED_WORK) += sensor.o

obj-$(CONFIG_BMA280) += sensor_bma280.o
obj-$(CONFIG_BMA280_TRIGGER) += sensor_bma280_trigger.o
obj-$(CONFIG_MCP9808) += sensor_mcp9808.o
obj-$(CONFIG_MCP9808_TRIGGER) += sensor_mcp9808_trigger.o
obj-$(CONFIG_SX9500) += sensor_sx9500.o
obj-$(CONFIG_SX9500_TRIGGER) += sensor_sx9500_trigger.o
