ccflags-y +=-I$(srctree)/drivers

obj-$(CONFIG_SENSOR_DELAYED_WORK) += sensor.o

obj-$(CONFIG_BMA280) += sensor_bma280.o
obj-$(CONFIG_BMA280_TRIGGER) += sensor_bma280_trigger.o
obj-$(CONFIG_BMC150_MAGN) += sensor_bmc150_magn.o
obj-$(CONFIG_BMP280) += sensor_bmp280.o
obj-$(CONFIG_HDC1008) += sensor_hdc1008.o
obj-$(CONFIG_ISL29035) += sensor_isl29035.o
obj-$(CONFIG_ISL29035_TRIGGER) += sensor_isl29035_trigger.o
obj-$(CONFIG_LIS3DH) += sensor_lis3dh.o
obj-$(CONFIG_LIS3DH_TRIGGER) += sensor_lis3dh_trigger.o
obj-$(CONFIG_LSM9DS0_GYRO) += sensor_lsm9ds0_gyro.o
obj-$(CONFIG_MCP9808) += sensor_mcp9808.o
obj-$(CONFIG_MCP9808_TRIGGER) += sensor_mcp9808_trigger.o
obj-$(CONFIG_SHT3XD) += sensor_sht3xd.o
obj-$(CONFIG_SHT3XD_TRIGGER) += sensor_sht3xd_trigger.o
obj-$(CONFIG_SX9500) += sensor_sx9500.o
obj-$(CONFIG_SX9500_TRIGGER) += sensor_sx9500_trigger.o
