ifdef CONFIG_ZOAP
include $(srctree)/subsys/net/lib/zoap/Makefile
endif

ifdef CONFIG_DNS_RESOLVER
include $(srctree)/subsys/net/lib/dns/Makefile
endif

ifdef CONFIG_MQTT_LIB
include $(srctree)/subsys/net/lib/mqtt/Makefile
endif

ifdef CONFIG_HTTP_PARSER
include $(srctree)/subsys/net/lib/http/Makefile
endif
