# Makefile - Bluetooth LE central sample makefile

#
# Copyright (c) 2015-2016 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

# DESCRIPTION
# Makefile for the Bluetooth LE central role sample
BOARD ?= qemu_x86
CONF_FILE = prj.conf
QEMU_EXTRA_FLAGS = -serial unix:/tmp/bt-server-bredr

include $(ZEPHYR_BASE)/Makefile.inc
