# Copyright (c) 2026 Antmicro <www.antmicro.com>

CONFIG_SAMPLE_COLORED_OUTPUT=y

CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_PROMPT_UART=""
CONFIG_SHELL_ECHO_STATUS=n
CONFIG_SHELL_VT100_COLORS=y

CONFIG_USB_HOST_STACK=y
CONFIG_USBH_STACK_SIZE=2048

CONFIG_INPUT=y
CONFIG_INPUT_MODE_THREAD=y

CONFIG_ASSERT=y
CONFIG_ASSERT_LEVEL=2

CONFIG_USBH_HID_BOOT_CLASS=y
CONFIG_USBH_HID_BOOT_INSTANCES_COUNT=1
