/*
 * Copyright (c) 2023 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __NXP_INPUTMUX_RT6XX_H__
#define __NXP_INPUTMUX_RT6XX_H__

#define ADSP_IRQ_SRC_FLEXCOMM0 0
#define ADSP_IRQ_SRC_FLEXCOMM1 1
#define ADSP_IRQ_SRC_FLEXCOMM2 2
#define ADSP_IRQ_SRC_FLEXCOMM3 3
#define ADSP_IRQ_SRC_FLEXCOMM4 4
#define ADSP_IRQ_SRC_FLEXCOMM5 5
#define ADSP_IRQ_SRC_FLEXCOMM6 6
#define ADSP_IRQ_SRC_FLEXCOMM7 7
#define ADSP_IRQ_SRC_GPIO_INT0_IRQ0 8
#define ADSP_IRQ_SRC_GPIO_INT0_IRQ1 9
#define ADSP_IRQ_SRC_GPIO_INT0_IRQ2 10
#define ADSP_IRQ_SRC_GPIO_INT0_IRQ3 11
#define ADSP_IRQ_SRC_GPIO_INT0_IRQ4 12
#define ADSP_IRQ_SRC_GPIO_INT0_IRQ5 13
#define ADSP_IRQ_SRC_GPIO_INT0_IRQ6 14
#define ADSP_IRQ_SRC_GPIO_INT0_IRQ7 15
#define ADSP_IRQ_SRC_NSHSGPIO_INT0 16
#define ADSP_IRQ_SRC_NSHSGPIO_INT1 17
#define ADSP_IRQ_SRC_WDT1 18
#define ADSP_IRQ_SRC_DMAC0 19
#define ADSP_IRQ_SRC_DMAC1 20
#define ADSP_IRQ_SRC_MU 21
#define ADSP_IRQ_SRC_UTICK0 22
#define ADSP_IRQ_SRC_MRT0 23
#define ADSP_IRQ_SRC_OS_EVENT 24
#define ADSP_IRQ_SRC_CT32BIT0 25
#define ADSP_IRQ_SRC_CT32BIT1 26
#define ADSP_IRQ_SRC_CT32BIT2 27
#define ADSP_IRQ_SRC_CT32BIT3 28
#define ADSP_IRQ_SRC_CT32BIT4 29
#define ADSP_IRQ_SRC_RTC_LITE0 30
#define ADSP_IRQ_SRC_RTC_I3C0 31
#define ADSP_IRQ_SRC_RTC_DMIC0 32
#define ADSP_IRQ_SRC_RTC_HWVAD0 33
#define ADSP_IRQ_SRC_RTC_FLEXSPI 34
#define ADSP_IRQ_SRC_NONE 63

#endif
