TIMO_BASE = $(strip $(subst /samples/nanokernel/apps/philosophers,,$(shell pwd) ))
BSP ?= generic_pc
KERNEL_TYPE = nano
SOURCE_DIR = $(TIMO_BASE)/samples/microkernel/apps/philosophers/src/

include ${TIMO_BASE}/Makefile.inc
