ifdef CONFIG_ZOAP
include $(srctree)/lib/iot/zoap/Makefile
endif

ifdef CONFIG_DNS_RESOLVER
include $(srctree)/lib/iot/dns/Makefile
endif

ifdef CONFIG_MQTT_LIB
include $(srctree)/lib/iot/mqtt/Makefile
endif
