/*
 * Copyright (c) 2018 Linaro Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* Board level DTS fixup file */

#define DT_SPI_FLASH_W25QXXDV_SPI_SLAVE		DT_SNPS_DESIGNWARE_SPI_B0001000_WINBOND_W25Q16_0_BASE_ADDRESS
#define DT_SPI_FLASH_W25QXXDV_SPI_NAME		DT_SNPS_DESIGNWARE_SPI_B0001000_WINBOND_W25Q16_0_BUS_NAME
#define DT_SPI_FLASH_W25QXXDV_SPI_FREQ		DT_SNPS_DESIGNWARE_SPI_B0001000_WINBOND_W25Q16_0_SPI_MAX_FREQUENCY

#define DT_SPI_FLASH_W25QXXDV_GPIO_SPI_CS_DRV_NAME	DT_SNPS_DESIGNWARE_SPI_B0001000_CS_GPIOS_CONTROLLER
#define DT_SPI_FLASH_W25QXXDV_GPIO_SPI_CS_PIN		DT_SNPS_DESIGNWARE_SPI_B0001000_CS_GPIOS_PIN


/* End of Board Level DTS fixup file */
