ccflags-$(CONFIG_I2C_QMSI) +=-I$(CONFIG_QMSI_INSTALL_PATH)/include
obj-$(CONFIG_I2C_DW) += i2c_dw.o
obj-$(CONFIG_I2C_QMSI) += i2c_qmsi.o
obj-$(CONFIG_I2C_QUARK_SE_SS) += i2c_quark_se_ss.o
obj-$(CONFIG_I2C_ATMEL_SAM3) += i2c_atmel_sam3.o