obj-$(CONFIG_I2C_ATMEL_SAM3) += i2c_atmel_sam3.o
obj-$(CONFIG_I2C_DW) += i2c_dw.o
obj-$(CONFIG_I2C_MCUX) += i2c_mcux.o
obj-$(CONFIG_I2C_NRF5) += i2c_nrf5.o
obj-$(CONFIG_I2C_QMSI) += i2c_qmsi.o
obj-$(CONFIG_I2C_QMSI_SS) += i2c_qmsi_ss.o
obj-$(CONFIG_I2C_STM32LX) += i2c_stm32lx.o
