#
# Copyright (c) 2016 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
include ${ZEPHYR_BASE}/tests/Makefile.test
ccflags-y += -I$(ZEPHYR_BASE)/tests/include

obj-y += http_header_fields.o
