obj-$(CONFIG_SERIAL)		+= serial.o
obj-$(CONFIG_UART_NS16550)	+= uart_ns16550.o
obj-$(CONFIG_UART_K20)		+= uart_k20.o
obj-$(CONFIG_UART_STELLARIS)	+= uart_stellaris.o
obj-$(CONFIG_NSIM)		+= uart_nsim.o
