/*
 * Copyright (c) 2025, Microchip Technology Inc.
 * SPDX-License-Identifier: Apache-2.0
 */

#include <xc.h>

/* UART Register Offsets */
#define OFFSET_STA   (&U1STAT - &U1CON) * sizeof(int) /* Offset for UART Status register */
#define OFFSET_BRG   (&U1BRG - &U1CON) * sizeof(int)  /* Offset for Baud Rate Generator register */
#define OFFSET_RXREG (&U1RXB - &U1CON) * sizeof(int)  /* Offset for UART Receive register */
#define OFFSET_TXREG (&U1TXB - &U1CON) * sizeof(int)  /* Offset for UART Transmit register */

#if defined(CONFIG_SOC_P33AK128MC106) || defined(CONFIG_SOC_P33AK512MPS512)
#define UART_INST_MAX 3
uint32_t BIT_TXEN[UART_INST_MAX] = {_U1CON_TXEN_MASK, _U2CON_TXEN_MASK, _U3CON_TXEN_MASK};
uint32_t BIT_RXEN[UART_INST_MAX] = {_U1CON_RXEN_MASK, _U2CON_RXEN_MASK, _U3CON_RXEN_MASK};
uint32_t BIT_UARTEN[UART_INST_MAX] = {_U1CON_ON_MASK, _U2CON_ON_MASK, _U3CON_ON_MASK};
uint32_t BIT_TXBF[UART_INST_MAX] = {_U1STAT_TXBF_MASK, _U2STAT_TXBF_MASK, _U3STAT_TXBF_MASK};
uint32_t BIT_TXBE[UART_INST_MAX] = {_U1STAT_TXBE_MASK, _U2STAT_TXBE_MASK, _U3STAT_TXBE_MASK};
uint32_t BIT_RXBF[UART_INST_MAX] = {_U1STAT_RXBF_MASK, _U2STAT_RXBF_MASK, _U3STAT_RXBF_MASK};
uint32_t BIT_RXBE[UART_INST_MAX] = {_U1STAT_RXBE_MASK, _U2STAT_RXBE_MASK, _U3STAT_RXBE_MASK};
uint32_t BIT_PERIE[UART_INST_MAX] = {_U1STAT_PERIE_MASK, _U2STAT_PERIE_MASK, _U3STAT_PERIE_MASK};
uint32_t BIT_ABDOVIE[UART_INST_MAX] = {_U1STAT_ABDOVIE_MASK, _U2STAT_ABDOVIE_MASK,
				       _U3STAT_ABDOVIE_MASK};
uint32_t BIT_CERIE[UART_INST_MAX] = {_U1STAT_CERIE_MASK, _U2STAT_CERIE_MASK, _U3STAT_CERIE_MASK};
uint32_t BIT_FERIE[UART_INST_MAX] = {_U1STAT_FERIE_MASK, _U2STAT_FERIE_MASK, _U3STAT_FERIE_MASK};
uint32_t BIT_RXBKIE[UART_INST_MAX] = {_U1STAT_RXBKIE_MASK, _U2STAT_RXBKIE_MASK,
				      _U3STAT_RXBKIE_MASK};
uint32_t BIT_RXFOIE[UART_INST_MAX] = {_U1STAT_RXFOIE_MASK, _U2STAT_RXFOIE_MASK,
				      _U3STAT_RXFOIE_MASK};
uint32_t BIT_TXCIE[UART_INST_MAX] = {_U1STAT_TXCIE_MASK, _U2STAT_TXCIE_MASK, _U3STAT_TXCIE_MASK};
uint32_t BIT_PERIF[UART_INST_MAX] = {_U1STAT_PERIF_MASK, _U2STAT_PERIF_MASK, _U3STAT_PERIF_MASK};
uint32_t BIT_ABDOVIF[UART_INST_MAX] = {_U1STAT_ABDOVIF_MASK, _U2STAT_ABDOVIF_MASK,
				       _U3STAT_ABDOVIF_MASK};
uint32_t BIT_CERIF[UART_INST_MAX] = {_U1STAT_CERIF_MASK, _U2STAT_CERIF_MASK, _U3STAT_CERIF_MASK};
uint32_t BIT_FERIF[UART_INST_MAX] = {_U1STAT_FERIF_MASK, _U2STAT_FERIF_MASK, _U3STAT_FERIF_MASK};
uint32_t BIT_RXBTIF[UART_INST_MAX] = {_U1STAT_RXBKIF_MASK, _U2STAT_RXBKIF_MASK,
				      _U3STAT_RXBKIF_MASK};
uint32_t BIT_RXFOIF[UART_INST_MAX] = {_U1STAT_RXFOIF_MASK, _U2STAT_RXFOIF_MASK,
				      _U3STAT_RXFOIF_MASK};
uint32_t BIT_TXCIF[UART_INST_MAX] = {_U1STAT_TXCIF_MASK, _U2STAT_TXCIF_MASK, _U3STAT_TXCIF_MASK};
uint32_t BIT_CLOCK_MODE[UART_INST_MAX] = {_U1CON_CLKMOD_MASK, _U2CON_CLKMOD_MASK,
					  _U3CON_CLKMOD_MASK};
uint32_t BIT_TXWM_POS[UART_INST_MAX] = {_U1STAT_TXWM_POSITION, _U2STAT_TXWM_POSITION,
					_U3STAT_TXWM_POSITION};
uint32_t BIT_RXWM_POS[UART_INST_MAX] = {_U1STAT_RXWM_POSITION, _U2STAT_RXWM_POSITION,
					_U3STAT_RXWM_POSITION};

/* Mask for receiver buffer */
uint32_t BIT_MASK_RCVR[UART_INST_MAX] = {_U1RXB_RXB_MASK, _U2RXB_RXB_MASK, _U3RXB_RXB_MASK};

/* UART Interrupt Level Select Enum (0–7) */
typedef enum {
	UART_INTLVL_0 = 0x0U,
	UART_INTLVL_1 = 0x1U,
	UART_INTLVL_2 = 0x2U,
	UART_INTLVL_3 = 0x3U,
	UART_INTLVL_4 = 0x4U,
	UART_INTLVL_5 = 0x5U,
	UART_INTLVL_6 = 0x6U,
	UART_INTLVL_7 = 0x7U
} uart_intlvl_t;

/* UART Mode Selection (UxMODE<3:0>) */
typedef enum {
	UART_MODE_ASYNC_8BIT = 0x0U,             /* Asynchronous 8-bit UART */
	UART_MODE_ASYNC_7BIT = 0x1U,             /* Asynchronous 7-bit UART */
	UART_MODE_ASYNC_8BIT_ODD_PARITY = 0x2U,  /* 8-bit UART, odd parity */
	UART_MODE_ASYNC_8BIT_EVEN_PARITY = 0x3U, /* 8-bit UART, even parity */
	UART_MODE_ASYNC_9BIT_ADDR = 0x4U,        /* 9-bit UART with address detect */
	UART_MODE_DMX = 0xAU,                    /* DMX mode */
	UART_MODE_LIN_RESPONDER_ONLY = 0xBU,     /* LIN responder only */
	UART_MODE_LIN_CMD_RESP = 0xCU,           /* LIN commander/responder */
	UART_MODE_IRDA = 0xEU,                   /* IrDA mode */
	UART_MODE_SMART_CARD = 0xFU,             /* Smart card mode */
} uart_mode_t;

#endif
