ccflags-y += -I${srctree}/include/drivers/usb -I${srctree}/usb/include

obj-$(CONFIG_USB_DEVICE_STACK) += usb_device.o usb_descriptor.o
obj-$(CONFIG_USB_COMPOSITE_DEVICE) += composite.o
obj-$(CONFIG_USB_DEVICE_STACK) += class/
