#
# Copyright (c) 2017 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0


# Abstraction of 'run' goal with Qemu

# QEMU_INSTANCE is a command line argument to make.
QEMU_FLAGS = $(QEMU_FLAGS_$(ARCH))

ifeq ($(JAILHOUSE_QEMU_IMG_FILE),)
run: zephyr
	$(error You have to provide a valid qcow2 QEMU image to be a Jailhouse root cell (variable JAILHOUSE_QEMU_IMG_FILE)!)
else
run: zephyr
	@echo '[QEMU] CPU: $(QEMU_CPU_TYPE_$(ARCH))'
	$(Q)$(QEMU_x86) $(QEMU_FLAGS) $(QEMU_EXTRA_FLAGS)
endif
