#!/bin/bash

#
# Copyright (c) 2014-2015 Wind River Systems, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

[ x$(which grep) = x ] && exit -1

num_cpus=$(\grep -c "^processor" /proc/cpuinfo)

if [ x${ZEPHYR_JOBS} = x ]; then
	ZEPHYR_JOBS=$((${num_cpus} * 2 + 1))
fi

echo Using $ZEPHYR_JOBS threads
nice make --jobs=${ZEPHYR_JOBS} --load-average=${num_cpus} $@
