# Makefile - MCUXpresso SDK drivers
#
# Copyright (c) 2016, Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier: Apache-2.0

obj-$(CONFIG_ETH_MCUX) += fsl_enet.o
obj-$(CONFIG_I2C_MCUX) += fsl_i2c.o
obj-$(CONFIG_RANDOM_MCUX_RNGA) += fsl_rnga.o
obj-$(CONFIG_RANDOM_MCUX_TRNG) += fsl_trng.o
obj-$(CONFIG_SOC_FLASH_MCUX) += fsl_flash.o
obj-$(CONFIG_SPI_MCUX_DSPI) += fsl_dspi.o
obj-$(CONFIG_UART_MCUX) += fsl_uart.o
obj-$(CONFIG_UART_MCUX_LPUART) += fsl_lpuart.o
