# Makefile - FXOS8700 6-axis accelerometer/magnetometer
#
# Copyright (c) 2016, Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

obj-$(CONFIG_FXOS8700) += fxos8700.o
obj-$(CONFIG_FXOS8700_TRIGGER) += fxos8700_trigger.o
