set(RX130_REVISIONS "512kb" "128kb")
if (NOT DEFINED BOARD_REVISION)
  set(BOARD_REVISION "RX130_REVISIONS")
else()
  if (NOT BOARD_REVISION IN_LIST RX130_REVISIONS)
    message(FATAL_ERROR "${BOARD_REVISION} is not a valid revision for rsk_rx130. Accepted revisions: ${RX130_REVISIONS}")
  endif()
endif()
