ccflags-y += -I${ZEPHYR_BASE}/net/ip/contiki
ccflags-y += -I${ZEPHYR_BASE}/net/ip/contiki/os/lib
ccflags-y += -I${ZEPHYR_BASE}/net/ip/contiki/os
ccflags-y += -I${ZEPHYR_BASE}/net/ip

obj-y = network.o
