/*
 * Copyright (c) 2026 Embracecactus
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_BEKEN_BK7258_CLOCK_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_BEKEN_BK7258_CLOCK_H_

#define BK7258_CLK_UART1 0

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_BEKEN_BK7258_CLOCK_H_ */
