/*
 * Copyright (c) 2025 MASSDRIVER EI (massdriver.space)
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_BFLB_BL70X_CLOCK_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_BFLB_BL70X_CLOCK_H_

#include "bflb_clock_common.h"

#define BL70X_CLKID_CLK_ROOT    BFLB_CLKID_CLK_ROOT
#define BL70X_CLKID_CLK_RC32M   BFLB_CLKID_CLK_RC32M
#define BL70X_CLKID_CLK_CRYSTAL BFLB_CLKID_CLK_CRYSTAL
#define BL70X_CLKID_CLK_BCLK    BFLB_CLKID_CLK_BCLK
#define BL70X_CLKID_CLK_DLL     4

#define BL70X_DLL_57MHz		0
#define BL70X_DLL_96MHz		1
#define BL70X_DLL_144MHz	2
#define BL70X_DLL_120MHz	3

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_BFLB_BL70X_CLOCK_H_ */
