/*
 * Copyright (c) 2025 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_NRFS_AUDIOPLL_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_NRFS_AUDIOPLL_H_

#define NRFS_AUDIOPLL_FREQ_MIN        10666707
#define NRFS_AUDIOPLL_FREQ_AUDIO_44K1 11289591
#define NRFS_AUDIOPLL_FREQ_AUDIO_48K  12287963
#define NRFS_AUDIOPLL_FREQ_MAX        13333292

#endif /* #define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_NRFS_AUDIOPLL_H_ */
