/*
 * Copyright 2026 Silicon Laboratories Inc.
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

#include <zephyr/devicetree.h>

#if defined(CONFIG_SILABS_SISDK_SLEEPTIMER)
#define SL_CATALOG_SLEEPTIMER_PRESENT 1
#endif

#if defined(CONFIG_SILABS_SISDK_CLOCK_MANAGER)
#define SL_CATALOG_CLOCK_MANAGER_PRESENT 1

#if DT_NODE_EXISTS(DT_NODELABEL(extmem)) && DT_NODE_HAS_PROP(DT_NODELABEL(extmem), clock_frequency)
#define SL_CATALOG_CLOCK_MANAGER_EXT_FLASH_PRESENT 1
#endif
#endif /* CONFIG_SILABS_SISDK_CLOCK_MANAGER */

#if defined(CONFIG_SILABS_SISDK_POWER_MANAGER)
#define SL_CATALOG_POWER_MANAGER_PRESENT 1

#if defined(CONFIG_SILABS_SISDK_RTCC)
#define SL_CATALOG_POWER_MANAGER_DEEPSLEEP_BLOCKING_HFXO_RESTORE_PRESENT 1
#endif

#if defined(CONFIG_SOC_FAMILY_SILABS_S3_SIX301)
#define SL_CATALOG_POWER_MANAGER_NO_DEEPSLEEP_PRESENT 1
#endif
#endif /* CONFIG_SILABS_SISDK_POWER_MANAGER */

#if defined(CONFIG_SILABS_SISDK_HFXO_MANAGER)
#define SL_CATALOG_HFXO_MANAGER_PRESENT 1
#endif

#if defined(CONFIG_SILABS_SISDK_GPIO)
#define SL_CATALOG_GPIO_PRESENT 1
#endif

#if defined(CONFIG_SILABS_SISDK_I2C)
#if defined(CONFIG_SOC_FAMILY_SILABS_S3)
#define SL_CATALOG_I2C_FIFO_PRESENT 1
#endif
#endif /* CONFIG_SILABS_SISDK_I2C */

#if defined(CONFIG_SOC_VENDOR_SILABS_HAS_RADIO)
#define SL_CATALOG_SL_RAIL_UTIL_RF_PATH_SWITCH_PRESENT 1
#endif

#endif /* SL_COMPONENT_CATALOG_H */
