/*
 * Copyright 2023-2024 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_NXP_ENET_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_NXP_ENET_H_

#define NXP_ENET_MII_MODE	0
#define NXP_ENET_RMII_MODE	1
#define NXP_ENET_RGMII_MODE	2
#define NXP_ENET_INVALID_MII_MODE 100

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_NXP_ENET_H_ */
