/*
 * Copyright (c) 2025 Silicon Laboratories Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * This file was generated by the script gen_acmp.py in the hal_silabs module.
 * Do not manually edit.
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_COMPARATOR_SILABS_ACMP_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_COMPARATOR_SILABS_ACMP_H_

/* ACMP Input Aliases */
#define ACMP_INPUT_VDACOUT0 ACMP_INPUT_VDAC0OUT0
#define ACMP_INPUT_VDACOUT1 ACMP_INPUT_VDAC0OUT1

/* ACMP Input Definitions */
#define ACMP_INPUT_VSS               0x0
#define ACMP_INPUT_VREFDIVAVDD       0x10
#define ACMP_INPUT_VREFDIVAVDDLP     0x11
#define ACMP_INPUT_VREFDIV1V25       0x12
#define ACMP_INPUT_VREFDIV1V25LP     0x13
#define ACMP_INPUT_VREFDIV2V5        0x14
#define ACMP_INPUT_VREFDIV2V5LP      0x15
#define ACMP_INPUT_VSENSE01DIV4      0x20
#define ACMP_INPUT_VSENSE01DIV4LP    0x21
#define ACMP_INPUT_VSENSE11DIV4      0x22
#define ACMP_INPUT_VSENSE11DIV4LP    0x23
#define ACMP_INPUT_CAPSENSE          0x30
#define ACMP_INPUT_VDAC0OUT0         0x40
#define ACMP_INPUT_VDAC0OUT1         0x41
#define ACMP_INPUT_VDAC1OUT0         0x42
#define ACMP_INPUT_VDAC1OUT1         0x43
#define ACMP_INPUT_EXTPA             0x50
#define ACMP_INPUT_EXTPB             0x51
#define ACMP_INPUT_EXTPC             0x52
#define ACMP_INPUT_EXTPD             0x53
#define ACMP_INPUT_PA0               0x80
#define ACMP_INPUT_PA1               0x81
#define ACMP_INPUT_PA2               0x82
#define ACMP_INPUT_PA3               0x83
#define ACMP_INPUT_PA4               0x84
#define ACMP_INPUT_PA5               0x85
#define ACMP_INPUT_PA6               0x86
#define ACMP_INPUT_PA7               0x87
#define ACMP_INPUT_PA8               0x88
#define ACMP_INPUT_PA9               0x89
#define ACMP_INPUT_PA10              0x8a
#define ACMP_INPUT_PA11              0x8b
#define ACMP_INPUT_PA12              0x8c
#define ACMP_INPUT_PA13              0x8d
#define ACMP_INPUT_PA14              0x8e
#define ACMP_INPUT_PA15              0x8f
#define ACMP_INPUT_PB0               0x90
#define ACMP_INPUT_PB1               0x91
#define ACMP_INPUT_PB2               0x92
#define ACMP_INPUT_PB3               0x93
#define ACMP_INPUT_PB4               0x94
#define ACMP_INPUT_PB5               0x95
#define ACMP_INPUT_PB6               0x96
#define ACMP_INPUT_PB7               0x97
#define ACMP_INPUT_PB8               0x98
#define ACMP_INPUT_PB9               0x99
#define ACMP_INPUT_PB10              0x9a
#define ACMP_INPUT_PB11              0x9b
#define ACMP_INPUT_PB12              0x9c
#define ACMP_INPUT_PB13              0x9d
#define ACMP_INPUT_PB14              0x9e
#define ACMP_INPUT_PB15              0x9f
#define ACMP_INPUT_PC0               0xa0
#define ACMP_INPUT_PC1               0xa1
#define ACMP_INPUT_PC2               0xa2
#define ACMP_INPUT_PC3               0xa3
#define ACMP_INPUT_PC4               0xa4
#define ACMP_INPUT_PC5               0xa5
#define ACMP_INPUT_PC6               0xa6
#define ACMP_INPUT_PC7               0xa7
#define ACMP_INPUT_PC8               0xa8
#define ACMP_INPUT_PC9               0xa9
#define ACMP_INPUT_PC10              0xaa
#define ACMP_INPUT_PC11              0xab
#define ACMP_INPUT_PC12              0xac
#define ACMP_INPUT_PC13              0xad
#define ACMP_INPUT_PC14              0xae
#define ACMP_INPUT_PC15              0xaf
#define ACMP_INPUT_PD0               0xb0
#define ACMP_INPUT_PD1               0xb1
#define ACMP_INPUT_PD2               0xb2
#define ACMP_INPUT_PD3               0xb3
#define ACMP_INPUT_PD4               0xb4
#define ACMP_INPUT_PD5               0xb5
#define ACMP_INPUT_PD6               0xb6
#define ACMP_INPUT_PD7               0xb7
#define ACMP_INPUT_PD8               0xb8
#define ACMP_INPUT_PD9               0xb9
#define ACMP_INPUT_PD10              0xba
#define ACMP_INPUT_PD11              0xbb
#define ACMP_INPUT_PD12              0xbc
#define ACMP_INPUT_PD13              0xbd
#define ACMP_INPUT_PD14              0xbe
#define ACMP_INPUT_PD15              0xbf

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_COMPARATOR_SILABS_ACMP_H_ */
