ccflags-$(CONFIG_CRYPTO_TINYCRYPT_SHIM) += -I${srctree}/ext/lib/crypto/tinycrypt/include

obj-$(CONFIG_CRYPTO_TINYCRYPT_SHIM) += crypto_tc_shim.o
obj-$(CONFIG_CRYPTO_ATAES132A) += crypto_ataes132a.o
obj-$(CONFIG_CRYPTO_MBEDTLS_SHIM) += crypto_mtls_shim.o
obj-$(CONFIG_CRYPTO_TINYCRYPT_RDA5981A) += crypto_aes_rda5981a.o
