set (CMAKE_SYSTEM_NAME      "Linux")
set (CMAKE_C_COMPILER       "${CROSS_PREFIX}gcc")
set (CMAKE_CXX_COMPILER     "${CROSS_PREFIX}g++")

set (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM	NEVER)
set (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY	NEVER)
set (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE	NEVER)

# vim: expandtab:ts=2:sw=2:smartindent
