/*
 * Copyright (c) 2019 Foundries.io
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __INC_BOARD_H
#define __INC_BOARD_H

/* SKYWORKS SKY13351 antenna selection settings */
#define SKY_UFLn_GPIO_NAME	DT_INST_0_SKYWORKS_SKY13351_VCTL1_GPIOS_CONTROLLER
#define SKY_UFLn_GPIO_FLAGS	DT_INST_0_SKYWORKS_SKY13351_VCTL1_GPIOS_FLAGS
#define SKY_UFLn_GPIO_PIN	DT_INST_0_SKYWORKS_SKY13351_VCTL1_GPIOS_PIN
#define SKY_PCBn_GPIO_NAME	DT_INST_0_SKYWORKS_SKY13351_VCTL2_GPIOS_CONTROLLER
#define SKY_PCBn_GPIO_FLAGS	DT_INST_0_SKYWORKS_SKY13351_VCTL2_GPIOS_FLAGS
#define SKY_PCBn_GPIO_PIN	DT_INST_0_SKYWORKS_SKY13351_VCTL2_GPIOS_PIN

#endif /* __INC_BOARD_H */
