/*
 * Copyright (c) 2016 Open-RnD Sp. z o.o.
 * Copyright (c) 2016 BayLibre, SAS
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef _STM32L4X_SOC_PINMUX_H_
#define _STM32L4X_SOC_PINMUX_H_

/* IO pin functions */
enum stm32l4x_pin_config_mode {
	STM32L4X_PIN_CONFIG_BIAS_HIGH_IMPEDANCE = 0,
	STM32L4X_PIN_CONFIG_BIAS_PULL_UP,
	STM32L4X_PIN_CONFIG_BIAS_PULL_DOWN,
	STM32L4X_PIN_CONFIG_ANALOG,
	STM32L4X_PIN_CONFIG_OPEN_DRAIN,
	STM32L4X_PIN_CONFIG_OPEN_DRAIN_PULL_UP,
	STM32L4X_PIN_CONFIG_OPEN_DRAIN_PULL_DOWN,
	STM32L4X_PIN_CONFIG_PUSH_PULL,
	STM32L4X_PIN_CONFIG_PUSH_PULL_PULL_UP,
	STM32L4X_PIN_CONFIG_PUSH_PULL_PULL_DOWN,
};

#endif /* _STM32L4X_SOC_PINMUX_H_ */
