/* SPDX-License-Identifier: Apache-2.0 */

#include <zephyr/linker/common-rom/common-rom-kernel-devices.ld>

#include <zephyr/linker/common-rom/common-rom-ztest.ld>

#include <zephyr/linker/common-rom/common-rom-cpp.ld>

#include <zephyr/linker/common-rom/common-rom-net.ld>

#include <zephyr/linker/common-rom/common-rom-bt.ld>

#include <zephyr/linker/common-rom/common-rom-logging.ld>

#include <zephyr/linker/common-rom/common-rom-debug.ld>

#include <zephyr/linker/common-rom/common-rom-misc.ld>
