obj-$(CONFIG_ENTROPY_MCUX_RNGA) += entropy_mcux_rnga.o
obj-$(CONFIG_ENTROPY_MCUX_TRNG) += entropy_mcux_trng.o
obj-$(CONFIG_ENTROPY_STM32_RNG) += entropy_stm32.o
obj-$(CONFIG_ENTROPY_ESP32_RNG) += entropy_esp32.o
obj-$(CONFIG_USERSPACE) += entropy_handlers.o
