# SPDX-License-Identifier: Apache-2.0

set_ifndef(GNUARC_TOOLCHAIN_PATH "$ENV{GNUARC_TOOLCHAIN_PATH}")
set(GNUARC_TOOLCHAIN_PATH ${GNUARC_TOOLCHAIN_PATH} CACHE PATH "GNUARC install directory")
assert(GNUARC_TOOLCHAIN_PATH "GNUARC_TOOLCHAIN_PATH is not set")

if(NOT EXISTS ${GNUARC_TOOLCHAIN_PATH})
  message(FATAL_ERROR "Nothing found at GNUARC_TOOLCHAIN_PATH: '${GNUARC_TOOLCHAIN_PATH}'")
endif()

set(TOOLCHAIN_HOME ${GNUARC_TOOLCHAIN_PATH})

set(COMPILER gcc)
set(LINKER ld)
set(BINTOOLS gnu)

set(CROSS_COMPILE_TARGET arc-elf32)
set(SYSROOT_TARGET       arc-elf32)

set(CROSS_COMPILE ${TOOLCHAIN_HOME}/bin/${CROSS_COMPILE_TARGET}-)
set(SYSROOT_DIR   ${TOOLCHAIN_HOME}/${SYSROOT_TARGET})
set(TOOLCHAIN_HAS_NEWLIB ON CACHE BOOL "True if toolchain supports newlib")
set_ifndef(OPENOCD_DEFAULT_PATH ${TOOLCHAIN_HOME}/share/openocd/scripts)

message(STATUS "Found toolchain: GNUARC (${GNUARC_TOOLCHAIN_PATH})")
