/* SPDX-License-Identifier: Apache-2.0 */

#if defined(CONFIG_HAS_DTS_I2C)

#if !DT_NODE_HAS_PROP(DT_INST(0, adi_adt7420), label)
#define DT_INST_0_ADI_ADT7420_LABEL ""
#define DT_INST_0_ADI_ADT7420_BASE_ADDRESS 0
#define DT_INST_0_ADI_ADT7420_BUS_NAME ""
#define DT_INST_0_ADI_ADT7420_INT_GPIOS_CONTROLLER ""
#define DT_INST_0_ADI_ADT7420_INT_GPIOS_FLAGS 0
#define DT_INST_0_ADI_ADT7420_INT_GPIOS_PIN 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, adi_adxl362), label)
#define DT_INST_0_ADI_ADXL362_LABEL ""
#define DT_INST_0_ADI_ADXL362_BUS_NAME ""
#define DT_INST_0_ADI_ADXL362_BASE_ADDRESS 0
#define DT_INST_0_ADI_ADXL362_INT1_GPIOS_CONTROLLER ""
#define DT_INST_0_ADI_ADXL362_INT1_GPIOS_FLAGS 0
#define DT_INST_0_ADI_ADXL362_INT1_GPIOS_PIN 0
#define DT_INST_0_ADI_ADXL362_CS_GPIOS_CONTROLLER 0
#define DT_INST_0_ADI_ADXL362_CS_GPIOS_FLAGS 0
#define DT_INST_0_ADI_ADXL362_CS_GPIOS_PIN 0
#define DT_INST_0_ADI_ADXL362_SPI_MAX_FREQUENCY 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, adi_adxl372), label)
#define DT_INST_0_ADI_ADXL372_LABEL ""
#define DT_INST_0_ADI_ADXL372_BUS_NAME ""
#define DT_INST_0_ADI_ADXL372_BASE_ADDRESS 0
#define DT_INST_0_ADI_ADXL372_INT1_GPIOS_CONTROLLER ""
#define DT_INST_0_ADI_ADXL372_INT1_GPIOS_FLAGS 0
#define DT_INST_0_ADI_ADXL372_INT1_GPIOS_PIN 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, avago_apds9960), label)
#define DT_INST_0_AVAGO_APDS9960_LABEL ""
#define DT_INST_0_AVAGO_APDS9960_BUS_NAME ""
#define DT_INST_0_AVAGO_APDS9960_BASE_ADDRESS 0
#define DT_INST_0_AVAGO_APDS9960_INT_GPIOS_CONTROLLER ""
#define DT_INST_0_AVAGO_APDS9960_INT_GPIOS_FLAGS 0
#define DT_INST_0_AVAGO_APDS9960_INT_GPIOS_PIN 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, bosch_bma280), label)
#define DT_INST_0_BOSCH_BMA280_LABEL ""
#define DT_INST_0_BOSCH_BMA280_BASE_ADDRESS 0
#define DT_INST_0_BOSCH_BMA280_BUS_NAME ""
#define DT_INST_0_BOSCH_BMA280_IS_BMC150 0
#define DT_INST_0_BOSCH_BMA280_INT1_GPIOS_CONTROLLER ""
#define DT_INST_0_BOSCH_BMA280_INT1_GPIOS_FLAGS 0
#define DT_INST_0_BOSCH_BMA280_INT1_GPIOS_PIN 0
#define DT_BOSCH_BMA280_BUS_I2C 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, bosch_bme280), label)
#define DT_INST_0_BOSCH_BME280_LABEL ""
#define DT_INST_0_BOSCH_BME280_BASE_ADDRESS 0
#define DT_INST_0_BOSCH_BME280_BUS_NAME ""
#define DT_BOSCH_BME280_BUS_I2C 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, bosch_bme680), label)
#define DT_INST_0_BOSCH_BME680_LABEL ""
#define DT_INST_0_BOSCH_BME680_BASE_ADDRESS 0
#define DT_INST_0_BOSCH_BME680_BUS_NAME ""
#define DT_BOSCH_BME680_BUS_I2C 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, ams_ccs811), label)
#define DT_INST_0_AMS_CCS811_LABEL ""
#define DT_INST_0_AMS_CCS811_BUS_NAME ""
#define DT_INST_0_AMS_CCS811_BASE_ADDRESS 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, aosong_dht), label)
#define DT_INST_0_AOSONG_DHT_LABEL ""
#define DT_INST_0_AOSONG_DHT_DIO_GPIOS_CONTROLLER ""
#define DT_INST_0_AOSONG_DHT_DIO_GPIOS_PIN 0
#define DT_INST_0_AOSONG_DHT_DIO_GPIOS_FLAGS 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, nxp_fxas21002), label)
#define DT_INST_0_NXP_FXAS21002_LABEL ""
#define DT_INST_0_NXP_FXAS21002_BASE_ADDRESS 0
#define DT_INST_0_NXP_FXAS21002_BUS_NAME ""
#define DT_INST_0_NXP_FXAS21002_INT2_GPIOS_CONTROLLER ""
#define DT_INST_0_NXP_FXAS21002_INT2_GPIOS_FLAGS 0
#define DT_INST_0_NXP_FXAS21002_INT2_GPIOS_PIN 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, nxp_fxos8700), label)
#define DT_INST_0_NXP_FXOS8700_LABEL ""
#define DT_INST_0_NXP_FXOS8700_BASE_ADDRESS 0
#define DT_INST_0_NXP_FXOS8700_BUS_NAME ""
#define DT_INST_0_NXP_FXOS8700_INT1_GPIOS_CONTROLLER ""
#define DT_INST_0_NXP_FXOS8700_INT1_GPIOS_FLAGS 0
#define DT_INST_0_NXP_FXOS8700_INT1_GPIOS_PIN 0
#define DT_INST_0_NXP_FXOS8700_INT2_GPIOS_CONTROLLER ""
#define DT_INST_0_NXP_FXOS8700_INT2_GPIOS_FLAGS 0
#define DT_INST_0_NXP_FXOS8700_INT2_GPIOS_PIN 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, panasonic_amg88xx), label)
#define DT_INST_0_PANASONIC_AMG88XX_LABEL ""
#define DT_INST_0_PANASONIC_AMG88XX_BUS_NAME ""
#define DT_INST_0_PANASONIC_AMG88XX_BASE_ADDRESS 0
#define DT_INST_0_PANASONIC_AMG88XX_INT_GPIOS_CONTROLLER ""
#define DT_INST_0_PANASONIC_AMG88XX_INT_GPIOS_FLAGS 0
#define DT_INST_0_PANASONIC_AMG88XX_INT_GPIOS_PIN 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_ism330dhcx), label)
#define DT_INST_0_ST_ISM330DHCX_LABEL ""
#define DT_INST_0_ST_ISM330DHCX_BUS_NAME ""
#define DT_INST_0_ST_ISM330DHCX_BASE_ADDRESS 0
#define DT_INST_0_ST_ISM330DHCX_DRDY_GPIOS_FLAGS 0
#define DT_INST_0_ST_ISM330DHCX_DRDY_GPIOS_PIN 0
#define DT_INST_0_ST_ISM330DHCX_DRDY_GPIOS_CONTROLLER ""
#define DT_ST_ISM330DHCX_BUS_I2C 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_hts221), label)
#define DT_INST_0_ST_HTS221_LABEL ""
#define DT_INST_0_ST_HTS221_BUS_NAME ""
#define DT_INST_0_ST_HTS221_BASE_ADDRESS 0
#define DT_INST_0_ST_HTS221_DRDY_GPIOS_FLAGS 0
#define DT_INST_0_ST_HTS221_DRDY_GPIOS_PIN 0
#define DT_INST_0_ST_HTS221_DRDY_GPIOS_CONTROLLER ""
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_iis2dlpc), label)
#define DT_INST_0_ST_IIS2DLPC_LABEL ""
#define DT_INST_0_ST_IIS2DLPC_BUS_NAME ""
#define DT_INST_0_ST_IIS2DLPC_BASE_ADDRESS 0
#define DT_INST_0_ST_IIS2DLPC_DRDY_GPIOS_FLAGS 0
#define DT_INST_0_ST_IIS2DLPC_DRDY_GPIOS_PIN 0
#define DT_INST_0_ST_IIS2DLPC_DRDY_GPIOS_CONTROLLER ""
#define DT_ST_IIS2DLPC_BUS_I2C 1
#endif

#ifndef DT_INST_0_ST_IIS2MDC_LABEL
#define DT_INST_0_ST_IIS2MDC_LABEL ""
#define DT_INST_0_ST_IIS2MDC_BUS_NAME ""
#define DT_INST_0_ST_IIS2MDC_BASE_ADDRESS 0
#define DT_INST_0_ST_IIS2MDC_DRDY_GPIOS_FLAGS 0
#define DT_INST_0_ST_IIS2MDC_DRDY_GPIOS_PIN 0
#define DT_INST_0_ST_IIS2MDC_DRDY_GPIOS_CONTROLLER ""
#define DT_ST_IIS2MDC_BUS_I2C 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lis3mdl_magn), label)
#define DT_INST_0_ST_LIS3MDL_MAGN_LABEL ""
#define DT_INST_0_ST_LIS3MDL_MAGN_BUS_NAME ""
#define DT_INST_0_ST_LIS3MDL_MAGN_BASE_ADDRESS 0x19
#define DT_INST_0_ST_LIS3MDL_MAGN_IRQ_GPIOS_PIN 0
#define DT_INST_0_ST_LIS3MDL_MAGN_IRQ_GPIOS_CONTROLLER ""
#define DT_INST_0_ST_LIS3MDL_MAGN_IRQ_GPIOS_FLAGS 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lps25hb_press), label)
#define DT_INST_0_ST_LPS25HB_PRESS_LABEL ""
#define DT_INST_0_ST_LPS25HB_PRESS_BUS_NAME ""
#define DT_INST_0_ST_LPS25HB_PRESS_BASE_ADDRESS 0x19
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lsm6ds0), label)
#define DT_INST_0_ST_LSM6DS0_LABEL ""
#define DT_INST_0_ST_LSM6DS0_BUS_NAME ""
#define DT_INST_0_ST_LSM6DS0_BASE_ADDRESS 0x19
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, max_max30101), label)
#define DT_INST_0_MAX_MAX30101_BUS_NAME ""
#define DT_INST_0_MAX_MAX30101_LABEL ""
#define DT_INST_0_MAX_MAX30101_BASE_ADDRESS 0x57
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, semtech_sx1509b), label)
#define DT_INST_0_SEMTECH_SX1509B_LABEL ""
#define DT_INST_0_SEMTECH_SX1509B_BASE_ADDRESS 0
#define DT_INST_0_SEMTECH_SX1509B_BUS_NAME ""
#define DT_INST_0_SEMTECH_SX1509B_INIT_OUT_LOW 0
#define DT_INST_0_SEMTECH_SX1509B_INIT_OUT_HIGH 0
#define DT_INST_0_SEMTECH_SX1509B_NGPIOS 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lsm6dsl), label)
#define DT_INST_0_ST_LSM6DSL_LABEL ""
#define DT_INST_0_ST_LSM6DSL_BASE_ADDRESS 0x6a
#define DT_INST_0_ST_LSM6DSL_BUS_NAME	""
#define DT_INST_0_ST_LSM6DSL_IRQ_GPIOS_CONTROLLER	""
#define DT_INST_0_ST_LSM6DSL_IRQ_GPIOS_FLAGS	0
#define DT_INST_0_ST_LSM6DSL_IRQ_GPIOS_PIN	0
#define DT_ST_LSM6DSL_BUS_I2C 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lsm6dso), label)
#define DT_INST_0_ST_LSM6DSO_LABEL ""
#define DT_INST_0_ST_LSM6DSO_BASE_ADDRESS 0x6a
#define DT_INST_0_ST_LSM6DSO_BUS_NAME	""
#define DT_INST_0_ST_LSM6DSO_IRQ_GPIOS_CONTROLLER	""
#define DT_INST_0_ST_LSM6DSO_IRQ_GPIOS_FLAGS	0
#define DT_INST_0_ST_LSM6DSO_IRQ_GPIOS_PIN	0
#define DT_ST_LSM6DSO_BUS_I2C 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lps22hb_press), label)
#define DT_INST_0_ST_LPS22HB_PRESS_LABEL ""
#define DT_INST_0_ST_LPS22HB_PRESS_BASE_ADDRESS 0
#define DT_INST_0_ST_LPS22HB_PRESS_BUS_NAME ""
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_vl53l0x), label)
#define DT_INST_0_ST_VL53L0X_LABEL ""
#define DT_INST_0_ST_VL53L0X_BASE_ADDRESS 0
#define DT_INST_0_ST_VL53L0X_BUS_NAME ""
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lsm303dlhc_magn), label)
#define DT_INST_0_ST_LSM303DLHC_MAGN_LABEL ""
#define DT_INST_0_ST_LSM303DLHC_MAGN_BUS_NAME ""
#define DT_INST_0_ST_LSM303DLHC_MAGN_BASE_ADDRESS 0x1e
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lis2dh), label)
#define DT_INST_0_ST_LIS2DH_LABEL ""
#define DT_INST_0_ST_LIS2DH_BASE_ADDRESS 0x19
#define DT_INST_0_ST_LIS2DH_BUS_NAME	""
#define DT_INST_0_ST_LIS2DH_IRQ_GPIOS_CONTROLLER	""
#define DT_INST_0_ST_LIS2DH_IRQ_GPIOS_FLAGS	0
#define DT_INST_0_ST_LIS2DH_IRQ_GPIOS_PIN	0
#define DT_ST_LIS2DH_BUS_I2C 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, sensirion_sht3xd), label)
#define DT_INST_0_SENSIRION_SHT3XD_LABEL ""
#define DT_INST_0_SENSIRION_SHT3XD_ALERT_GPIOS_CONTROLLER ""
#define DT_INST_0_SENSIRION_SHT3XD_ALERT_GPIOS_FLAGS 0
#define DT_INST_0_SENSIRION_SHT3XD_ALERT_GPIOS_PIN 0
#define DT_INST_0_SENSIRION_SHT3XD_BASE_ADDRESS 0x44
#define DT_INST_0_SENSIRION_SHT3XD_BUS_NAME ""
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, silabs_si7006), label)
#define DT_INST_0_SILABS_SI7006_LABEL ""
#define DT_INST_0_SILABS_SI7006_BASE_ADDRESS 0x40
#define DT_INST_0_SILABS_SI7006_BUS_NAME	""
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, silabs_si7060), label)
#define DT_INST_0_SILABS_SI7060_LABEL ""
#define DT_INST_0_SILABS_SI7060_BASE_ADDRESS 0x00
#define DT_INST_0_SILABS_SI7060_BUS_NAME	""
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lis2ds12), label)
#define DT_INST_0_ST_LIS2DS12_LABEL ""
#define DT_INST_0_ST_LIS2DS12_BUS_NAME ""
#define DT_INST_0_ST_LIS2DS12_BASE_ADDRESS 0x19
#define DT_INST_0_ST_LIS2DS12_IRQ_GPIOS_CONTROLLER ""
#define DT_INST_0_ST_LIS2DS12_IRQ_GPIOS_FLAGS 0
#define DT_INST_0_ST_LIS2DS12_IRQ_GPIOS_PIN 0
#define DT_ST_LIS2DS12_BUS_I2C 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lis2mdl), label)
#define DT_INST_0_ST_LIS2MDL_LABEL ""
#define DT_INST_0_ST_LIS2MDL_BUS_NAME ""
#define DT_INST_0_ST_LIS2MDL_BASE_ADDRESS 0x19
#define DT_INST_0_ST_LIS2MDL_IRQ_GPIOS_CONTROLLER ""
#define DT_INST_0_ST_LIS2MDL_IRQ_GPIOS_FLAGS 0
#define DT_INST_0_ST_LIS2MDL_IRQ_GPIOS_PIN 0
#define DT_ST_LIS2MDL_BUS_I2C 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lis2dw12), label)
#define DT_INST_0_ST_LIS2DW12_LABEL ""
#define DT_INST_0_ST_LIS2DW12_BUS_NAME ""
#define DT_INST_0_ST_LIS2DW12_BASE_ADDRESS 0x19
#define DT_INST_0_ST_LIS2DW12_IRQ_GPIOS_CONTROLLER ""
#define DT_INST_0_ST_LIS2DW12_IRQ_GPIOS_FLAGS 0
#define DT_INST_0_ST_LIS2DW12_IRQ_GPIOS_PIN 0
#define DT_ST_LIS2DW12_BUS_I2C 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lps22hh), label)
#define DT_INST_0_ST_LPS22HH_LABEL ""
#define DT_INST_0_ST_LPS22HH_BUS_NAME ""
#define DT_INST_0_ST_LPS22HH_BASE_ADDRESS 0x19
#define DT_INST_0_ST_LPS22HH_DRDY_GPIOS_CONTROLLER ""
#define DT_INST_0_ST_LPS22HH_DRDY_GPIOS_FLAGS 0
#define DT_INST_0_ST_LPS22HH_DRDY_GPIOS_PIN 0
#define DT_ST_LPS22HH_BUS_I2C 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lsm9ds0_mfd), label)
#define DT_INST_0_ST_LSM9DS0_MFD_LABEL ""
#define DT_INST_0_ST_LSM9DS0_MFD_BUS_NAME ""
#define DT_INST_0_ST_LSM9DS0_MFD_BASE_ADDRESS 0x1d
#define DT_LSM9DS0_MFD_I2C_MASTER_DEV_NAME ""
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lsm9ds0_gyro), label)
#define DT_INST_0_ST_LSM9DS0_GYRO_LABEL ""
#define DT_INST_0_ST_LSM9DS0_GYRO_BUS_NAME ""
#define DT_INST_0_ST_LSM9DS0_GYRO_BASE_ADDRESS 0x1d
#define DT_INST_0_ST_LSM9DS0_GYRO_IRQ_GPIOS_CONTROLLER ""
#define DT_INST_0_ST_LSM9DS0_GYRO_IRQ_GPIOS_PIN 1
#define DT_INST_0_ST_LSM9DS0_GYRO_IRQ_GPIOS_FLAGS 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_stts751), label)
#define DT_INST_0_ST_STTS751_LABEL ""
#define DT_INST_0_ST_STTS751_BUS_NAME ""
#define DT_INST_0_ST_STTS751_BASE_ADDRESS 0x19
#define DT_INST_0_ST_STTS751_DRDY_GPIOS_CONTROLLER ""
#define DT_INST_0_ST_STTS751_DRDY_GPIOS_FLAGS 0
#define DT_INST_0_ST_STTS751_DRDY_GPIOS_PIN 0
#define DT_ST_STTS751_BUS_I2C 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, ams_iaqcore), label)
#define DT_INST_0_AMS_IAQCORE_LABEL        ""
#define DT_INST_0_AMS_IAQCORE_BUS_NAME     ""
#define DT_INST_0_AMS_IAQCORE_BASE_ADDRESS 0x00
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, ams_ens210), label)
#define DT_INST_0_AMS_ENS210_LABEL         ""
#define DT_INST_0_AMS_ENS210_BUS_NAME      ""
#define DT_INST_0_AMS_ENS210_BASE_ADDRESS  0x00
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, ti_hdc), label)
#define DT_INST_0_TI_HDC_LABEL ""
#define DT_INST_0_TI_HDC_BUS_NAME ""
#define DT_INST_0_TI_HDC_BASE_ADDRESS 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, ti_opt3001), label)
#define DT_INST_0_TI_OPT3001_LABEL ""
#define DT_INST_0_TI_OPT3001_BASE_ADDRESS 0x00
#define DT_INST_0_TI_OPT3001_BUS_NAME	""
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, ti_tmp116), label)
#define DT_INST_0_TI_TMP116_LABEL ""
#define DT_INST_0_TI_TMP116_BASE_ADDRESS 0
#define DT_INST_0_TI_TMP116_BUS_NAME ""
#define DT_TI_TMP116_BUS_I2C 1
#endif

#if !DT_HAS_NODE(DT_INST(0, atmel_at24))
#define DT_INST_0_ATMEL_AT24 1
#define DT_INST_0_ATMEL_AT24_LABEL ""
#define DT_INST_0_ATMEL_AT24_BUS_NAME ""
#define DT_INST_0_ATMEL_AT24_BASE_ADDRESS 0
#define DT_INST_0_ATMEL_AT24_WP_GPIOS_CONTROLLER ""
#define DT_INST_0_ATMEL_AT24_WP_GPIOS_PIN 0
#define DT_INST_0_ATMEL_AT24_WP_GPIOS_FLAGS 0
#define DT_INST_0_ATMEL_AT24_SIZE 32768
#define DT_INST_0_ATMEL_AT24_PAGESIZE 64
#define DT_INST_0_ATMEL_AT24_ADDRESS_WIDTH 16
#define DT_INST_0_ATMEL_AT24_READ_ONLY 0
#define DT_INST_0_ATMEL_AT24_TIMEOUT 5
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, hoperf_th02), label)
#define DT_INST_0_HOPERF_TH02_LABEL ""
#define DT_INST_0_HOPERF_TH02_BUS_NAME ""
#define DT_INST_0_HOPERF_TH02_BASE_ADDRESS 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, ti_tmp112), label)
#define DT_INST_0_TI_TMP112_LABEL ""
#define DT_INST_0_TI_TMP112_BASE_ADDRESS 0
#define DT_INST_0_TI_TMP112_BUS_NAME ""
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, ti_tmp007), label)
#define DT_INST_0_TI_TMP007_LABEL ""
#define DT_INST_0_TI_TMP007_BASE_ADDRESS 0
#define DT_INST_0_TI_TMP007_BUS_NAME ""
#define DT_INST_0_TI_TMP007_INT_GPIOS_CONTROLLER ""
#define DT_INST_0_TI_TMP007_INT_GPIOS_FLAGS 0
#define DT_INST_0_TI_TMP007_INT_GPIOS_PIN 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, semtech_sx9500), label)
#define DT_INST_0_SEMTECH_SX9500_LABEL ""
#define DT_INST_0_SEMTECH_SX9500_BASE_ADDRESS 0
#define DT_INST_0_SEMTECH_SX9500_BUS_NAME ""
#define DT_INST_0_SEMTECH_SX9500_INT_GPIOS_CONTROLLER ""
#define DT_INST_0_SEMTECH_SX9500_INT_GPIOS_FLAGS 0
#define DT_INST_0_SEMTECH_SX9500_INT_GPIOS_PIN 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, microchip_mcp9808), label)
#define DT_INST_0_MICROCHIP_MCP9808_LABEL ""
#define DT_INST_0_MICROCHIP_MCP9808_BASE_ADDRESS 0
#define DT_INST_0_MICROCHIP_MCP9808_BUS_NAME ""
#define DT_INST_0_MICROCHIP_MCP9808_INT_GPIOS_CONTROLLER ""
#define DT_INST_0_MICROCHIP_MCP9808_INT_GPIOS_FLAGS 0
#define DT_INST_0_MICROCHIP_MCP9808_INT_GPIOS_PIN 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, maxim_max44009), label)
#define DT_INST_0_MAXIM_MAX44009_LABEL ""
#define DT_INST_0_MAXIM_MAX44009_BASE_ADDRESS 0
#define DT_INST_0_MAXIM_MAX44009_BUS_NAME ""
#define DT_INST_0_MAXIM_MAX44009_INT_GPIOS_CONTROLLER ""
#define DT_INST_0_MAXIM_MAX44009_INT_GPIOS_FLAGS 0
#define DT_INST_0_MAXIM_MAX44009_INT_GPIOS_PIN 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, isil_isl29035), label)
#define DT_INST_0_ISIL_ISL29035_LABEL ""
#define DT_INST_0_ISIL_ISL29035_BASE_ADDRESS 0
#define DT_INST_0_ISIL_ISL29035_BUS_NAME ""
#define DT_INST_0_ISIL_ISL29035_INT_GPIOS_CONTROLLER ""
#define DT_INST_0_ISIL_ISL29035_INT_GPIOS_FLAGS 0
#define DT_INST_0_ISIL_ISL29035_INT_GPIOS_PIN 0
#endif


#if !DT_NODE_HAS_PROP(DT_INST(0, invensense_mpu6050), label)
#define DT_INST_0_INVENSENSE_MPU6050_LABEL ""
#define DT_INST_0_INVENSENSE_MPU6050_BASE_ADDRESS 0
#define DT_INST_0_INVENSENSE_MPU6050_BUS_NAME ""
#define DT_INST_0_INVENSENSE_MPU6050_INT_GPIOS_CONTROLLER ""
#define DT_INST_0_INVENSENSE_MPU6050_INT_GPIOS_FLAGS 0
#define DT_INST_0_INVENSENSE_MPU6050_INT_GPIOS_PIN 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, grove_light), label)
#define DT_INST_0_GROVE_LIGHT_LABEL ""
#define DT_INST_0_GROVE_LIGHT_IO_CHANNELS_CONTROLLER ""
#define DT_INST_0_GROVE_LIGHT_IO_CHANNELS_INPUT 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, grove_temperature), label)
#define DT_INST_0_GROVE_TEMPERATURE_LABEL ""
#define DT_INST_0_GROVE_TEMPERATURE_IO_CHANNELS_CONTROLLER ""
#define DT_INST_0_GROVE_TEMPERATURE_IO_CHANNELS_INPUT 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, hoperf_hp206c), label)
#define DT_INST_0_HOPERF_HP206C_LABEL ""
#define DT_INST_0_HOPERF_HP206C_BASE_ADDRESS 0
#define DT_INST_0_HOPERF_HP206C_BUS_NAME ""
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, bosch_bmm150), label)
#define DT_INST_0_BOSCH_BMM150_LABEL ""
#define DT_INST_0_BOSCH_BMM150_BASE_ADDRESS 0
#define DT_INST_0_BOSCH_BMM150_BUS_NAME ""
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, bosch_bmg160), label)
#define DT_INST_0_BOSCH_BMG160_LABEL ""
#define DT_INST_0_BOSCH_BMG160_BASE_ADDRESS 0
#define DT_INST_0_BOSCH_BMG160_BUS_NAME ""
#define DT_INST_0_BOSCH_BMG160_INT_GPIOS_CONTROLLER ""
#define DT_INST_0_BOSCH_BMG160_INT_GPIOS_FLAGS 0
#define DT_INST_0_BOSCH_BMG160_INT_GPIOS_PIN 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, bosch_bmc150_magn), label)
#define DT_INST_0_BOSCH_BMC150_MAGN_LABEL ""
#define DT_INST_0_BOSCH_BMC150_MAGN_BASE_ADDRESS 0
#define DT_INST_0_BOSCH_BMC150_MAGN_BUS_NAME ""
#define DT_INST_0_BOSCH_BMC150_MAGN_DRDY_GPIOS_CONTROLLER ""
#define DT_INST_0_BOSCH_BMC150_MAGN_DRDY_GPIOS_FLAGS 0
#define DT_INST_0_BOSCH_BMC150_MAGN_DRDY_GPIOS_PIN 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, honeywell_hmc5883l), label)
#define DT_INST_0_HONEYWELL_HMC5883L_LABEL ""
#define DT_INST_0_HONEYWELL_HMC5883L_BASE_ADDRESS 0
#define DT_INST_0_HONEYWELL_HMC5883L_BUS_NAME ""
#define DT_INST_0_HONEYWELL_HMC5883L_INT_GPIOS_CONTROLLER ""
#define DT_INST_0_HONEYWELL_HMC5883L_INT_GPIOS_FLAGS 0
#define DT_INST_0_HONEYWELL_HMC5883L_INT_GPIOS_PIN 0
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, asahi_kasei_ak8975), label)
#define DT_INST_0_ASAHI_KASEI_AK8975_LABEL ""
#define DT_INST_0_ASAHI_KASEI_AK8975_BASE_ADDRESS 0
#define DT_INST_0_ASAHI_KASEI_AK8975_BUS_NAME ""
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, adi_adxl345), label)
#define DT_INST_0_ADI_ADXL345_LABEL ""
#define DT_INST_0_ADI_ADXL345_BUS_NAME ""
#define DT_INST_0_ADI_ADXL345_BASE_ADDRESS 0
#endif

#endif /* CONFIG_HAS_DTS_I2C */

#ifndef DT_ADXL372_DEV_NAME
#define DT_ADXL372_DEV_NAME ""
#define DT_ADXL372_SPI_DEV_NAME ""
#define DT_ADXL372_SPI_DEV_SLAVE 0
#define DT_ADXL372_SPI_BUS_FREQ 8000000
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, bosch_bmi160), label)
#define DT_INST_0_BOSCH_BMI160_LABEL		""
#define DT_INST_0_BOSCH_BMI160_BASE_ADDRESS		0
#define DT_INST_0_BOSCH_BMI160_BUS_NAME	""
#define DT_INST_0_BOSCH_BMI160_INT_GPIOS_CONTROLLER	""
#define DT_INST_0_BOSCH_BMI160_INT_GPIOS_FLAGS	0
#define DT_INST_0_BOSCH_BMI160_INT_GPIOS_PIN	0
#define DT_INST_0_BOSCH_BMI160_SPI_MAX_FREQUENCY	6400000
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_iis2dlpc), label)
#define DT_INST_0_ST_IIS2DLPC_LABEL ""
#define DT_INST_0_ST_IIS2DLPC_BUS_NAME ""
#define DT_INST_0_ST_IIS2DLPC_SPI_MAX_FREQUENCY 100000
#define DT_INST_0_ST_IIS2DLPC_BASE_ADDRESS 1
#define DT_INST_0_ST_IIS2DLPC_DRDY_GPIOS_CONTROLLER ""
#define DT_INST_0_ST_IIS2DLPC_DRDY_GPIOS_FLAGS 0
#define DT_INST_0_ST_IIS2DLPC_DRDY_GPIOS_PIN 0
#define DT_ST_IIS2DLPC_BUS_SPI 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_ism330dhcx), label)
#define DT_INST_0_ST_ISM330DHCX_LABEL ""
#define DT_INST_0_ST_ISM330DHCX_BUS_NAME ""
#define DT_INST_0_ST_ISM330DHCX_SPI_MAX_FREQUENCY 100000
#define DT_INST_0_ST_ISM330DHCX_BASE_ADDRESS 1
#define DT_INST_0_ST_ISM330DHCX_DRDY_GPIOS_CONTROLLER ""
#define DT_INST_0_ST_ISM330DHCX_DRDY_GPIOS_FLAGS 0
#define DT_INST_0_ST_ISM330DHCX_DRDY_GPIOS_PIN 0
#define DT_ST_ISM330DHCX_BUS_SPI 1
#endif

#ifndef DT_INST_0_ST_IIS2MDC_LABEL
#define DT_INST_0_ST_IIS2MDC_LABEL ""
#define DT_INST_0_ST_IIS2MDC_BUS_NAME ""
#define DT_INST_0_ST_IIS2MDC_SPI_MAX_FREQUENCY 100000
#define DT_INST_0_ST_IIS2MDC_BASE_ADDRESS 1
#define DT_INST_0_ST_IIS2MDC_DRDY_GPIOS_CONTROLLER ""
#define DT_INST_0_ST_IIS2MDC_DRDY_GPIOS_FLAGS 0
#define DT_INST_0_ST_IIS2MDC_DRDY_GPIOS_PIN 0
#define DT_ST_IIS2MDC_BUS_SPI 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_iis3dhhc), label)
#define DT_INST_0_ST_IIS3DHHC_LABEL ""
#define DT_INST_0_ST_IIS3DHHC_BASE_ADDRESS		0
#define DT_INST_0_ST_IIS3DHHC_BUS_NAME	""
#define DT_INST_0_ST_IIS3DHHC_IRQ_GPIOS_CONTROLLER_0	""
#define DT_INST_0_ST_IIS3DHHC_IRQ_GPIOS_PIN_0	0
#define DT_INST_0_ST_IIS3DHHC_IRQ_GPIOS_FLAGS_0	0
#define DT_INST_0_ST_IIS3DHHC_IRQ_GPIOS_CONTROLLER_1	""
#define DT_INST_0_ST_IIS3DHHC_IRQ_GPIOS_PIN_1	0
#define DT_INST_0_ST_IIS3DHHC_IRQ_GPIOS_FLAGS_1	0
#define DT_INST_0_ST_IIS3DHHC_SPI_MAX_FREQUENCY	6400000
#define DT_ST_IIS3DHHC_BUS_SPI 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lis2dh), label)
#define DT_INST_0_ST_LIS2DH_LABEL ""
#define DT_INST_0_ST_LIS2DH_BASE_ADDRESS		0
#define DT_INST_0_ST_LIS2DH_BUS_NAME	""
#define DT_INST_0_ST_LIS2DH_IRQ_GPIOS_CONTROLLER	""
#define DT_INST_0_ST_LIS2DH_IRQ_GPIOS_FLAGS	0
#define DT_INST_0_ST_LIS2DH_IRQ_GPIOS_PIN	0
#define DT_INST_0_ST_LIS2DH_SPI_MAX_FREQUENCY	6400000
#define DT_ST_LIS2DH_BUS_SPI 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lsm6dsl), label)
#define DT_INST_0_ST_LSM6DSL_LABEL ""
#define DT_INST_0_ST_LSM6DSL_BASE_ADDRESS		0
#define DT_INST_0_ST_LSM6DSL_BUS_NAME	""
#define DT_INST_0_ST_LSM6DSL_IRQ_GPIOS_CONTROLLER	""
#define DT_INST_0_ST_LSM6DSL_IRQ_GPIOS_FLAGS	0
#define DT_INST_0_ST_LSM6DSL_IRQ_GPIOS_PIN	0
#define DT_INST_0_ST_LSM6DSL_SPI_MAX_FREQUENCY	6400000
#define DT_ST_LSM6DSL_BUS_SPI 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lsm6dso), label)
#define DT_INST_0_ST_LSM6DSO_LABEL ""
#define DT_INST_0_ST_LSM6DSO_BASE_ADDRESS		0
#define DT_INST_0_ST_LSM6DSO_BUS_NAME	""
#define DT_INST_0_ST_LSM6DSO_IRQ_GPIOS_CONTROLLER	""
#define DT_INST_0_ST_LSM6DSO_IRQ_GPIOS_FLAGS	0
#define DT_INST_0_ST_LSM6DSO_IRQ_GPIOS_PIN	0
#define DT_INST_0_ST_LSM6DSO_SPI_MAX_FREQUENCY	6400000
#define DT_ST_LSM6DSO_BUS_SPI 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lis2ds12), label)
#define DT_INST_0_ST_LIS2DS12_LABEL ""
#define DT_INST_0_ST_LIS2DS12_BUS_NAME ""
#define DT_INST_0_ST_LIS2DS12_SPI_MAX_FREQUENCY 100000
#define DT_INST_0_ST_LIS2DS12_BASE_ADDRESS 1
#define DT_INST_0_ST_LIS2DS12_IRQ_GPIOS_CONTROLLER ""
#define DT_INST_0_ST_LIS2DS12_IRQ_GPIOS_FLAGS 0
#define DT_INST_0_ST_LIS2DS12_IRQ_GPIOS_PIN 0
#define DT_ST_LIS2DS12_BUS_SPI 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lis2dw12), label)
#define DT_INST_0_ST_LIS2DW12_LABEL ""
#define DT_INST_0_ST_LIS2DW12_BUS_NAME ""
#define DT_INST_0_ST_LIS2DW12_SPI_MAX_FREQUENCY 100000
#define DT_INST_0_ST_LIS2DW12_BASE_ADDRESS 1
#define DT_INST_0_ST_LIS2DW12_IRQ_GPIOS_CONTROLLER ""
#define DT_INST_0_ST_LIS2DW12_IRQ_GPIOS_FLAGS 0
#define DT_INST_0_ST_LIS2DW12_IRQ_GPIOS_PIN 0
#define DT_ST_LIS2DW12_BUS_SPI 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lis2mdl), label)
#define DT_INST_0_ST_LIS2MDL_LABEL ""
#define DT_INST_0_ST_LIS2MDL_BUS_NAME ""
#define DT_INST_0_ST_LIS2MDL_SPI_MAX_FREQUENCY 100000
#define DT_INST_0_ST_LIS2MDL_BASE_ADDRESS 1
#define DT_INST_0_ST_LIS2MDL_IRQ_GPIOS_CONTROLLER ""
#define DT_INST_0_ST_LIS2MDL_IRQ_GPIOS_FLAGS 0
#define DT_INST_0_ST_LIS2MDL_IRQ_GPIOS_PIN 0
#define DT_INST_0_ST_LIS2MDL_CS_GPIOS_CONTROLLER 0
#define DT_INST_0_ST_LIS2MDL_CS_GPIOS_FLAGS 0
#define DT_INST_0_ST_LIS2MDL_CS_GPIOS_PIN 0
#define DT_ST_LIS2MDL_BUS_SPI 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, st_lps22hh), label)
#define DT_INST_0_ST_LPS22HH_LABEL ""
#define DT_INST_0_ST_LPS22HH_BUS_NAME ""
#define DT_INST_0_ST_LPS22HH_SPI_MAX_FREQUENCY 100000
#define DT_INST_0_ST_LPS22HH_BASE_ADDRESS 1
#define DT_INST_0_ST_LPS22HH_DRDY_GPIOS_CONTROLLER ""
#define DT_INST_0_ST_LPS22HH_DRDY_GPIOS_FLAGS 0
#define DT_INST_0_ST_LPS22HH_DRDY_GPIOS_PIN 0
#define DT_INST_0_ST_LPS22HH_CS_GPIOS_CONTROLLER 0
#define DT_INST_0_ST_LPS22HH_CS_GPIOS_FLAGS 0
#define DT_INST_0_ST_LPS22HH_CS_GPIOS_PIN 0
#define DT_ST_LPS22HH_BUS_SPI 1
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, microchip_enc28j60), label)
#define DT_INST_0_MICROCHIP_ENC28J60_BASE_ADDRESS		0
#define DT_INST_0_MICROCHIP_ENC28J60_BUS_NAME		""
#define DT_INST_0_MICROCHIP_ENC28J60_INT_GPIOS_CONTROLLER	""
#define DT_INST_0_MICROCHIP_ENC28J60_INT_GPIOS_FLAGS		0
#define DT_INST_0_MICROCHIP_ENC28J60_INT_GPIOS_PIN		0
#define DT_INST_0_MICROCHIP_ENC28J60_LABEL			""
#define DT_INST_0_MICROCHIP_ENC28J60_LOCAL_MAC_ADDRESS	{0, 0, 0, 0, 0, 0}
#define DT_INST_0_MICROCHIP_ENC28J60_SPI_MAX_FREQUENCY	0
#endif

#if !DT_HAS_NODE(DT_INST(0, atmel_at25))
#define DT_INST_0_ATMEL_AT25 1
#define DT_INST_0_ATMEL_AT25_LABEL ""
#define DT_INST_0_ATMEL_AT25_BUS_NAME ""
#define DT_INST_0_ATMEL_AT25_BASE_ADDRESS 0
#define DT_INST_0_ATMEL_AT25_SPI_MAX_FREQUENCY 1000000
#define DT_INST_0_ATMEL_AT25_WP_GPIOS_CONTROLLER ""
#define DT_INST_0_ATMEL_AT25_WP_GPIOS_PIN 0
#define DT_INST_0_ATMEL_AT25_WP_GPIOS_FLAGS 0
#define DT_INST_0_ATMEL_AT25_SIZE 32768
#define DT_INST_0_ATMEL_AT25_PAGESIZE 64
#define DT_INST_0_ATMEL_AT25_ADDRESS_WIDTH 16
#define DT_INST_0_ATMEL_AT25_READ_ONLY 0
#define DT_INST_0_ATMEL_AT25_TIMEOUT 5
#endif

#if !DT_NODE_HAS_PROP(DT_INST(0, meas_ms5607), label)
#define DT_INST_0_MEAS_MS5607_LABEL ""
#define DT_INST_0_MEAS_MS5607_BUS_NAME ""
#define DT_INST_0_MEAS_MS5607_CS_GPIOS_CONTROLLER 0
#define DT_INST_0_MEAS_MS5607_CS_GPIOS_PIN 0
#define DT_INST_0_MEAS_MS5607_BASE_ADDRESS 0
#define DT_INST_0_MEAS_MS5607_SPI_MAX_FREQUENCY 10000
#define DT_MEAS_MS5607_SPI 1
#endif
