ccflags-y += -I${srctree}

obj-$(CONFIG_ETH_SAM_GMAC) += eth_sam_gmac.o phy_sam_gmac.o
obj-$(CONFIG_ETH_DW) += eth_dw.o
obj-$(CONFIG_ETH_ENC28J60) += eth_enc28j60.o
obj-$(CONFIG_ETH_MCUX) += eth_mcux.o
obj-$(CONFIG_ETH_STM32_HAL) += eth_stm32_hal.o

