ccflags-y += -I${srctree}/net/yaip

obj-$(CONFIG_NET_L2_IEEE802154) += ieee802154.o \
					ieee802154_frame.o \

obj-$(CONFIG_NET_L2_IEEE802154_RADIO_ALOHA) += ieee802154_radio_aloha.o

obj-$(CONFIG_NET_L2_IEEE802154_FRAGMENT) += ieee802154_fragment.o
