.. SPDX-License-Identifier: Apache-2.0
..
.. Copyright (c) 2026 Ezurio LLC

.. _Lyra product brief:
   https://www.ezurio.com/documentation/product-brief-lyra-series

.. _Lyra website:
   https://www.ezurio.com/wireless-modules/bluetooth-modules/bluetooth-5-modules/lyra-series-bluetooth-53-modules

.. _EFR32BG22 datasheet:
   https://www.silabs.com/documents/public/data-sheets/efr32bg22-datasheet.pdf

.. _EFR32BG22 reference manual:
   https://www.silabs.com/documents/public/reference-manuals/efr32xg22-rm.pdf

.. _mikroBUS:
   https://www.mikroe.com/mikrobus

.. _Qwiic:
   https://www.sparkfun.com/qwiic

.. _Simplicity Studio:
   https://www.silabs.com/software-and-tools/simplicity-studio
