set(PROJECT_VERSION_TWEAK 0) # CMake would set this variable if it is used in the project statement
math(EXPR ZEPHYR_VERSION_CODE   "(${PROJECT_VERSION_MAJOR} << 16) + (${PROJECT_VERSION_MAJOR} <<  8) + (${PROJECT_VERSION_MAJOR})")
math(EXPR KERNELVERSION         "(${PROJECT_VERSION_MAJOR} << 16) + (${PROJECT_VERSION_MAJOR} <<  8) + (${PROJECT_VERSION_MAJOR})")
math(EXPR KERNEL_VERSION_NUMBER "(${PROJECT_VERSION_MAJOR} << 24) + (${PROJECT_VERSION_MAJOR} << 16) + (${PROJECT_VERSION_MAJOR} << 8) + ${PROJECT_VERSION_TWEAK}")

set(KERNEL_VERSION_MAJOR      ${PROJECT_VERSION_MAJOR})
set(KERNEL_VERSION_MINOR      ${PROJECT_VERSION_MINOR})
set(KERNEL_PATCHLEVEL         ${PROJECT_VERSION_PATCH})
set(KERNEL_VERSION_STRING     "\"${PROJECT_VERSION}\"")
