/*
 * SPDX-FileCopyrightText: Copyright Bavariamatic GmbH
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief Interrupt definitions for the Microchip SmartFusion2 platform.
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_INTERRUPT_CONTROLLER_MICROCHIP_SMARTFUSION2_IRQ_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_INTERRUPT_CONTROLLER_MICROCHIP_SMARTFUSION2_IRQ_H_

#define IRQ_TYPE_NONE                      0
#define IRQ_TYPE_EDGE_RISING               1
#define IRQ_TYPE_EDGE_FALLING              2
#define IRQ_TYPE_EDGE_BOTH                 (IRQ_TYPE_EDGE_FALLING | IRQ_TYPE_EDGE_RISING)
#define IRQ_TYPE_LEVEL_HIGH                4
#define IRQ_TYPE_LEVEL_LOW                 8

#define SMARTFUSION2_IRQ_WDOG_WAKEUP      0
#define SMARTFUSION2_IRQ_RTC_WAKEUP       1
#define SMARTFUSION2_IRQ_SPI0             2
#define SMARTFUSION2_IRQ_SPI1             3
#define SMARTFUSION2_IRQ_I2C0             4
#define SMARTFUSION2_IRQ_I2C1             7
#define SMARTFUSION2_IRQ_UART0            10
#define SMARTFUSION2_IRQ_UART1            11
#define SMARTFUSION2_IRQ_ETHERNET_MAC     12
#define SMARTFUSION2_IRQ_PDMA             13
#define SMARTFUSION2_IRQ_TIMER1           14
#define SMARTFUSION2_IRQ_TIMER2           15
#define SMARTFUSION2_IRQ_CAN              16
#define SMARTFUSION2_IRQ_COMBLK           19
#define SMARTFUSION2_IRQ_USB              20
#define SMARTFUSION2_IRQ_USB_DMA          21
#define SMARTFUSION2_IRQ_PLL_LOCK         22
#define SMARTFUSION2_IRQ_PLL_LOCK_LOST    23
#define SMARTFUSION2_IRQ_COMM_SWITCH_ERR  24
#define SMARTFUSION2_IRQ_CACHE_ERROR      25
#define SMARTFUSION2_IRQ_DDR              26
#define SMARTFUSION2_IRQ_HPDMA_COMPLETE   27
#define SMARTFUSION2_IRQ_HPDMA_ERROR      28
#define SMARTFUSION2_IRQ_ECC_ERROR        29
#define SMARTFUSION2_IRQ_MDDR_IO_CALIB    30
#define SMARTFUSION2_IRQ_FAB_PLL_LOCK     31
#define SMARTFUSION2_IRQ_FAB_PLL_LOCK_LOST 32
#define SMARTFUSION2_IRQ_FIC64            33
#define SMARTFUSION2_IRQ_GPIO0            50

#define M2S_IRQ_WDOG                      SMARTFUSION2_IRQ_WDOG_WAKEUP
#define M2S_IRQ_RTC_WAKEUP                SMARTFUSION2_IRQ_RTC_WAKEUP
#define M2S_IRQ_RTC_MATCH                 SMARTFUSION2_IRQ_RTC_WAKEUP
#define M2S_IRQ_SPI0                      SMARTFUSION2_IRQ_SPI0
#define M2S_IRQ_SPI1                      SMARTFUSION2_IRQ_SPI1
#define M2S_IRQ_I2C0_MAIN                 SMARTFUSION2_IRQ_I2C0
#define M2S_IRQ_I2C0_ALERT                SMARTFUSION2_IRQ_I2C0
#define M2S_IRQ_I2C0_SUS                  SMARTFUSION2_IRQ_I2C0
#define M2S_IRQ_I2C1_MAIN                 SMARTFUSION2_IRQ_I2C1
#define M2S_IRQ_I2C1_ALERT                SMARTFUSION2_IRQ_I2C1
#define M2S_IRQ_I2C1_SUS                  SMARTFUSION2_IRQ_I2C1
#define M2S_IRQ_UART0                     SMARTFUSION2_IRQ_UART0
#define M2S_IRQ_UART1                     SMARTFUSION2_IRQ_UART1
#define M2S_IRQ_MAC0                      SMARTFUSION2_IRQ_ETHERNET_MAC
#define M2S_IRQ_DMA                       SMARTFUSION2_IRQ_PDMA
#define M2S_IRQ_TIMER1                    SMARTFUSION2_IRQ_TIMER1
#define M2S_IRQ_TIMER2                    SMARTFUSION2_IRQ_TIMER2
#define M2S_IRQ_CAN0                      SMARTFUSION2_IRQ_CAN
#define M2S_IRQ_CAN1                      SMARTFUSION2_IRQ_CAN
#define M2S_IRQ_USB_MC                    SMARTFUSION2_IRQ_USB
#define M2S_IRQ_USB_DMA                   SMARTFUSION2_IRQ_USB_DMA
#define M2S_IRQ_GPIO0                     SMARTFUSION2_IRQ_GPIO0

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_INTERRUPT_CONTROLLER_MICROCHIP_SMARTFUSION2_IRQ_H_ */