/*
 * Copyright (c) 2024 Realtek Semiconductor, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_DRIVERS_RESET_RESET_RTS5817_REG_H_
#define ZEPHYR_DRIVERS_RESET_RESET_RTS5817_REG_H_

#define SYSRST_BASE_ADDR 0x0
#define R_SYS_FORCE_RST  (SYSRST_BASE_ADDR + 0X0000)

/* Bits of R_SYS_FORCE_RST (0X0200) */

#define SYS_FORCE_RESET_BUS_OFFSET 0
#define SYS_FORCE_RESET_BUS_BITS   1
#define SYS_FORCE_RESET_BUS_MASK   (((1 << 1) - 1) << 0)
#define SYS_FORCE_RESET_BUS        (SYS_FORCE_RESET_BUS_MASK)

#define SYS_FORCE_RESET_AES_OFFSET 1
#define SYS_FORCE_RESET_AES_BITS   1
#define SYS_FORCE_RESET_AES_MASK   (((1 << 1) - 1) << 1)
#define SYS_FORCE_RESET_AES        (SYS_FORCE_RESET_AES_MASK)

#define SYS_FORCE_RESET_GE_OFFSET 2
#define SYS_FORCE_RESET_GE_BITS   1
#define SYS_FORCE_RESET_GE_MASK   (((1 << 1) - 1) << 2)
#define SYS_FORCE_RESET_GE        (SYS_FORCE_RESET_GE_MASK)

#define SYS_FORCE_RESET_SHA_OFFSET 3
#define SYS_FORCE_RESET_SHA_BITS   1
#define SYS_FORCE_RESET_SHA_MASK   (((1 << 1) - 1) << 3)
#define SYS_FORCE_RESET_SHA        (SYS_FORCE_RESET_SHA_MASK)

#define SYS_FORCE_RESET_SPI_CACHE_OFFSET 4
#define SYS_FORCE_RESET_SPI_CACHE_BITS   1
#define SYS_FORCE_RESET_SPI_CACHE_MASK   (((1 << 1) - 1) << 4)
#define SYS_FORCE_RESET_SPI_CACHE        (SYS_FORCE_RESET_SPI_CACHE_MASK)

#define SYS_FORCE_RESET_SPI_SENSOR_OFFSET 5
#define SYS_FORCE_RESET_SPI_SENSOR_BITS   1
#define SYS_FORCE_RESET_SPI_SENSOR_MASK   (((1 << 1) - 1) << 5)
#define SYS_FORCE_RESET_SPI_SENSOR        (SYS_FORCE_RESET_SPI_SENSOR_MASK)

#define SYS_FORCE_RESET_SPI_SSI_M_OFFSET 6
#define SYS_FORCE_RESET_SPI_SSI_M_BITS   1
#define SYS_FORCE_RESET_SPI_SSI_M_MASK   (((1 << 1) - 1) << 6)
#define SYS_FORCE_RESET_SPI_SSI_M        (SYS_FORCE_RESET_SPI_SSI_M_MASK)

#define SYS_FORCE_RESET_SPI_SSI_S_OFFSET 7
#define SYS_FORCE_RESET_SPI_SSI_S_BITS   1
#define SYS_FORCE_RESET_SPI_SSI_S_MASK   (((1 << 1) - 1) << 7)
#define SYS_FORCE_RESET_SPI_SSI_S        (SYS_FORCE_RESET_SPI_SSI_S_MASK)

#define SYS_FORCE_RESET_PKE_OFFSET 8
#define SYS_FORCE_RESET_PKE_BITS   1
#define SYS_FORCE_RESET_PKE_MASK   (((1 << 1) - 1) << 8)
#define SYS_FORCE_RESET_PKE        (SYS_FORCE_RESET_PKE_MASK)

#define SYS_FORCE_RESET_I2C_OFFSET 9
#define SYS_FORCE_RESET_I2C_BITS   1
#define SYS_FORCE_RESET_I2C_MASK   (((1 << 1) - 1) << 9)
#define SYS_FORCE_RESET_I2C        (SYS_FORCE_RESET_I2C_MASK)

#define SYS_FORCE_RESET_I2C0_OFFSET 10
#define SYS_FORCE_RESET_I2C0_BITS   1
#define SYS_FORCE_RESET_I2C0_MASK   (((1 << 1) - 1) << 10)
#define SYS_FORCE_RESET_I2C0        (SYS_FORCE_RESET_I2C0_MASK)

#define SYS_FORCE_RESET_I2C1_OFFSET 11
#define SYS_FORCE_RESET_I2C1_BITS   1
#define SYS_FORCE_RESET_I2C1_MASK   (((1 << 1) - 1) << 11)
#define SYS_FORCE_RESET_I2C1        (SYS_FORCE_RESET_I2C1_MASK)

#define SYS_FORCE_RESET_TRNG_OFFSET 12
#define SYS_FORCE_RESET_TRNG_BITS   1
#define SYS_FORCE_RESET_TRNG_MASK   (((1 << 1) - 1) << 12)
#define SYS_FORCE_RESET_TRNG        (SYS_FORCE_RESET_TRNG_MASK)

#define SYS_FORCE_RESET_I2C_S_OFFSET 13
#define SYS_FORCE_RESET_I2C_S_BITS   1
#define SYS_FORCE_RESET_I2C_S_MASK   (((1 << 1) - 1) << 13)
#define SYS_FORCE_RESET_I2C_S        (SYS_FORCE_RESET_I2C_S_MASK)

#define SYS_FORCE_RESET_UART0_OFFSET 14
#define SYS_FORCE_RESET_UART0_BITS   1
#define SYS_FORCE_RESET_UART0_MASK   (((1 << 1) - 1) << 14)
#define SYS_FORCE_RESET_UART0        (SYS_FORCE_RESET_UART0_MASK)

#define SYS_FORCE_RESET_UART1_OFFSET 15
#define SYS_FORCE_RESET_UART1_BITS   1
#define SYS_FORCE_RESET_UART1_MASK   (((1 << 1) - 1) << 15)
#define SYS_FORCE_RESET_UART1        (SYS_FORCE_RESET_UART1_MASK)

#define SYS_FORCE_RESET_PUF_OFFSET 16
#define SYS_FORCE_RESET_PUF_BITS   1
#define SYS_FORCE_RESET_PUF_MASK   (((1 << 1) - 1) << 16)
#define SYS_FORCE_RESET_PUF        (SYS_FORCE_RESET_PUF_MASK)

#define SYS_FORCE_RESET_USB2_OFFSET 17
#define SYS_FORCE_RESET_USB2_BITS   1
#define SYS_FORCE_RESET_USB2_MASK   (((1 << 1) - 1) << 17)
#define SYS_FORCE_RESET_USB2        (SYS_FORCE_RESET_USB2_MASK)

#define SYS_FORCE_RESET_CK30M_OFFSET 18
#define SYS_FORCE_RESET_CK30M_BITS   1
#define SYS_FORCE_RESET_CK30M_MASK   (((1 << 1) - 1) << 18)
#define SYS_FORCE_RESET_CK30M        (SYS_FORCE_RESET_CK30M_MASK)

#define SYS_FORCE_RESET_CK60M_OFFSET 19
#define SYS_FORCE_RESET_CK60M_BITS   1
#define SYS_FORCE_RESET_CK60M_MASK   (((1 << 1) - 1) << 19)
#define SYS_FORCE_RESET_CK60M        (SYS_FORCE_RESET_CK60M_MASK)

#define SYS_FORCE_RESET_CK120M_OFFSET 20
#define SYS_FORCE_RESET_CK120M_BITS   1
#define SYS_FORCE_RESET_CK120M_MASK   (((1 << 1) - 1) << 20)
#define SYS_FORCE_RESET_CK120M        (SYS_FORCE_RESET_CK120M_MASK)

#define USB2_PHY_FORCE_RESET_OFFSET 21
#define USB2_PHY_FORCE_RESET_BITS   1
#define USB2_PHY_FORCE_RESET_MASK   (((1 << 1) - 1) << 21)
#define USB2_PHY_FORCE_RESET        (USB2_PHY_FORCE_RESET_MASK)

#define SYS_FORCE_RESET_SYS_OFFSET 22
#define SYS_FORCE_RESET_SYS_BITS   1
#define SYS_FORCE_RESET_SYS_MASK   (((1 << 1) - 1) << 22)
#define SYS_FORCE_RESET_SYS        (SYS_FORCE_RESET_SYS_MASK)

#define SYS_FORCE_RESET_DPHY_OFFSET 23
#define SYS_FORCE_RESET_DPHY_BITS   1
#define SYS_FORCE_RESET_DPHY_MASK   (((1 << 1) - 1) << 23)
#define SYS_FORCE_RESET_DPHY        (SYS_FORCE_RESET_DPHY_MASK)

#define SYS_FORCE_RESET_SPI_SSISLV_BUS_OFFSET 24
#define SYS_FORCE_RESET_SPI_SSISLV_BUS_BITS   1
#define SYS_FORCE_RESET_SPI_SSISLV_BUS_MASK   (((1 << 1) - 1) << 24)
#define SYS_FORCE_RESET_SPI_SSISLV_BUS        (SYS_FORCE_RESET_SPI_SSISLV_BUS_MASK)

#endif /* ZEPHYR_DRIVERS_RESET_RESET_RTS5817_REG_H_ */
