#
# Copyright (c) 2017, Linaro Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#

obj-$(CONFIG_IEEE802154_KW41Z) += OSAbstraction/Source/fsl_os_abstraction_zephyr.o
obj-$(CONFIG_IEEE802154_KW41Z) += XCVR/
