#
# Copyright (c) 2017, Linaro Ltd.
#
# SPDX-License-Identifier: Apache-2.0
#

obj-y += OSAbstraction/Source/fsl_os_abstraction_zephyr.o
obj-y += XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_gfsk_bt_0p5_h_1p0_config.o
obj-y += XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_gfsk_bt_0p3_h_0p5_config.o
obj-y += XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_gfsk_bt_0p7_h_0p5_config.o
obj-y += XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_ant_config.o
obj-y += XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_mode_datarate_config.o
obj-y += XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_gfsk_bt_0p5_h_0p7_config.o
obj-y += XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_msk_config.o
obj-y += XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_zgbe_config.o
obj-y += XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_ble_config.o
obj-y += XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_common_config.o
obj-y += XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_gfsk_bt_0p5_h_0p32_config.o
obj-y += XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_gfsk_bt_0p5_h_0p5_config.o
obj-y += XCVR/MKW41Z4/fsl_xcvr.o
obj-y += XCVR/MKW41Z4/fsl_xcvr_trim.o
obj-y += XCVR/MKW41Z4/ifr_radio.o
obj-y += XCVR/MKW41Z4/dbg_ram_capture.o
