/**
 * Copyright (c) 2025 TOKITA Hiroshi
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_GPIO_ARDUINO_NANO_HEADER_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_GPIO_ARDUINO_NANO_HEADER_H_

#define ARDUINO_NANO_HEADER_D0  0
#define ARDUINO_NANO_HEADER_D1  1
#define ARDUINO_NANO_HEADER_D2  2
#define ARDUINO_NANO_HEADER_D3  3
#define ARDUINO_NANO_HEADER_D4  4
#define ARDUINO_NANO_HEADER_D5  5
#define ARDUINO_NANO_HEADER_D6  6
#define ARDUINO_NANO_HEADER_D7  7
#define ARDUINO_NANO_HEADER_D8  8
#define ARDUINO_NANO_HEADER_D9  9
#define ARDUINO_NANO_HEADER_D10 10
#define ARDUINO_NANO_HEADER_D11 11
#define ARDUINO_NANO_HEADER_D12 12
#define ARDUINO_NANO_HEADER_D13 13
#define ARDUINO_NANO_HEADER_D14 14
#define ARDUINO_NANO_HEADER_D15 15
#define ARDUINO_NANO_HEADER_D16 16
#define ARDUINO_NANO_HEADER_D17 17
#define ARDUINO_NANO_HEADER_D18 18
#define ARDUINO_NANO_HEADER_D19 19
#define ARDUINO_NANO_HEADER_D20 20
#define ARDUINO_NANO_HEADER_D21 21
#define ARDUINO_NANO_HEADER_A0  14
#define ARDUINO_NANO_HEADER_A1  15
#define ARDUINO_NANO_HEADER_A2  16
#define ARDUINO_NANO_HEADER_A3  19
#define ARDUINO_NANO_HEADER_A4  18
#define ARDUINO_NANO_HEADER_A5  18
#define ARDUINO_NANO_HEADER_A6  20
#define ARDUINO_NANO_HEADER_A7  21

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_GPIO_ARDUINO_NANO_HEADER_H_ */
