# Copyright (c) 2020 Linaro Limited.
# SPDX-License-Identifier: Apache-2.0

name: Zephyr West Command Tests

on:
  push:
    branches:
    - main
    - v*-branch
    - collab-*
    paths:
    - 'scripts/west-commands.yml'
    - 'scripts/west_commands/**'
    - 'scripts/requirements*'
    - '.github/workflows/west_cmds.yml'
  pull_request:
    branches:
    - main
    - v*-branch
    - collab-*
    paths:
    - 'scripts/west-commands.yml'
    - 'scripts/west_commands/**'
    - 'scripts/requirements*'
    - '.github/workflows/west_cmds.yml'

permissions:
  contents: read

jobs:
  west-commands:
    name: West Command Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
        os: [ubuntu-24.04, macos-14, windows-2025]
    steps:
    - name: checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: scripts/requirements-actions.txt

    - name: Install Python packages
      run: |
        pip install -r scripts/requirements-actions.txt --require-hashes

    - name: run pytest-win
      if: runner.os == 'Windows'
      run: |
        python ./scripts/west_commands/run_tests.py

    - name: run pytest-mac-linux
      if: runner.os != 'Windows'
      run: |
        ./scripts/west_commands/run_tests.py
